import assert from 'node:assert/strict';
import fs from 'node:fs';
const p=fs.readFileSync('supabase/functions/powerhouse-social-publisher/index.ts','utf8');
assert.match(p,/const INSTAGRAM_CANONICAL_USERNAME='bedrijfsgeheugen\.nl'/);
assert.doesNotMatch(p,/17841446582493753/);
assert.match(p,/INSTAGRAM_GET_USER_INFO/);
assert.match(p,/COMPOSIO_INSTAGRAM_CANONICAL_IDENTITY_REQUIRED/);
assert.match(p,/ig_user_id:'me'/);
assert.match(p,/ig_user_id:ctx\.providerUserId/);
assert.match(p,/INSTAGRAM_POST_IG_USER_MEDIA_PUBLISH/);
assert.match(p,/INSTAGRAM_GET_IG_MEDIA/);
assert.match(p,/instagram-composio-only-canonical-graph-id-v2/);
const start=p.lastIndexOf("if (row.channel === 'instagram_company') {");
const end=p.indexOf("if (!bufferToken) {",start);
assert.ok(start>=0&&end>start,'Instagram routing block must exist before generic legacy Buffer branch');
const block=p.slice(start,end);
assert.ok(!block.includes('publishInstagramViaMeta'),'Instagram canonical lane must not use direct Meta');
assert.ok(!block.includes('createPost(bufferToken'),'Instagram canonical lane must not use Buffer');
assert.ok(block.includes('canonicalInstagramComposioContext'),'Instagram identity must be preflighted before provider side effect');
assert.ok(block.indexOf('canonicalInstagramComposioContext') < block.indexOf('consumePublishCapability'),'identity preflight must happen before capability consumption');
assert.match(p,/INSTAGRAM_GET_USER_INFO'\s*,\s*\{ig_user_id:'me'/);
console.log('Instagram publication is Composio-only and bound to live Bedrijfsgeheugen provider identity');
