import test from 'node:test';
import assert from 'node:assert/strict';
import {evidenceConvergence,latentDemandScore,choosePortfolio,counterfactualAssessment,attributionClass,learningLifecycle,offerLearning,buildPrediction,intelligenceScorecard} from '../platform/growth-intelligence-engine.mjs';

test('cross-source convergence rewards independent evidence types',()=>{const r=evidenceConvergence([{type:'search',quality:.9},{type:'market',quality:.8},{type:'engagement',quality:.7}]);assert.equal(r.independentTypes,3);assert.ok(r.score>.7);});
test('latent demand combines problem timing fit warmth evidence and value',()=>{const r=latentDemandScore({problemProbability:90,timing:80,fit:85,relationshipWarmth:50,evidenceQuality:.9,expectedValueEur:20000});assert.ok(r.probability>.75);assert.ok(r.expectedRevenueValue>15000);});
test('portfolio preserves exploration budget',()=>{const r=choosePortfolio([{id:'a',expectedRevenueValue:100,novelty:.1},{id:'b',expectedRevenueValue:90,novelty:.9},{id:'c',expectedRevenueValue:80,novelty:.2},{id:'d',expectedRevenueValue:70,novelty:.8}],{explorationRate:.25});assert.equal(r.filter(x=>x.portfolioRole==='EXPLORE').length,1);assert.equal(r.find(x=>x.id==='b').portfolioRole,'EXPLORE');});
test('counterfactual does not fabricate missing baseline',()=>{assert.equal(counterfactualAssessment({observed:5}).status,'INSUFFICIENT_EVIDENCE');assert.equal(counterfactualAssessment({observed:5,baseline:3}).incrementalEffect,2);});
test('attribution separates direct assisted influenced unknown',()=>{assert.equal(attributionClass({directKey:'x',evidenceQuality:.9}),'DIRECT');assert.equal(attributionClass({assistedKeys:['x'],evidenceQuality:.6}),'ASSISTED');assert.equal(attributionClass({directKey:'x',evidenceQuality:.2}),'INFLUENCED');assert.equal(attributionClass({}),'UNKNOWN');});
test('learning lifecycle can promote weaken and retire',()=>{assert.equal(learningLifecycle({sampleSize:5,confidence:.8}),'PROVEN');assert.equal(learningLifecycle({status:'PROVEN',confidence:.5,contradictions:1}),'WEAKENING');assert.equal(learningLifecycle({confidence:.2,contradictions:3}),'RETIRED');});
test('signed offer records order value but not realized revenue without explicit revenue evidence',()=>{assert.equal(offerLearning({amount:2900,signed:false}).revenueEur,0);const x=offerLearning({amount:2900,signed:true});assert.equal(x.orderValueEur,2900);assert.equal(x.revenueEur,0);assert.equal(offerLearning({amount:2900,signed:true,recognizedRevenueEur:1000}).revenueEur,1000);});
test('prediction is explicitly prior to outcome',()=>{const p=buildPrediction({id:'p1',subject:'manufacturing',evidenceRefs:['a','a','b']});assert.equal(p.recordedBeforeOutcome,true);assert.deepEqual(p.evidenceRefs,['a','b']);});
test('scorecard measures prediction error',()=>{const s=intelligenceScorecard({predictions:[{predicted:1,observed:1},{predicted:1,observed:0}]});assert.equal(s.evaluated,2);assert.equal(s.accuracy,.5);assert.equal(s.falsePositiveRate,.5);});
