import test from 'node:test';
import assert from 'node:assert/strict';
import {evidenceConvergence,latentDemandScore,choosePortfolio,counterfactualAssessment,attributionClass,learningLifecycle,offerLearning,buildPrediction,intelligenceScorecard,buildRelationshipRecord,companyIntelligenceProfile,classifyMkbBuyingTriggers,whitespaceScore,calibratePrediction,decayConfidence,attributionSummary} from '../platform/growth-intelligence-engine.mjs';

test('cross-source convergence rewards independent evidence types',()=>{const r=evidenceConvergence([{type:'search',quality:.9},{type:'market',quality:.8},{type:'engagement',quality:.7}]);assert.equal(r.independentTypes,3);assert.ok(r.score>.7);});
test('latent demand combines problem timing fit warmth evidence and value',()=>{const r=latentDemandScore({problemProbability:90,timing:80,fit:85,relationshipWarmth:50,evidenceQuality:.9,expectedValueEur:20000});assert.ok(r.probability>.75);assert.ok(r.expectedRevenueValue>15000);});
test('portfolio preserves exploration budget',()=>{const r=choosePortfolio([{id:'a',expectedRevenueValue:100,novelty:.1},{id:'b',expectedRevenueValue:90,novelty:.9},{id:'c',expectedRevenueValue:80,novelty:.2},{id:'d',expectedRevenueValue:70,novelty:.8}],{explorationRate:.25});assert.equal(r.filter(x=>x.portfolioRole==='EXPLORE').length,1);assert.equal(r.find(x=>x.id==='b').portfolioRole,'EXPLORE');});
test('counterfactual does not fabricate missing baseline',()=>{assert.equal(counterfactualAssessment({observed:5}).status,'INSUFFICIENT_EVIDENCE');assert.equal(counterfactualAssessment({observed:5,baseline:3}).incrementalEffect,2);});
test('attribution separates direct assisted influenced unknown',()=>{assert.equal(attributionClass({directKey:'x',evidenceQuality:.9}),'DIRECT');assert.equal(attributionClass({assistedKeys:['x'],evidenceQuality:.6}),'ASSISTED');assert.equal(attributionClass({directKey:'x',evidenceQuality:.2}),'INFLUENCED');assert.equal(attributionClass({}),'UNKNOWN');});
test('learning lifecycle can promote weaken and retire',()=>{assert.equal(learningLifecycle({sampleSize:5,confidence:.8}),'PROVEN');assert.equal(learningLifecycle({status:'PROVEN',confidence:.5,contradictions:1}),'WEAKENING');assert.equal(learningLifecycle({confidence:.2,contradictions:3}),'RETIRED');});
test('signed offer records order value but not realized revenue without explicit revenue evidence',()=>{const x=offerLearning({amount:2900,signed:true});assert.equal(x.orderValueEur,2900);assert.equal(x.revenueEur,0);});
test('prediction is explicitly prior to outcome',()=>{const p=buildPrediction({id:'p1',subject:'manufacturing',evidenceRefs:['a','a','b']});assert.equal(p.recordedBeforeOutcome,true);assert.deepEqual(p.evidenceRefs,['a','b']);});
test('scorecard measures prediction error',()=>{const s=intelligenceScorecard({predictions:[{predicted:1,observed:1},{predicted:1,observed:0}]});assert.equal(s.accuracy,.5);});

test('relationship records are deterministic and evidence linked',()=>{const r=buildRelationshipRecord({fromType:'company',fromKey:'Acme',toType:'topic',toKey:'ai-adoptie',relation:'exposed_to',confidence:.8,evidenceRefs:['s1','s1','e1'],observedAt:'2026-09-12T18:00:00Z',reviewAt:'2026-12-11T18:00:00Z'});assert.equal(r.record_kind,'relation');assert.equal(r.payload.confidence,.8);assert.deepEqual(r.evidence_ids,['s1','e1']);assert.match(r.record_id,/^relation:/);});
test('company intelligence separates observed from inferred clues',()=>{const p=companyIntelligenceProfile({company:'Acme',connection:{rol:'CIO',prioriteit:80},engagementEvents:[{event_key:'e1',company_name:'Acme'}],externalSignals:[{url:'s1',titel:'Acme werft data engineers',samenvatting:'Vacatures voor data en AI',vertrouwen:90}],now:'2026-09-12T18:00:00Z'});assert.equal(p.observed.role,'CIO');assert.equal(p.observed.engagementCount,1);assert.ok(p.inferred.hiringSignals.length>0);assert.deepEqual(p.sourceRefs.sort(),['e1','s1']);});
test('white-space score rises with demand and falls with observed supply',()=>{const high=whitespaceScore({searchDemand:90,observedSupply:10,evidenceQuality:.9,commercialFit:.8});const low=whitespaceScore({searchDemand:30,observedSupply:80,evidenceQuality:.9,commercialFit:.8});assert.ok(high.score>low.score);assert.ok(high.score>.6);});
test('calibration returns Brier error and keeps counterfactual fail closed',()=>{const x=calibratePrediction({predictedProbability:.8,observedBinary:1});assert.ok(Math.abs(x.brierScore-.04)<1e-9);assert.equal(x.classification,'TRUE_POSITIVE');assert.equal(x.counterfactualStatus,'INSUFFICIENT_EVIDENCE');assert.equal(calibratePrediction({predictedProbability:.8,observedBinary:1,baseline:0}).counterfactualStatus,'ASSESSED');});
test('stale confidence decays and requests review',()=>{const x=decayConfidence({confidence:.8,lastValidatedAt:'2026-03-16T00:00:00Z',now:'2026-09-12T00:00:00Z',halfLifeDays:90});assert.ok(x.confidence<.3);assert.equal(x.reviewRequired,true);});
test('attribution summary deduplicates realized revenue and separates order value',()=>{const s=attributionSummary({growthOutcomes:[{outcome_id:'r1',revenue_eur:1000,payload:{attribution_class:'DIRECT'}},{outcome_id:'r1',revenue_eur:1000,payload:{attribution_class:'DIRECT'}}],salesOutcomes:[{dedupe_key:'order1',revenue_eur:0,evidence:{order_value_eur:2900,attribution_class:'ASSISTED'}}]});assert.equal(s.realizedRevenueEur,1000);assert.equal(s.orderValueEur,2900);assert.equal(s.counts.DIRECT,1);assert.equal(s.counts.ASSISTED,1);});


test('MKB buying triggers require company-specific evidence and produce contextual entry routes',()=>{const x=classifyMkbBuyingTriggers({company:'Acme',connection:{prioriteit:80},engagementEvents:[{company_name:'Acme'}],externalSignals:[{url:'https://example.com/acme-overname',titel:'Acme doet overname van leverancier',samenvatting:'Integratie start dit kwartaal',vertrouwen:90}]});assert.equal(x.status,'EVIDENCE_BACKED');assert.ok(x.score>.6);assert.ok(x.triggers.some(t=>t.type==='acquisition_integration'));assert.ok(x.problemHypotheses.some(v=>/overname/i.test(v)));assert.ok(x.recommendedOffers.includes('Frisse Blik overname & integratie'));assert.ok(x.partnerChannels.includes('m&a-adviseur'));assert.equal(x.outreachMode,'context-led');const none=classifyMkbBuyingTriggers({company:'Acme',externalSignals:[{url:'s2',titel:'Andere BV opent vestiging',vertrouwen:95}]});assert.equal(none.status,'INSUFFICIENT_EVIDENCE');assert.deepEqual(none.triggers,[]);});
