import test from 'node:test';
import assert from 'node:assert/strict';
import { createPortalDataAdapter } from '../portal/data-adapter.mjs';
function store(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)}}
test('adapter uses cached state immediately',async()=>{const s=store();s.setItem('bg.portal.state.v3',JSON.stringify({savedAt:100,state:{id:'cached'}}));const a=createPortalDataAdapter({storage:s,now:()=>110,loadLive:async()=>({id:'live'}),fallbackState:{id:'empty'}});const x=await a.loadInitial();assert.equal(x.source,'cache');assert.equal(x.state.id,'cached')});
test('adapter loads live and caches when cache missing',async()=>{const s=store();const a=createPortalDataAdapter({storage:s,now:()=>100,loadLive:async()=>({id:'live'}),fallbackState:{id:'empty'}});const x=await a.loadInitial();assert.equal(x.source,'live');assert.equal(x.state.id,'live');assert.equal(JSON.parse(s.getItem('bg.portal.state.v3')).state.id,'live')});
test('adapter never falls back to demo data',async()=>{const empty={sourceMeta:{kind:'empty'}};const a=createPortalDataAdapter({storage:store(),fallbackState:empty,loadLive:async()=>{throw new Error('offline')}});const x=await a.loadInitial();assert.equal(x.source,'empty');assert.equal(x.state,empty);assert.match(x.error.message,/offline/)});
test('refresh preserves last known state on live failure',async()=>{const s=store();s.setItem('bg.portal.state.v3',JSON.stringify({savedAt:1,state:{id:'last-good'}}));const a=createPortalDataAdapter({storage:s,loadLive:async()=>{throw new Error('offline')},fallbackState:{id:'empty'}});const x=await a.refresh();assert.equal(x.source,'cache');assert.equal(x.state.id,'last-good');assert.equal(x.changed,false)});
test('unchanged live state does not trigger rerender',async()=>{const s=store();s.setItem('bg.portal.state.v3',JSON.stringify({savedAt:1,state:{id:'same'}}));const a=createPortalDataAdapter({storage:s,loadLive:async()=>({id:'same'})});const x=await a.refresh();assert.equal(x.changed,false);assert.equal(x.source,'live')});
test('refresh skips the live loader while cached state is still fresh',async()=>{let calls=0;const s=store();s.setItem('bg.portal.state.v3',JSON.stringify({savedAt:100,state:{id:'cached'}}));const a=createPortalDataAdapter({storage:s,now:()=>110,ttlMs:60_000,loadLive:async()=>{calls+=1;return{id:'live'}}});const x=await a.refresh();assert.equal(calls,0);assert.equal(x.state.id,'cached');assert.equal(x.changed,false);assert.equal(x.skipped,true);assert.equal(x.source,'cache')});
test('cold load does not immediately perform a second live read',async()=>{let calls=0;const s=store();const a=createPortalDataAdapter({storage:s,now:()=>100,ttlMs:60_000,loadLive:async()=>{calls+=1;return{id:'live'}}});const initial=await a.loadInitial();const refreshed=await a.refresh();assert.equal(initial.source,'live');assert.equal(refreshed.source,'live');assert.equal(refreshed.skipped,true);assert.equal(calls,1)});
test('forced refresh bypasses a fresh cache',async()=>{let calls=0;const s=store();s.setItem('bg.portal.state.v3',JSON.stringify({savedAt:100,state:{id:'cached'}}));const a=createPortalDataAdapter({storage:s,now:()=>110,ttlMs:60_000,loadLive:async()=>{calls+=1;return{id:'live'}}});const x=await a.refresh({force:true});assert.equal(calls,1);assert.equal(x.source,'live');assert.equal(x.state.id,'live')});
test('concurrent stale refreshes share one live request',async()=>{let calls=0;let release;const gate=new Promise(resolve=>{release=resolve});const s=store();s.setItem('bg.portal.state.v3',JSON.stringify({savedAt:0,state:{id:'cached'}}));const a=createPortalDataAdapter({storage:s,now:()=>100_000,ttlMs:60_000,loadLive:async()=>{calls+=1;await gate;return{id:'live'}}});const p1=a.refresh();const p2=a.refresh();assert.equal(calls,1);release();const [x1,x2]=await Promise.all([p1,p2]);assert.equal(calls,1);assert.equal(x1.state.id,'live');assert.equal(x2.state.id,'live')});
