import test from 'node:test';
import assert from 'node:assert/strict';
import { createPortalDataAdapter } from '../portal/data-adapter.mjs';
function store(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)}}
test('adapter uses cached state immediately',async()=>{const s=store();s.setItem('bg.portal.state.v3',JSON.stringify({savedAt:100,state:{id:'cached'}}));const a=createPortalDataAdapter({storage:s,now:()=>110,loadLive:async()=>({id:'live'}),fallbackState:{id:'empty'}});const x=await a.loadInitial();assert.equal(x.source,'cache');assert.equal(x.state.id,'cached')});
test('adapter loads live and caches when cache missing',async()=>{const s=store();const a=createPortalDataAdapter({storage:s,now:()=>100,loadLive:async()=>({id:'live'}),fallbackState:{id:'empty'}});const x=await a.loadInitial();assert.equal(x.source,'live');assert.equal(x.state.id,'live');assert.equal(JSON.parse(s.getItem('bg.portal.state.v3')).state.id,'live')});
test('adapter never falls back to demo data',async()=>{const empty={sourceMeta:{kind:'empty'}};const a=createPortalDataAdapter({storage:store(),fallbackState:empty,loadLive:async()=>{throw new Error('offline')}});const x=await a.loadInitial();assert.equal(x.source,'empty');assert.equal(x.state,empty);assert.match(x.error.message,/offline/)});
test('refresh preserves last known state on live failure',async()=>{const s=store();s.setItem('bg.portal.state.v3',JSON.stringify({savedAt:1,state:{id:'last-good'}}));const a=createPortalDataAdapter({storage:s,loadLive:async()=>{throw new Error('offline')},fallbackState:{id:'empty'}});const x=await a.refresh();assert.equal(x.source,'cache');assert.equal(x.state.id,'last-good');assert.equal(x.changed,false)});
test('unchanged live state does not trigger rerender',async()=>{const s=store();s.setItem('bg.portal.state.v3',JSON.stringify({savedAt:1,state:{id:'same'}}));const a=createPortalDataAdapter({storage:s,loadLive:async()=>({id:'same'})});const x=await a.refresh();assert.equal(x.changed,false);assert.equal(x.source,'live')});
