import test from 'node:test';
import assert from 'node:assert/strict';
import {portalStateKey,sanitizePortalState,readPortalState,writePortalState} from '../netlify/functions/_portal-state-store.mjs';
import {choosePortalState,loadServerPortalState,saveServerPortalState} from '../portal/server-state.mjs';
function fakeStore(){const map=new Map();return{get:async k=>map.get(k)||null,setJSON:async(k,v)=>map.set(k,v),map}}
test('server state key is scoped only by verified identity id',()=>{assert.equal(portalStateKey('user-123'),'identity/user-123/canonical-state');assert.throws(()=>portalStateKey(''))});
test('server snapshot strips unknown top-level and tenant override fields',()=>{const clean=sanitizePortalState({company:{name:'Acme'},actions:[],tenantId:'other',secret:'x'});assert.deepEqual(clean,{company:{name:'Acme'},actions:[]});assert.equal('tenantId'in clean,false)});
test('snapshot store revisions one canonical record per identity',async()=>{const s=fakeStore();const one=await writePortalState(s,'u1',{company:{name:'A'}},{now:()=> '2026-01-01T00:00:00Z'});const two=await writePortalState(s,'u1',{company:{name:'B'}},{now:()=> '2026-01-02T00:00:00Z'});assert.equal(one.revision,1);assert.equal(two.revision,2);assert.equal((await readPortalState(s,'u1')).state.company.name,'B')});
test('newer local legacy state migrates once; newer server state wins',()=>{const local={sourceMeta:{updatedAt:'2026-08-29T10:00:00Z'}};const oldServer={sourceMeta:{updatedAt:'2026-08-28T10:00:00Z'}};const freshServer={sourceMeta:{updatedAt:'2026-08-30T10:00:00Z'}};assert.deepEqual(choosePortalState({serverState:oldServer,localState:local}),{state:local,source:'local',shouldPersist:true});assert.deepEqual(choosePortalState({serverState:freshServer,localState:local}),{state:freshServer,source:'server',shouldPersist:false})});
test('client always sends authenticated bearer token and same-origin credentials',async()=>{const calls=[];const user={jwt:async()=> 'token-1'};const fetchImpl=async(url,options)=>{calls.push({url,options});return{ok:true,status:200,json:async()=>({state:{company:{name:'A'}}})}};const state=await loadServerPortalState({user,fetchImpl});assert.equal(state.company.name,'A');assert.equal(calls[0].options.headers.authorization,'Bearer token-1');assert.equal(calls[0].options.credentials,'same-origin');await saveServerPortalState({user,state,fetchImpl});assert.equal(calls[1].options.method,'PUT');assert.equal(calls[1].options.headers.authorization,'Bearer token-1')});
