import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const html=await readFile(new URL('../portal/index.html',import.meta.url),'utf8');const css=await readFile(new URL('../portal/styles.css',import.meta.url),'utf8');const app=await readFile(new URL('../portal/app.mjs',import.meta.url),'utf8');const shell=await readFile(new URL('../portal/render-shell.mjs',import.meta.url),'utf8');const today=await readFile(new URL('../portal/render-today.mjs',import.meta.url),'utf8');
test('portal entry has no static href attributes',()=>assert.equal(html.includes('href='),false));
test('approved white enterprise design tokens are binding',()=>{for(const token of ['--bg:#f8faff','--surface:#fff','--ink:#0b1741','--blue:#1557ff','.sidebar','.topbar','.dashboard-grid','.right-rail'])assert.ok(css.includes(token),token);assert.equal(css.includes('--forest:'),false)});
test('portal includes responsive and reduced-motion design',()=>{assert.ok(css.includes('@media(max-width:820px)'));assert.ok(css.includes('prefers-reduced-motion'));assert.ok(css.includes('.mobile-nav'))});
test('shell retains legacy navigation and approved topbar',()=>{for(const text of ['Overzicht','Bedrijfsgezondheid','Strategie & uitvoering','Processen & organisatie','Kennis','Data & koppelingen','AI & Insights','Acties & impact','Rapportages','BEHEER','Koppelingen bouwen','Roadmap','Facturen & abonnement','Organisatie & gebruikers','Instellingen','Frisse Blik Scan','Vraag het Bedrijfsgeheugen AI'])assert.ok(shell.includes(text),text)});
test('today preserves legacy dashboard surfaces',()=>{for(const text of ['AI Management Summary','Alles verbonden in één overzicht','Impact deze maand','Recente activiteiten','Koppelingen status','Roadmap & voortgang','Aanbevolen acties','Snelle links'])assert.ok(today.includes(text),text)});
test('portal supports search contextual AI and detail drawer',()=>{assert.ok(shell.includes('command-modal'));assert.ok(shell.includes('Bedrijfsgeheugen AI'));assert.ok(app.includes('openDetail'))});
test('portal exposes all eight canonical route renderers',()=>{for(const id of ['today','company','intelligence','decisions','execution','impact','memory','admin'])assert.ok(app.includes(id+':'),id)});
test('sample fallback is explicitly labelled',()=>assert.ok(shell.includes('Prototype · voorbeelddata')));
