import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const workflow = await readFile(new URL('../.github/workflows/supabase-production-baseline-capture.yml', import.meta.url), 'utf8');

test('production baseline capture runs only from trusted default-branch workflow code', () => {
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /push:\n\s+branches: \[main\]/);
  assert.doesNotMatch(workflow, /pull_request:/);
  assert.match(workflow, /permissions:\n\s+contents: write\n\s+pull-requests: write/);
});

test('baseline is generated by official Supabase CLI commands, never pg_catalog reconstruction', () => {
  assert.match(workflow, /supabase db dump --linked -f \/tmp\/bg3742-baseline\/schema\.sql/);
  assert.match(workflow, /supabase db dump --linked -f \/tmp\/bg3742-baseline\/history-data\.sql --use-copy --data-only --schema supabase_migrations/);
  assert.match(workflow, /supabase migration list --linked/);
  assert.doesNotMatch(workflow, /pg_catalog/i);
  assert.doesNotMatch(workflow, /information_schema/i);
});

test('baseline write is exact-head leased and fail-closed', () => {
  assert.match(workflow, /EXPECTED_HEAD/);
  assert.match(workflow, /Recovery branch moved before baseline write/);
  assert.match(workflow, /--force-with-lease="refs\/heads\/\$TARGET_BRANCH:\$EXPECTED_HEAD"/);
  assert.match(workflow, /production_write:false/);
  assert.match(workflow, /hand_built_catalog_dump:false/);
});
