import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const workflow = await readFile(new URL('../.github/workflows/supabase-production-baseline-capture.yml', import.meta.url), 'utf8');

test('production baseline capture runs only from trusted default-branch workflow code', () => {
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /push:\n\s+branches: \[main\]/);
  assert.doesNotMatch(workflow, /pull_request:/);
  assert.match(workflow, /permissions:\n\s+contents: write\n\s+pull-requests: write/);
  assert.match(workflow, /refs\\/heads\\/main/);
  assert.match(workflow, /version: 2\\.119\\.0/);
});

test('baseline is generated by official Supabase CLI commands, never pg_catalog reconstruction', () => {
  assert.match(workflow, /supabase db dump --linked -f \/tmp\/bg3742-baseline\/schema\.sql/);
  assert.match(workflow, /supabase db dump --linked -f \/tmp\/bg3742-baseline\/history-data\.sql --use-copy --data-only --schema supabase_migrations/);
  assert.match(workflow, /supabase migration list --linked/);
  assert.doesNotMatch(workflow, /--role-only/);
  assert.doesNotMatch(workflow, /pg_catalog/i);
  assert.doesNotMatch(workflow, /information_schema/i);
});

test('baseline write is exact-head leased and fail-closed', () => {
  assert.match(workflow, /EXPECTED_HEAD/);
  assert.match(workflow, /Recovery branch moved before baseline write/);
  assert.match(workflow, /--force-with-lease="refs\/heads\/\$TARGET_BRANCH:\$EXPECTED_HEAD"/);
  assert.match(workflow, /production_write:false/);
  assert.match(workflow, /hand_built_catalog_dump:false/);
});

test('production credentials are scoped only to the official capture step', () => {
  const jobPrefix = workflow.split('- name: Capture official production baseline with Supabase CLI')[0];
  assert.doesNotMatch(jobPrefix, /secrets\.SUPABASE_ACCESS_TOKEN/);
  assert.doesNotMatch(jobPrefix, /secrets\.PRODUCTION_DB_PASSWORD/);
  const capture = workflow.split('- name: Capture official production baseline with Supabase CLI')[1]?.split('- name: Write immutable baseline')[0] || '';
  assert.match(capture, /secrets\.SUPABASE_ACCESS_TOKEN/);
  assert.match(capture, /secrets\.PRODUCTION_DB_PASSWORD/);
  assert.match(capture, /rm -rf supabase\/\.temp \.supabase/);
});

test('canonical recovery selection is unique and baseline write advances writer lease metadata', () => {
  assert.match(workflow, /Resolve unique highest-version canonical recovery/);
  assert.match(workflow, /Multiple open canonical recoveries share highest version/);
  assert.match(workflow, /Writer-Lease-Head/);
  assert.match(workflow, /--method PATCH/);
});
