import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const workflow = await readFile(new URL('../.github/workflows/supabase-production-baseline-capture.yml', import.meta.url), 'utf8');

test('production baseline capture runs only from trusted default-branch workflow code', () => {
  assert.match(workflow, /workflow_dispatch:/);
  assert.match(workflow, /push:\n\s+branches: \[main\]/);
  assert.doesNotMatch(workflow, /pull_request:/);
  assert.match(workflow, /permissions:\n\s+contents: write\n\s+pull-requests: write/);
  assert.match(workflow, /refs\\/heads\\/main/);
  assert.match(workflow, /version: 2\\.119\\.0/);
});

test('baseline is generated by official Supabase CLI commands, never pg_catalog reconstruction', () => {
  assert.match(workflow, /supabase db dump --linked -f \/tmp\/bg3742-baseline\/schema\.sql/);
  assert.match(workflow, /supabase db dump --linked -f \/tmp\/bg3742-baseline\/history-data\.sql --use-copy --data-only --schema supabase_migrations/);
  assert.match(workflow, /supabase migration list --linked/);
  assert.match(workflow, /supabase migration repair --linked --status applied/);
  for (const version of ['20260920101150','20260920102450','20260925080500','20261005133951']) assert.match(workflow,new RegExp(version));
  assert.doesNotMatch(workflow, /--role-only/);
  assert.doesNotMatch(workflow, /pg_catalog/i);
  assert.doesNotMatch(workflow, /information_schema/i);
});

test('baseline write is exact-head leased and fail-closed', () => {
  assert.match(workflow, /EXPECTED_HEAD/);
  assert.match(workflow, /Recovery branch moved before baseline write/);
  assert.match(workflow, /--force-with-lease="refs\/heads\/\$TARGET_BRANCH:\$EXPECTED_HEAD"/);
    assert.match(workflow, /hand_built_catalog_dump:false/);
  assert.match(workflow, /supabase migration repair/);
  assert.match(workflow, /20260920101150/);
  assert.match(workflow, /20260920102450/);
  assert.match(workflow, /20260925080500/);
  assert.match(workflow, /20261005133951/);
  assert.match(workflow, /PRE_REPAIR_PARITY_NOT_EXACT/);
  assert.match(workflow, /POST_REPAIR_PARITY_DRIFT/);
  assert.match(workflow, /sql_reexecuted:false/);
});

test('supported migration repair is bounded by candidate evidence and exact tracking readback', () => {
  assert.match(workflow, /candidate-lock\.json/);
  assert.match(workflow, /EFFECT_VERIFIED_REPAIR_REQUIRED/);
  assert.match(workflow, /SUPPORTED_MIGRATION_REPAIR_NOT_VISIBLE/);
  assert.match(workflow, /CANDIDATE_REPAIR_SET_NOT_EXACT/);
  assert.match(workflow, /P0_PROOF_EFFECT_NOT_VERIFIED/);
  assert.match(workflow, /OUTBOUND_QUALITY_FUNCTION_NOT_VERIFIED/);
  assert.match(workflow, /MESSAGE_QUALITY_RLS_NOT_VERIFIED/);
  assert.match(workflow, /MESSAGE_QUALITY_PRIVILEGE_CONTRACT_NOT_VERIFIED/);
  assert.match(workflow, /supabase db query --linked/);
  assert.match(workflow, /REPAIRED_APPLIED_VERIFIED/);
  assert.match(workflow, /history-data\.sql/);
});

test('production credentials are scoped only to the official capture step', () => {
  const jobPrefix = workflow.split('- name: Capture official production baseline with Supabase CLI')[0];
  assert.doesNotMatch(jobPrefix, /secrets\.SUPABASE_ACCESS_TOKEN/);
  assert.doesNotMatch(jobPrefix, /secrets\.PRODUCTION_DB_PASSWORD/);
  const capture = workflow.split('- name: Capture official production baseline with Supabase CLI')[1]?.split('- name: Write immutable baseline')[0] || '';
  assert.match(capture, /secrets\.SUPABASE_ACCESS_TOKEN/);
  assert.match(capture, /secrets\.PRODUCTION_DB_PASSWORD/);
  assert.match(capture, /rm -rf supabase\/\.temp \.supabase/);
});

test('canonical recovery selection is unique and baseline write advances writer lease metadata', () => {
  assert.match(workflow, /Resolve unique highest-version canonical recovery/);
  assert.match(workflow, /Multiple open canonical recoveries share highest version/);
  assert.match(workflow, /Writer-Lease-Head/);
  assert.match(workflow, /--method PATCH/);
});


test('baseline capture dynamically selects one highest canonical recovery and pins CLI', () => {
  assert.match(workflow, /supabase-migration-history-canonical-v/);
  assert.match(workflow, /Multiple open canonical recoveries share highest version/);
  assert.match(workflow, /version: 2\.119\.0/);
});
