const p=(primaryAction,metrics,worklist,actions)=>({
  primaryAction,
  blocks:[
    {type:'metrics',title:'Stand van zaken',items:metrics},
    {type:'worklist',title:'Wat vraagt aandacht',items:worklist},
    {type:'actions',title:'Volgende acties',items:actions}
  ]
});

export const NATIVE_PAGE_CONTENT = Object.freeze({
  overzicht:p('Open prioriteiten',[['Gezondheid','72/100'],['Open acties','18'],['Waarde YTD','€ 1,24M']],[['Topprioriteit','Kennisborging Finance'],['Risico','Datakwaliteit klantdata'],['Kans','Offerteproces automatiseren']],[['Bekijk management summary','brain-verwerking'],['Open roadmap','roadmap'],['Bekijk impact','csrd-impact']]),
  profiel:p('Werk profiel bij',[['Compleet','82%'],['Domeinen','9'],['Open hiaten','6']],[['Finance','Kennisafhankelijkheid'],['Operations','Procesvariatie'],['Sales','CRM-adoptie']],[['Vul ontbrekende gegevens aan','gegevens-invullen'],['Open eindconclusie','eindconclusie'],['Bekijk wijzigingen','wijzigingen']]),
  'data-ai':p('Prioriteer datakans',[['Bronnen','33'],['Datakwaliteit','74/100'],['AI-volwassenheid','54/100']],[['CRM','Dubbele klantrecords'],['Documenten','Metadata onvolledig'],['AI','3 kansen zonder eigenaar']],[['Open koppelingen','koppelingen'],['Bekijk AI-scan','ai-scan'],['Open bronnenstatus','bronnenstatus']]),
  'ai-scan':p('Start kansanalyse',[['Kansen','12'],['Hoge waarde','4'],['Ready','5']],[['Offertes','Hoge impact / hoge haalbaarheid'],['Service','Veel handwerk'],['Finance','Kennisrisico beperkt schaalbaarheid']],[['Open kansenkaart','kansenkaart'],['Maak businesscase','businesscase'],['Zet actie uit','actieve-acties']]),
  kansenkaart:p('Kies volgende kans',[['Kansen','12'],['Waarde-potentieel','€ 430K'],['Snelle wins','5']],[['Automatisering','Offerte → order'],['Data','Klantbeeld verrijken'],['AI','Kennisassistent Finance']],[['Open AI-scan','ai-scan'],['Maak businesscase','businesscase'],['Plan in roadmap','roadmap']]),
  'csrd-impact':p('Open impactcockpit',[['Impactdomeinen','6'],['Open acties','9'],['Auditbewijs','In opbouw']],[['CO₂','Datadekking uitbreiden'],['Water','Scope verifiëren'],['Social','Evidence actualiseren']],[['Open audit','audit'],['Open compliance','compliance-governance'],['Bekijk acties','actieve-acties']]),
  'gegevens-invullen':p('Vul volgende sectie in',[['Ingevuld','78%'],['Ontbrekend','11'],['Verouderd','5']],[['Strategie','Doelstellingen 2027'],['Mensen','Kritieke rollen'],['Systemen','Eigenaar per applicatie']],[['Bekijk ingevulde gegevens','ingevulde-gegevens'],['Open profiel','profiel'],['Bekijk risico-impact','eindconclusie']]),
  'ingevulde-gegevens':p('Controleer actualiteit',[['Records','164'],['Bronvermelding','91%'],['Review nodig','14']],[['Finance','3 antwoorden ouder dan 6 maanden'],['HR','2 ontbrekende eigenaren'],['IT','Architectuurinformatie incompleet']],[['Werk gegevens bij','gegevens-invullen'],['Open wijzigingen','wijzigingen'],['Open audit','audit']]),
  businesscase:p('Maak scenario',[['Potentiële baten','€ 310K'],['Investering','€ 96K'],['Terugverdientijd','7 mnd']],[['Aannames','2 nog te valideren'],['Capaciteit','Data engineering nodig'],['Risico','Adoptie sales']],[['Vergelijk scenario’s','waarde-financiering'],['Plan uitvoering','roadmap'],['Maak offerte','offerte']]),
  'cijfers-maatstaven':p('Bekijk afwijkingen',[['KPI’s','24'],['Op koers','17'],['Afwijkend','7']],[['Doorlooptijd offerte','+18% t.o.v. doel'],['Datakwaliteit','-9 p.p. onder norm'],['Kennisborging','Verbetering stagneert']],[['Open businesscase','businesscase'],['Bekijk branche','branche-markt'],['Zet actie uit','actieve-acties']]),
  'waarde-financiering':p('Open scenario’s',[['Indicatieve waarde','€ 8,4M'],['Waardedrijvers','7'],['Financieringsruimte','€ 1,1M']],[['Recurring omzet','Onder benchmark'],['Afhankelijkheid eigenaar','Waardedrukkend'],['Digitalisering','Waarde-opwaarts']],[['Open due diligence','due-diligence'],['Open exit','exit'],['Maak businesscase','businesscase']]),
  mensen:p('Pak kennisrisico aan',[['Medewerkers','84'],['Kritieke rollen','11'],['Kennisrisico’s','5']],[['Finance','1 single point of failure'],['Operations','Capaciteit onder norm'],['Sales','Onboarding duurt te lang']],[['Open kennis','documenten'],['Maak taak','taken-werkstromen'],['Bekijk profiel','profiel']]),
  'branche-markt':p('Vergelijk benchmark',[['Benchmarks','18'],['Boven markt','8'],['Onder markt','6']],[['Doorlooptijd','Langzamer dan branche'],['Digitale selfservice','Achterstand'],['Retentie','Boven benchmark']],[['Open cijfers','cijfers-maatstaven'],['Bekijk kansen','kansenkaart'],['Open onderzoek','onderzoek']]),
  onderzoek:p('Leg bevinding vast',[['Onderzoeken','7'],['Open hypotheses','9'],['Bronnen','28']],[['Klantverlies','Oorzaak nog niet bewezen'],['Procesdata','Steekproef uitbreiden'],['Markt','Nieuwe concurrent analyseren']],[['Open eindconclusie','eindconclusie'],['Voeg document toe','documenten'],['Maak actie','actieve-acties']]),
  'compliance-governance':p('Pak hoogste risico',[['Frameworks','4'],['Open controls','13'],['Hoog risico','4']],[['AI Act','AI-inventaris onvolledig'],['NIS2','Leveranciersbewijs ontbreekt'],['AVG','Retentiebeleid review nodig']],[['Open command center','compliance-command-center'],['Open audit','audit'],['Maak actie','actieve-acties']]),
  'compliance-command-center':p('Open auditpakket',[['Readiness','68%'],['Open risico’s','13'],['Evidence gaps','21']],[['AI Act','Classificatie afronden'],['NIS2','Incidentproces toetsen'],['Governance','Control owner bevestigen']],[['Open compliance','compliance-governance'],['Open audit','audit'],['Open acties','actieve-acties']]),
  'ai-capabilities':p('Beoordeel capability',[['Capabilities','16'],['Actief','7'],['Pilot','4']],[['RAG','Bronkwaliteit bewaken'],['Agents','Human override vastleggen'],['Forecasting','Modelmonitoring toevoegen']],[['Open Brain','brain-verwerking'],['Open agentstatus','agentstatus'],['Open AI-scan','ai-scan']]),
  strategiemodellen:p('Open strategiemodel',[['Modellen','8'],['Actief gebruikt','4'],['Review nodig','2']],[['SWOT','Actualiseren'],['OGSM','Measures aanscherpen'],['Porter','Marktdata vernieuwen']],[['Open canvassen','canvassen'],['Open eindconclusie','eindconclusie'],['Vertaal naar uitvoering','strategie-naar-maandagochtend']]),
  modellen:p('Kies model',[['Modellen','14'],['In gebruik','7'],['Templates','11']],[['Businesscase','Aannames herzien'],['Risicomodel','Nieuwe controls verwerken'],['Waardemodel','Scenario 2027 toevoegen']],[['Open strategiemodellen','strategiemodellen'],['Open canvassen','canvassen'],['Open onderzoek','onderzoek']]),
  canvassen:p('Werk canvas bij',[['Canvassen','9'],['Compleet','6'],['Open review','3']],[['Business Model','Value proposition review'],['Execution','Eigenaren ontbreken'],['AI Canvas','Risicokaders aanvullen']],[['Open strategiemodellen','strategiemodellen'],['Open roadmap','roadmap'],['Vertaal naar uitvoering','strategie-naar-maandagochtend']]),
  eindconclusie:p('Bespreek conclusie',[['Sterktes','8'],['Risico’s','6'],['Prioriteiten','5']],[['Kennis','Te persoonsafhankelijk'],['Data','Fundament voldoende, kwaliteit wisselt'],['Uitvoering','Prioritering kan scherper']],[['Open roadmap','roadmap'],['Open advies','advies'],['Bekijk management summary','brain-verwerking']]),
  'due-diligence':p('Open dossier',[['Domeinen','10'],['Issues','23'],['Materieel','6']],[['Finance','Datadekking controleren'],['IT','Legacy afhankelijkheden'],['People','Kritieke kennisdragers']],[['Open waarde','waarde-financiering'],['Open audit','audit'],['Open exit','exit']]),
  exit:p('Beoordeel exit-readiness',[['Readiness','64%'],['Waardedrijvers','7'],['Red flags','5']],[['Eigenaar','Operationele afhankelijkheid'],['Kennis','Niet volledig geborgd'],['Data','Rapportage reproduceerbaarheid']],[['Open due diligence','due-diligence'],['Open waarde','waarde-financiering'],['Plan verbeteringen','roadmap']]),
  'strategie-naar-maandagochtend':p('Maak uitvoeringsactie',[['Strategische thema’s','5'],['Capabilities','17'],['Open acties','18']],[['Groei','CRM capability verbeteren'],['Efficiency','Offerteproces automatiseren'],['Risico','Finance kennis borgen']],[['Open roadmap','roadmap'],['Open uitvoeringsladder','uitvoeringsladder'],['Maak taken','taken-werkstromen']]),
  'actueel-houden':p('Werk verouderde bron bij',[['Actueel','86%'],['Verouderd','9'],['Zonder eigenaar','4']],[['Proceshandboek','9 maanden oud'],['Systeemlandschap','Nieuwe applicatie ontbreekt'],['KPI-definities','Review verlopen']],[['Open wijzigingen','wijzigingen'],['Open documenten','documenten'],['Maak taak','taken-werkstromen']]),
  wijzigingen:p('Beoordeel wijziging',[['Wijzigingen 30d','42'],['Materieel','8'],['Open opvolging','11']],[['CRM','Nieuwe velden raken rapportage'],['Organisatie','Finance rol gewijzigd'],['Compliance','Nieuwe control toegevoegd']],[['Open impact','actieve-acties'],['Open audittrail','audittrail'],['Werk profiel bij','profiel']]),
  advies:p('Zet advies om in actie',[['Adviezen','14'],['Hoog','5'],['Geaccepteerd','8']],[['Kennisborging','Start binnen 30 dagen'],['CRM','Datakwaliteit eerst'],['AI','Begin met offerte-assistent']],[['Maak roadmap-item','roadmap'],['Open businesscase','businesscase'],['Maak offerte','offerte']]),
  offerte:p('Werk voorstel uit',[['Voorstellen','4'],['Open','2'],['Geaccepteerd','1']],[['Scope','Datahub fase 1'],['Randvoorwaarde','Eigenaar klantdata'],['Planning','Startmoment bevestigen']],[['Open businesscase','businesscase'],['Open roadmap','roadmap'],['Open taken','taken-werkstromen']]),
  roadmap:p('Plan volgende mijlpaal',[['Nu','6'],['Volgende','8'],['Afgerond','23']],[['Klantdata opschonen','75%'],['Onboarding optimaliseren','60%'],['Kennisborging Finance','20%']],[['Open taken','taken-werkstromen'],['Open actieve acties','actieve-acties'],['Bekijk outcomes','outcomes-evidence']]),
  uitvoeringsladder:p('Verhoog borgingsniveau',[['Tellen','12'],['Meten','8'],['Geborgd','5']],[['CRM-adoptie','Meten → borgen'],['Offerteproces','Koppelen → meten'],['Kennis Finance','Vastleggen → koppelen']],[['Open roadmap','roadmap'],['Open taken','taken-werkstromen'],['Open outcomes','outcomes-evidence']]),
  'taken-werkstromen':p('Maak taak',[['Open taken','38'],['Deze week','11'],['Geblokkeerd','4']],[['Finance','Kennisdocumentatie'],['Sales','CRM cleanup'],['IT','Connector readiness']],[['Open actieve acties','actieve-acties'],['Open roadmap','roadmap'],['Bekijk wijzigingen','wijzigingen']]),
  bronnenstatus:p('Herstel bron',[['Bronnen','33'],['Gezond','27'],['Aandacht','6']],[['CRM','Sync vertraagd'],['HR','Owner ontbreekt'],['Documenten','Index achterstand']],[['Open koppelingen','koppelingen'],['Open datahub','datahubstatus'],['Maak recovery','recovery-obligations']]),
  datahubstatus:p('Bekijk dataketen',[['Datasets','41'],['Gezond','35'],['Quarantaine','2']],[['Klantmaster','Deduplicatie nodig'],['Finance','Schema wijziging gedetecteerd'],['Documenten','Metadata verrijking loopt']],[['Open bronnen','bronnenstatus'],['Open Brain','brain-verwerking'],['Open self-heal','self-heal']]),
  'brain-verwerking':p('Open besliscontext',[['Contextsets','19'],['Adviezen','14'],['Evidence gaps','7']],[['Finance','Bronactualiteit laag'],['Sales','Tegenstrijdige KPI-definitie'],['Compliance','Control evidence incompleet']],[['Open outcomes','outcomes-evidence'],['Open learning','learning-writeback'],['Open agentstatus','agentstatus']]),
  agentstatus:p('Bekijk agent',[['Agents','12'],['Actief','9'],['Geblokkeerd','2']],[['Connector agent','Provider readiness'],['Content agent','Review vereist'],['Recovery agent','1 obligation open']],[['Open acties','actieve-acties'],['Open recovery','recovery-obligations'],['Open audittrail','audittrail']]),
  'actieve-acties':p('Prioriteer actie',[['Open','18'],['Hoog','6'],['Met evidence','12']],[['Finance','Kennis borgen'],['CRM','Datakwaliteit herstellen'],['NIS2','Leveranciersbewijs verzamelen']],[['Open taken','taken-werkstromen'],['Open outcomes','outcomes-evidence'],['Open roadmap','roadmap']]),
  'recovery-obligations':p('Sluit recovery loop',[['Open','4'],['Geblokkeerd','1'],['Oudste','3 dagen']],[['Connector','Providerconfiguratie'],['Brain writeback','Runtime capacity'],['Dataset','Schema drift']],[['Open self-heal','self-heal'],['Open audittrail','audittrail'],['Bekijk outcomes','outcomes-evidence']]),
  'outcomes-evidence':p('Verifieer outcome',[['Outcomes','31'],['Bewezen','22'],['Evidence gap','9']],[['Offertes','Tijdwinst nog meten'],['CRM','Foutreductie bewezen'],['Onboarding','NPS-effect nog open']],[['Open learning','learning-writeback'],['Open audittrail','audittrail'],['Open roadmap','roadmap']]),
  'learning-writeback':p('Schrijf learning terug',[['Learnings','47'],['Duurzaam','42'],['Open writeback','5']],[['CRM','Dedupe-regel herbruikbaar'],['Release','Live readback verplicht'],['Brain','Capacity blocker open']],[['Open outcomes','outcomes-evidence'],['Open audittrail','audittrail'],['Open self-heal','self-heal']]),
  'self-heal':p('Open herstelactie',[['Signals','7'],['Automatisch hersteld','4'],['Mens nodig','2']],[['Connector','Safe retry toegestaan'],['Dataset','Schema rollback klaar'],['Capacity','Geen retry tot vrijgave']],[['Open recovery','recovery-obligations'],['Open agentstatus','agentstatus'],['Open audittrail','audittrail']]),
  audittrail:p('Filter audittrail',[['Events 30d','418'],['Besluiten','67'],['Evidence links','189']],[['Release','Production readback'],['Compliance','Control status gewijzigd'],['Brain','Learning writeback poging']],[['Open audit','audit'],['Open outcomes','outcomes-evidence'],['Open wijzigingen','wijzigingen']]),
  koppelingen:p('Beheer koppeling',[['Koppelingen','18'],['Ready','13'],['Setup nodig','5']],[['Exact','Gezond'],['CRM','Datakwaliteit waarschuwing'],['HR','Providerconfiguratie nodig']],[['Open bronnenstatus','bronnenstatus'],['Open datahub','datahubstatus'],['Maak taak','taken-werkstromen']]),
  gebruikers:p('Beheer gebruiker',[['Gebruikers','24'],['Beheerders','3'],['Review rechten','5']],[['Finance','Rolreview nodig'],['Extern','Tijdelijke toegang verloopt'],['Auditor','Read-only toegang actief']],[['Open audit','audit'],['Open instellingen','instellingen'],['Bekijk wijzigingen','wijzigingen']]),
  documenten:p('Voeg document toe',[['Documenten','286'],['Actueel','91%'],['Review nodig','19']],[['Finance handboek','Actualiseren'],['Privacybeleid','Review gepland'],['Proces Offerte','Eigenaar ontbreekt']],[['Open actueel houden','actueel-houden'],['Open kennisprofiel','profiel'],['Open audit','audit']]),
  instellingen:p('Beheer instellingen',[['Configuraties','31'],['Compleet','27'],['Aandacht','4']],[['Notificaties','Escalatie-eigenaar'],['Data','Retentieperiode review'],['AI','Human override policy']],[['Open gebruikers','gebruikers'],['Open compliance','compliance-governance'],['Open audit','audit']]),
  audit:p('Exporteer auditoverzicht',[['Controls','44'],['Evidence compleet','76%'],['Open bevindingen','12']],[['AI Act','Inventaris afronden'],['NIS2','Leveranciersbewijs'],['Data','Lineage evidence']],[['Open compliance','compliance-governance'],['Open audittrail','audittrail'],['Open documenten','documenten']])
});

export function nativePageContent(pageId){
  return NATIVE_PAGE_CONTENT[pageId] || null;
}
