const n=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const nl=(v,d=1)=>n(v).toLocaleString('nl-NL',{minimumFractionDigits:d,maximumFractionDigits:d});
const freeze=value=>Object.freeze(value);
function portal(s){return s?.portal||{}}
function profile(s){return portal(s).profile||{}}
function market(s){return portal(s).market||{}}
function metrics(s){return portal(s).metrics||{}}
function maturity(s){return profile(s).maturity||profile(s).dimensions||{}}
function level(s,key,fallback=0){return n(maturity(s)[key],fallback)}
function maturityValues(s){return Object.values(maturity(s)).map(Number).filter(v=>Number.isFinite(v)&&v>=1&&v<=5)}
function companyMaturity(s){const xs=maturityValues(s);return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0}
function branchGrowth(s){const m=market(s);return n(m.growth??m.industryGrowth??m.brancheGrowth,0)}
function branchDigital(s){const m=market(s);return n(m.digitalMaturity??m.digitalIntensity??m.benchmarkDigitalMaturity,0)}
function noteFor(s,id){return String(portal(s).strategicModels?.[id]?.note||'')}
function modelBase(state,id,title,source,signal,explanation,conclusion,evidence,extra={}){return freeze({id,title,source,signal,explanation,conclusion,evidence,note:noteFor(state,id),notePath:`portal.strategicModels.${id}.note`,prompt:'Welke context of nuance wil je bij dit model vastleggen?',...extra})}
const dims=freeze([
 ['sturing','Strategie en sturing'],['commercie','Commercie en klant'],['operatie','Operatie en levering'],['finance','Finance'],['mensen','Mensen en kennis'],['analytics','Stuurinformatie'],['quality','Datakwaliteit'],['governance','Governance'],['tech','Systemen en AI'],['culture','Organisatie en cultuur'],['service','Klantenservice'],['security','Beveiliging'],['duurzaam','Duurzaamheid en CSRD']
]);
function weakest(state){return dims.map(([id,label])=>({id,label,value:level(state,id)})).sort((a,b)=>a.value-b.value||a.id.localeCompare(b.id))[0]}
function strongest(state){return dims.map(([id,label])=>({id,label,value:level(state,id)})).sort((a,b)=>b.value-a.value||a.id.localeCompare(b.id))[0]}
function average(state,keys){const xs=keys.map(k=>level(state,k)).filter(Number.isFinite);return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0}

export const BCG_QUADRANTS=freeze([
 freeze({id:'ster',label:'Ster',description:'Groeiende markt, sterke positie. Investeren zolang het duurt.'}),
 freeze({id:'melkkoe',label:'Melkkoe',description:'Trage markt, sterke positie. Hier haal je het geld voor de rest.'}),
 freeze({id:'vraagteken',label:'Vraagteken',description:'Groeiende markt, achterstand. Kiezen: investeren of loslaten.'}),
 freeze({id:'hond',label:'Hond',description:'Trage markt, achterstand. Niet groeien maar opruimen.'})
]);
export function buildBcgModel(state={}){const growth=branchGrowth(state),own=companyMaturity(state),baseline=branchDigital(state),highGrowth=growth>1.5,strong=own>=baseline,currentQuadrant=highGrowth?(strong?'ster':'vraagteken'):(strong?'melkkoe':'hond'),note=noteFor(state,'bcg'),explanation=`Twee assen: marktgroei en je eigen positie. Je sector groeit met ${nl(growth)}%; jouw niveau is ${nl(own)} tegenover ${nl(baseline)} in de branche.`,conclusion={ster:'Je positie is sterk in een groeiende markt: gericht blijven investeren en bewijs van rendement vasthouden.',melkkoe:'Je positie is sterk in een tragere markt: rendement oogsten en selectief financieren wat daarna komt.',vraagteken:'De markt groeit, maar je positie blijft achter: kies expliciet waar je investeert om een ster te worden en laat de rest los.',hond:'De markt groeit beperkt en je positie blijft achter: stop met vanzelfsprekend doorinvesteren en bewijs eerst strategische waarde.'}[currentQuadrant];return freeze({id:'bcg',title:'BCG-matrix',source:'Boston Consulting Group',signal:currentQuadrant,marketGrowth:growth,companyMaturity:own,branchDigitalMaturity:baseline,growthThreshold:1.5,currentQuadrant,quadrants:BCG_QUADRANTS.map(q=>({...q,current:q.id===currentQuadrant})),explanation,conclusion,evidence:'Canonieke marktgroei + profielvolwassenheid + branche digitale volwassenheid',note,notePath:'portal.strategicModels.bcg.note',prompt:'Wat zijn je diensten, en welk vak past bij elk?'})}
export function buildBcgRoadmapAction(model={}){const q=String(model.currentQuadrant||''),title={ster:'BCG: investeringen in sterke groeipositie prioriteren',melkkoe:'BCG: rendement uit sterke positie benutten',vraagteken:'BCG: investeringskeuze voor groeimarkt expliciet maken',hond:'BCG: stoppen of opruimen zonder bewezen strategische waarde'}[q]||'BCG: strategische vervolgstap vastleggen';return freeze({id:`bcg-${q||'actie'}`,source:'bcg',quadrant:q,title,done:false,progress:0})}
export function mergeBcgRoadmapAction(state={},action={}){const current=Array.isArray(state?.roadmap)?state.roadmap:[],id=String(action?.id||'');if(!id)return state;const nonBcg=current.filter(item=>String(item?.source||'')!=='bcg'),existing=current.find(item=>String(item?.id||'')===id);const roadmap=[...nonBcg,existing||action];return{...state,roadmap}}

function buildToc(state){const w=weakest(state);return modelBase(state,'toc','Theory of Constraints','Eliyahu Goldratt',w?.id||'unknown',`De smalste schakel is ${w?.label||'nog niet vast te stellen'} op niveau ${nl(w?.value||0)}.`,w&&w.value<3?`Verbeter eerst ${w.label.toLowerCase()}; verbeteringen elders lopen hier anders alsnog vast.`:'Er is geen maturity-schakel onder niveau 3; bewaak de relatief smalste schakel.','Legacy DIM-maturity: laagste score bepaalt de constraint',{dimension:w?.id})}
function buildSevenS(state){const hard=average(state,['sturing','tech','governance','analytics']),soft=average(state,['mensen','culture','service','commercie']),delta=hard-soft,signal=delta>.7?'hard-ahead':delta<-.7?'soft-ahead':'balanced';return modelBase(state,'seven-s','7S — hard tegen zacht','McKinsey',signal,`Harde kant ${nl(hard)}, zachte kant ${nl(soft)}.`,signal==='hard-ahead'?'Techniek en inrichting lopen voor op gebruik en gedrag; zet een kwartaal in op adoptie.':signal==='soft-ahead'?'Mensen kunnen meer aan dan de systemen toelaten; hier ligt snelle winst.':'Harde en zachte kant liggen voldoende dicht bij elkaar.','Legacy maturity-combinatie: hard = sturing/tech/governance/analytics; zacht = mensen/culture/service/commercie',{hard,soft})}
function buildValueChain(state){const service=level(state,'service'),signal=service<3?'service-gap':'service-ok';return modelBase(state,'value-chain','Waardeketen','Michael Porter',signal,`De klant merkt de service-schakel direct; die staat op niveau ${nl(service)}.`,service<3?'Breng klantvragen naar één plek met een status.':'De service-schakel is voldoende ingericht; kijk vervolgens naar overdrachten tussen schakels.','Legacy service-maturity is de klantzichtbare ketenschakel',{service})}
function buildFiveForces(state){const growth=branchGrowth(state),largest=n(metrics(state).largestCustomer),tech=level(state,'tech'),signal=growth<1?'low-growth-rivalry':largest>=25?'customer-power':tech<3?'supplier-lock-in':'balanced';return modelBase(state,'five-forces','Vijf krachten','Michael Porter',signal,`Sectorgroei ${nl(growth)}%; grootste klant ${largest?`${nl(largest)}%`:'niet ingevuld'}; systemen niveau ${nl(tech)}.`,growth<1?'Onder 1% groei is groei vooral een verdeelspel: kies waarop je wint in plaats van alleen meer offertes te maken.':largest>=25?'Klantconcentratie geeft afnemers relatief veel macht; verlaag afhankelijkheid of versterk onderscheid.':tech<3?'Losse systemen verhogen overstapkosten en daarmee leveranciersmacht.':'Geen van de legacy hoofdtriggers domineert.','Legacy Vijf-krachten signalen: marktgroei, klantconcentratie, systeemvolwassenheid')}
function buildAnsoff(state){const largest=n(metrics(state).largestCustomer),growth=branchGrowth(state),signal=largest>0&&largest<20&&growth<1.5?'existing-customer-growth':'other-growth-route';return modelBase(state,'ansoff','Ansoff-groeimatrix','Igor Ansoff',signal,`Grootste klant ${largest?`${nl(largest)}%`:'niet ingevuld'}; sectorgroei ${nl(growth)}%.`,signal==='existing-customer-growth'?'In een trage markt met gespreide klanten is meer omzet uit bestaande klanten de goedkoopste legacy-groeiroute.':'De legacy-trigger voor marktpenetratie bij bestaande klanten is niet actief.','Legacy Ansoff-trigger: cGrootste <20% en branchegroei <1,5%')}
function buildDestep(state){const m=market(state),wage=Number(m.wageGrowth??m.loonstijging),economy=Number(m.economicGrowth??m.economieGroei),has=Number.isFinite(wage)&&Number.isFinite(economy),signal=has&&wage>economy+2?'margin-pressure':'evidence-needed';return modelBase(state,'destep','DESTEP','Macro-omgeving',signal,has?`Loonstijging ${nl(wage)}%, economische groei ${nl(economy)}%.`:'Canonieke loon- en economische groeidata ontbreken; er wordt geen DESTEP-cijfer verzonnen.',signal==='margin-pressure'?'Zet productiviteitswinst om in tarief of capaciteit; anders verdampt marge.':'Zonder actuele macro-evidence blijft deze legacy-trigger fail-closed.','Legacy DESTEP-trigger: loonstijging > economische groei + 2 procentpunt',{wageGrowth:Number.isFinite(wage)?wage:null,economicGrowth:Number.isFinite(economy)?economy:null})}
function buildAdkar(state){const culture=level(state,'culture'),open=(portal(state).strategy?.findings||[]).length,signal=culture<3?'change-readiness-gap':'change-ready';return modelBase(state,'adkar','ADKAR','Prosci',signal,`Cultuur/verandervermogen staat op ${nl(culture)}; ${open} strategische bevindingen zijn vastgelegd.`,culture<3?'Beperk verandering: één zichtbare verbetering per kwartaal is sterker dan veel tegelijk.':'De culture-maturity geeft geen legacy ADKAR-waarschuwing.','Legacy ADKAR-trigger: culture <3 bij een bredere verbeteragenda',{culture})}
function buildSwot(state){const s=strongest(state),w=weakest(state),growth=branchGrowth(state),largest=n(metrics(state).largestCustomer),signal=s?.id||'strength';return modelBase(state,'swot','SWOT','Strategische analyse',signal,`Sterkste onderdeel: ${s?.label||'onbekend'} (${nl(s?.value||0)}); zwakste: ${w?.label||'onbekend'} (${nl(w?.value||0)}).`,s?`Bouw je aanbod op ${s.label.toLowerCase()}; wat je aantoonbaar goed doet verkoopt makkelijker dan wat je nog moet leren.`:'Vul maturity-data aan voordat SWOT conclusies trekt.','Legacy SWOT combineert sterkste/zwakste maturity, marktgroei en klantconcentratie',{strength:s?.id,weakness:w?.id,marketGrowth:growth,largestCustomer:largest})}
function buildBalancedScorecard(state){const service=level(state,'service'),commercial=level(state,'commercie'),operation=level(state,'operatie'),people=level(state,'mensen'),signal=service<3||commercial<3?'customer-measure-gap':'balanced';return modelBase(state,'balanced-scorecard','Balanced Scorecard','Kaplan & Norton',signal,`Klant ${nl(service)}, commercie ${nl(commercial)}, proces ${nl(operation)}, leren ${nl(people)}.`,signal==='customer-measure-gap'?'Meet één klantcijfer maandelijks, bijvoorbeeld reactietijd of aanbeveling.':'De vier legacy-perspectieven hebben geen dominante klantwaarschuwing.','Legacy Balanced Scorecard: financieel, klant, proces, leren uit canonical metrics/maturity')}
function buildBlueOcean(state){return modelBase(state,'blue-ocean','Blue Ocean (ERRC)','Kim & Mauborgne','eliminate-reduce',`Het legacy-model gebruikt ERRC als expliciete keuze-oefening, niet als voorspelling.`,'Schrap één ding dat de sector doet en niemand mist; onderscheid ontstaat vaak door weglaten.','Legacy Blue Ocean-actie is een vaste strategische keuzeprompt, zonder verzonnen marktdata')}
function buildThreeHorizons(state){return modelBase(state,'three-horizons','Drie horizonten','McKinsey','portfolio-balance','De legacy-regel verdeelt aandacht tussen nu, straks en later.','Zet minimaal één vast moment per maand apart voor de volgende horizon, zodat vandaag niet alle capaciteit opslokt.','Legacy Three Horizons-actie uit strategie-engine')}
function buildUlrich(state){const people=level(state,'mensen'),signal=people<3?'skills-risk':'skills-covered';return modelBase(state,'ulrich','Ulrich — rol van HR','Dave Ulrich',signal,`Mensen en kennis staat op niveau ${nl(people)}.`,people<3?'Maak een kennismatrix: wie kan welke taak en waar staat maar één naam?':'Geen legacy kennisrisico-trigger onder niveau 3.','Legacy Ulrich-trigger: mensen <3',{people})}
function buildSipoc(state){const operation=level(state,'operatie'),signal=operation<4?'process-documentation-gap':'process-documented';return modelBase(state,'sipoc','SIPOC en Lean','SIPOC',signal,`Operatie staat op niveau ${nl(operation)}.`,operation<4?'Beschrijf de drie hoofdprocessen op één A4: leverancier, input, proces, output, klant.':'De legacy SIPOC-trigger voor procesbeschrijving is niet actief.','Legacy SIPOC-trigger: operatie <4',{operation})}
function buildRaci(state){const employees=n(profile(state).employees??profile(state).mw),signal=employees>=16?'decision-rights':'small-team';return modelBase(state,'raci','RACI en span of control','RACI',signal,`${employees||0} medewerkers; legacy-richtgetal circa ${employees?Math.max(1,Math.round(employees/8)):0} leidinggevenden.`,employees>=16?'Leg vast wie beslist waarover; zonder duidelijke beslissers verschuift besluitvorming naar informele routes.':'De legacy RACI-trigger start vanaf 16 medewerkers.','Legacy RACI-trigger: medewerkers >=16, span-of-control ~8',{employees})}
function buildOcai(state){const culture=level(state,'culture'),signal=culture<3?'culture-gap':'culture-visible';return modelBase(state,'ocai','OCAI — cultuurtypen','Cameron & Quinn',signal,`Organisatie en cultuur staat op niveau ${nl(culture)}.`,culture<3?'Kies één verandering en maak het resultaat zichtbaar; dat werkt beter dan een groot plan bij de legacy familiecultuur-trigger.':'De legacy OCAI-waarschuwing is niet actief.','Legacy OCAI-trigger: culture <3',{culture})}
function buildSalesFunnel(state){const commercial=level(state,'commercie'),conversion=n(metrics(state).quoteConversion),signal=commercial<4?'conversion-gap':'funnel-controlled';return modelBase(state,'sales-funnel','Salestrechter en win/loss','Sales funnel',signal,`Commercie staat op ${nl(commercial)}${conversion?`; offerteconversie ${nl(conversion)}%`:''}.`,commercial<4?'Meet offerteconversie per stap: contact → gesprek → offerte → opdracht.':'De legacy maturity-trigger voor de salestrechter is niet actief.','Legacy salestrechter-trigger: commercie <4; conversiedata indien beschikbaar',{commercial,quoteConversion:conversion||null})}
function buildAarrr(state){const marketing=n(metrics(state).marketing),newCustomers=n(metrics(state).newCustomers),signal=marketing>0&&!newCustomers?'acquisition-measurement-gap':'acquisition-measured';return modelBase(state,'aarrr','AARRR en STP','Pirate Metrics',signal,`Marketing ${marketing||0}; nieuwe klanten ${newCustomers||0}.`,signal==='acquisition-measurement-gap'?'Tel hoeveel nieuwe klanten marketing oplevert; zonder dat getal weet je niet of het budget werkt.':'De legacy acquisition-measurement-trigger is niet actief.','Legacy AARRR-trigger: marketingkosten aanwezig en nieuwe-klantenmeting ontbreekt',{marketing,newCustomers})}
function buildKraljic(state){return modelBase(state,'kraljic','Kraljic en TCO','Peter Kraljic','supplier-segmentation','Het legacy-model segmenteert leveranciers op financieel belang × leveringsrisico.','Zet leveranciers in vier vakken: routine automatiseren, knelpunten borgen, hefboom benutten en strategische relaties gericht beheren.','Legacy Kraljic-actie is een vaste segmentatieprompt; leveranciersdata wordt niet verzonnen')}
function buildPareto(state){const dso=n(metrics(state).dso),signal=dso>30?'receivables-focus':'receivables-normal';return modelBase(state,'pareto-receivables','Pareto op debiteuren','Pareto',signal,`DSO is ${nl(dso,0)} dagen.`,dso>30?'Richt opvolging eerst op de kleine groep klanten die het grootste deel van de achterstand veroorzaakt.':'De legacy Pareto-debiteuren-trigger start boven 30 DSO.','Legacy Pareto-trigger: cDso >30',{dso})}

export const STRATEGIC_MODEL_IDS=freeze(['toc','seven-s','value-chain','five-forces','bcg','ansoff','destep','adkar','swot','balanced-scorecard','blue-ocean','three-horizons','ulrich','sipoc','raci','ocai','sales-funnel','aarrr','kraljic','pareto-receivables']);
const BUILDERS=freeze({toc:buildToc,'seven-s':buildSevenS,'value-chain':buildValueChain,'five-forces':buildFiveForces,bcg:buildBcgModel,ansoff:buildAnsoff,destep:buildDestep,adkar:buildAdkar,swot:buildSwot,'balanced-scorecard':buildBalancedScorecard,'blue-ocean':buildBlueOcean,'three-horizons':buildThreeHorizons,ulrich:buildUlrich,sipoc:buildSipoc,raci:buildRaci,ocai:buildOcai,'sales-funnel':buildSalesFunnel,aarrr:buildAarrr,kraljic:buildKraljic,'pareto-receivables':buildPareto});
export function buildStrategicModels(state={}){return STRATEGIC_MODEL_IDS.map(id=>BUILDERS[id](state))}
function slug(value){return String(value||'actie').toLocaleLowerCase('nl').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)||'actie'}
export function buildStrategicRoadmapAction(model={}){const id=String(model.id||'model'),signal=String(model.signal||model.currentQuadrant||'actie');return freeze({id:`strategy-${id}-${slug(signal)}`,source:id,signal,title:`${model.title||id}: ${model.conclusion||'strategische vervolgstap'}`,done:false,progress:0})}
export function mergeStrategicRoadmapAction(state={},action={}){const id=String(action?.id||'');if(!id)return state;const current=Array.isArray(state?.roadmap)?state.roadmap:[];if(current.some(item=>String(item?.id||'')===id))return state;return{...state,roadmap:[...current,action]}}
