async function saveAssessment(i){
 const r=reviewer(),name=PLAYERS[i-1],playerId=PLAYER_IDS[name],scores=collectScores(i),status=document.getElementById(`ss${i}`),btn=document.getElementById(`save${i}`);
 if(!r){status.textContent="Kies eerst jouw naam op de homepage.";status.className="err";return}
 if(!isCompleteScores(scores)){status.textContent="Vul eerst alle 14 scores in.";status.className="err";return}
 const observation=document.getElementById(`obs${i}`).value||"",assessmentId=`${r.id}__${playerId}__${Date.now()}`,payload={assessmentId,playerId,playerName:name,reviewerId:r.id,reviewerName:r.name,...scores,observation,timestamp:new Date().toISOString()};
 saveDraft(playerId,scores,observation);btn.disabled=true;status.textContent="Opslaan in Notion…";status.className="";
 try{const body=new URLSearchParams();Object.entries(payload).forEach(([k,v])=>body.append(k,String(v)));await fetch(WRITE_URL,{method:"POST",body,mode:"no-cors"});status.textContent="✓ Beoordeling verzonden. Teambeeld wordt ververst…";status.className="ok";setTimeout(()=>refreshTeamData(playerId),1200)}catch(err){status.textContent="Netwerkfout. Je lokale draft is wel bewaard.";status.className="err"}finally{btn.disabled=false}
}
function unwrapTeamPayload(data){let x=data;for(let i=0;i<4;i++){if(typeof x==="string"){try{x=JSON.parse(x);continue}catch(e){break}}if(x&&typeof x.body==="string"){try{x={...x,body:JSON.parse(x.body)}}catch(e){} }break}return x}
async function refreshTeamData(focusPlayerId){const top=document.getElementById("activeReviewerPill");try{const res=await fetch(READ_URL,{method:"GET",cache:"no-store"});if(!res.ok)throw new Error("HTTP "+res.status);let data=unwrapTeamPayload(await res.json());if(data?.body)data=unwrapTeamPayload(data.body);const pages=Array.isArray(data?.results)?data.results:[];centralAssessments=pages.map(notionAssessment).filter(a=>a.playerId&&a.reviewerId);buildTeamViews();lastSync=new Date();top.classList.remove("err");renderPlayerPages();top.textContent=`Beoordelaar: ${reviewer()?.name||"niet gekozen"} · sync ${lastSync.toLocaleTimeString("nl-NL",{hour:"2-digit",minute:"2-digit"})}`;if(focusPlayerId){const idx=PLAYERS.findIndex(n=>PLAYER_IDS[n]===focusPlayerId)+1,s=document.getElementById(`ss${idx}`);if(s){s.textContent="✓ Opgeslagen en Teambeeld bijgewerkt";s.className="ok"}}}catch(err){top.textContent=`Beoordelaar: ${reviewer()?.name||"niet gekozen"} · centrale data niet bereikbaar`;top.classList.add("err")}}
function balanceBonus(metrics,pos){if(pos==="CB"||pos==="FB"||pos==="GK")return (Number(metrics.verdedigen||0)+Number(metrics.nietBalbezit||0))/10*3;if(pos==="CM")return (Number(metrics.spelinzicht||0)+Number(metrics.rust||0))/10*3;if(pos==="WM"||pos==="W")return Number(metrics.snelheid||0)/5*2;if(pos==="ST")return (Number(metrics.aanvallend||0)+Number(metrics.moed||0))/10*3;return 0}
function slotFit(tv,pos){return tv.complete?fitFor(tv.flat,pos):partialFitFor(tv.flat,pos)}
function slotScore(tv,pos){return slotFit(tv,pos)+balanceBonus(tv.flat,pos)-(tv.complete?0:5)}
function optimize(E,slots){let dp=new Map([[0,{score:0,picks:[]}]]);for(let s=0;s<slots.length;s++){const nx=new Map(),pos=slots[s][0];for(const [mask,node] of dp)for(let i=0;i<E.length;i++){const bit=1<<i;if(mask&bit)continue;const v=node.score+slotScore(E[i].tv,pos),nm=mask|bit,old=nx.get(nm);if(!old||v>old.score)nx.set(nm,{score:v,picks:node.picks.concat([{i,fit:slotFit(E[i].tv,pos),slotScore:slotScore(E[i].tv,pos)}])})}dp=nx}return [...dp.values()].sort((a,b)=>b.score-a.score)[0]}
function lineupEligible(tv){return tv?.complete||tv?.provisional}
function renderLineup(){const field=document.getElementById("field"),status=document.getElementById("lineStatus"),bench=document.getElementById("bench");if(!field)return;field.innerHTML="";const E=PLAYERS.map((n,i)=>({name:n,id:PLAYER_IDS[n],tv:teamViews[PLAYER_IDS[n]],idx:i})).filter(x=>lineupEligible(x.tv));if(E.length<11){status.innerHTML=`${E.length}/14 speelsters hebben minimaal 8/14 bruikbare teamkenmerken. Minimaal 11 nodig voor een conceptopstelling.`;bench.innerHTML=PLAYERS.filter(n=>!lineupEligible(teamViews[PLAYER_IDS[n]])).map(n=>`<span class="tag">${n} · nog te weinig teamdata</span>`).join("");return}const slots=FORMATIONS[currentFormation],best=optimize(E,slots),used=new Set();slots.forEach((slot,j)=>{const pick=best.picks[j],p=E[pick.i];used.add(p.id);const d=document.createElement("div");d.className="pl";d.style.left=slot[2]+"%";d.style.top=slot[3]+"%";d.innerHTML=`${p.name}<small>${slot[1]} · fit ${pick.fit}% · ${p.tv.complete?"definitief":"voorlopig"}</small>`;field.appendChild(d)});const avg=Math.round(best.picks.reduce((a,b)=>a+b.fit,0)/11),provisional=best.picks.filter(x=>!E[x.i].tv.complete).length;status.innerHTML=`<b>Concept ${currentFormation[0]}-${currentFormation[1]}-${currentFormation[2]}</b> · gemiddelde positie-fit <b>${avg}%</b> · ${provisional}/11 voorlopig. Definitief zodra alle gebruikte speelsters 14/14 hebben.`;bench.innerHTML=E.filter(x=>!used.has(x.id)).map(x=>`<span class="tag">${x.name} · ${POSITION_LABEL[x.tv.fits[0][0]]} ${x.tv.fits[0][1]}%</span>`).join("")+PLAYERS.filter(n=>!lineupEligible(teamViews[PLAYER_IDS[n]])).map(n=>`<span class="tag">${n} · nog te weinig teamdata</span>`).join("")}
async function syncLineup(){const E=PLAYERS.map(n=>({name:n,id:PLAYER_IDS[n],tv:teamViews[PLAYER_IDS[n]]})).filter(x=>x.tv?.complete),e=document.getElementById("syncLineStatus");if(E.length<11){e.textContent="Opslaan in Notion kan pas met 11 definitieve Teambeelden (14/14)";e.className="err";return}const slots=FORMATIONS[currentFormation],best=optimize(E,slots),arr=slots.map((s,j)=>({position:s[1],player:E[best.picks[j].i].name,fit:best.picks[j].fit,reviewers:E[best.picks[j].i].tv.reviewerCount,confidence:E[best.picks[j].i].tv.confidence})),teamfit=Math.round(best.picks.reduce((a,b)=>a+b.fit,0)/11),assessmentCount=E.reduce((a,x)=>a+x.tv.reviewerCount,0);e.textContent="Synchroniseren…";try{const b=new URLSearchParams({pageId:FORMATION_IDS[currentFormation],name:`Opstelling ${currentFormation[0]}-${currentFormation[1]}-${currentFormation[2]}`,type:"Opstelling",formation:`${currentFormation[0]}-${currentFormation[1]}-${currentFormation[2]}`,lineup:JSON.stringify(arr),teamfit:String(teamfit),assessmentCount:String(assessmentCount),source:"PW MO14-1 Coach Hub v2",timestamp:new Date().toISOString()});await fetch(LINEUP_URL,{method:"POST",body:b,mode:"no-cors"});e.textContent="✓ Opstelling naar Notion verzonden";e.className="ok"}catch(err){e.textContent="Synchronisatie mislukt";e.className="err"}}
function init(){renderReviewerSelector();document.getElementById("activeReviewerPill").textContent="Beoordelaar: "+(reviewer()?.name||"niet gekozen");document.getElementById("reviewerOnPlayers").textContent=reviewer()?.name||"nog niet gekozen";renderPlayerPages();document.querySelectorAll(".fb").forEach(b=>b.onclick=()=>{document.querySelectorAll(".fb").forEach(x=>x.classList.remove("on"));b.classList.add("on");currentFormation=b.dataset.f;renderLineup()});document.getElementById("syncLineBtn").onclick=syncLineup;document.getElementById("refreshTop").onclick=()=>refreshTeamData();refreshTeamData()}
init();
