function propText(p){if(!p)return"";const a=p.rich_text||p.title||p.text;if(Array.isArray(a))return a.map(x=>x.plain_text||x.text?.content||"").join("");return p.select?.name??p.number??p.date?.start??""}
function notionAssessment(page){
 const p=page.properties||{};const scores={techniek:Number(p["Techniek"]?.number||0),spelinzicht:Number(p["Spelinzicht"]?.number||0),verdedigen:Number(p["Verdedigen"]?.number||0),snelheid:Number(p["Snelheid"]?.number||0),loopvermogen:Number(p["Loopvermogen"]?.number||0),rust:Number(p["Rust aan de bal"]?.number||0),aanvallend:Number(p["Aanvallend instinct"]?.number||0),communicatie:Number(p["Communicatie"]?.number||0),balbezit:Number(p["Balbezit"]?.number||0),nietBalbezit:Number(p["Niet-balbezit"]?.number||0),omschakeling:Number(p["Omschakeling"]?.number||0),moed:Number(p["Moed"]?.number||0),winnendeKracht:Number(p["Winnende kracht"]?.number||0),teamgedrag:Number(p["Teamgedrag"]?.number||0)};
 return {id:propText(p["Assessment ID"])||page.id,reviewerId:propText(p["Reviewer ID"]),reviewerName:propText(p["Reviewer naam"]),playerId:propText(p["Player ID"]),scores,observation:propText(p["Observatie"]),timestamp:p["Moment"]?.date?.start||page.last_edited_time||page.created_time};
}
function latestPerReviewerPlayer(items){const map=new Map();items.forEach(a=>{if(!a.reviewerId||!a.playerId)return;const k=`${a.reviewerId}__${a.playerId}`,old=map.get(k);if(!old||String(a.timestamp)>String(old.timestamp))map.set(k,a)});return [...map.values()]}
function aggregateMetric(vals){if(!vals.length)return null;const avg=vals.reduce((a,b)=>a+b,0)/vals.length,min=Math.min(...vals),max=Math.max(...vals);return{avg,min,max,conflict:max-min>=2}}
function aggregatePlayerAssessments(items){const latest=latestPerReviewerPlayer(items),result={metrics:{},reviewerCount:new Set(latest.map(x=>x.reviewerId)).size,conflicts:0};METRICS.forEach(m=>{const vals=latest.map(x=>Number(x.scores[m.id])).filter(v=>v>=1&&v<=5);const a=aggregateMetric(vals);if(a?.conflict)result.conflicts++;result.metrics[m.id]=a});let c=result.reviewerCount>=3?"hoog":result.reviewerCount===2?"middel":"laag";if(result.conflicts>=3)c=c==="hoog"?"middel":"laag";result.confidence=c;const flat={};METRICS.forEach(m=>flat[m.id]=result.metrics[m.id]?.avg||0);result.flat=flat;result.complete=METRICS.every(m=>result.metrics[m.id]?.avg>0);if(result.complete)result.fits=positionFits(flat);return result}
function buildTeamViews(){teamViews={};PLAYERS.forEach(n=>{const pid=PLAYER_IDS[n],items=centralAssessments.filter(a=>a.playerId===pid);if(items.length)teamViews[pid]=aggregatePlayerAssessments(items)})}
function renderAllTeamViews(){PLAYERS.forEach((n,i)=>renderTeamView(i+1,n));renderLineup()}
function renderTeamView(i,name){const e=document.getElementById(`tv${i}`);if(!e)return;const tv=teamViews[PLAYER_IDS[name]];if(!tv){e.innerHTML="Nog geen centrale beoordeling voor deze speelster.";return}const badge=tv.confidence==="hoog"?"high":tv.confidence==="middel"?"medium":"low";const metrics=METRICS.map(m=>{const a=tv.metrics[m.id];return a?`<div class="metric"><b>${m.label}</b><span>${a.avg.toFixed(1)} / 5</span><span class="${a.conflict?"conflict":""}">${a.conflict?"BESPREEK":""}</span></div>`:""}).join("");let pos="";if(tv.complete){const f=tv.fits,best=f[0][0],s=strongestContributors(tv.flat,best).map(x=>x.label).join(", "),g=developmentGaps(tv.flat,best).map(x=>x.label).join(", ");pos=`<div class="fit"><b>Gezamenlijk positieadvies:</b> ${POSITION_LABEL[best]} ${f[0][1]}% · 2e ${POSITION_LABEL[f[1][0]]} ${f[1][1]}% · 3e ${POSITION_LABEL[f[2][0]]} ${f[2][1]}%<div class="why"><b>Past door:</b> ${s}. <b>Ontwikkelen:</b> ${g}.</div></div>`}e.innerHTML=`<div class="box"><b>${tv.reviewerCount} beoordelaar(s)</b> · confidence <span class="confidence ${badge}">${tv.confidence}</span> · ${tv.conflicts} verschilpunt(en)</div><div class="tvgrid">${metrics}</div>${pos}`}
