const CSS=`
.os-executive{margin:0 0 24px;padding:24px;border:1px solid rgba(15,23,42,.12);border-radius:20px;background:linear-gradient(180deg,#fff,#f8fafc);box-shadow:0 18px 45px rgba(15,23,42,.06)}
.os-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:18px}.os-head h2{margin:3px 0 0;font-size:clamp(24px,4vw,38px);line-height:1.05}.os-head>span{font-size:12px;padding:7px 10px;border:1px solid rgba(15,23,42,.12);border-radius:999px}.os-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:0 0 16px}.os-metrics article,.os-card,.os-health,.os-page-card,.os-page-empty{border:1px solid rgba(15,23,42,.1);border-radius:14px;background:#fff;padding:16px}.os-metrics small,.os-card small,.os-list small,.os-graph-list small{display:block;opacity:.7}.os-metrics b{display:block;margin-top:5px;font-size:25px}.os-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.os-card h3,.os-health h3,.os-page-card h3{margin:0 0 10px}.os-card ol{margin:0;padding-left:20px}.os-card li{padding:7px 0}.os-evidence{margin-top:4px}.os-health{margin-top:12px}.os-health p,.os-muted,.os-empty,.os-page-empty p{margin:0;opacity:.72}.os-module-tabs,.os-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.os-module-tabs button,.os-actions button,.os-graph-list button{appearance:none;border:1px solid rgba(15,23,42,.16);background:#fff;border-radius:10px;padding:10px 12px;font:inherit;cursor:pointer;text-align:left}.os-module-tabs button[aria-pressed="true"]{font-weight:700;border-color:currentColor}.os-module-detail{margin-top:12px}.os-page-card+.os-page-card{margin-top:12px}.os-list{display:grid;gap:10px}.os-list article{border-top:1px solid rgba(15,23,42,.08);padding-top:10px}.os-list article:first-child{border-top:0;padding-top:0}.os-impact-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.os-impact-grid article{padding:12px;border:1px solid rgba(15,23,42,.08);border-radius:12px}.os-impact-grid b{display:block;font-size:20px;margin:6px 0}.os-scenario-result pre{white-space:pre-wrap;overflow:auto;padding:12px;border-radius:10px;background:rgba(15,23,42,.05)}.os-graph-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.os-graph-list button{display:flex;flex-direction:column;gap:3px}.os-module-tabs button:focus-visible,.os-actions button:focus-visible,.os-graph-list button:focus-visible{outline:3px solid currentColor;outline-offset:2px}
@media(max-width:900px){.os-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.os-impact-grid{grid-template-columns:1fr 1fr}}
@media(max-width:640px){.os-executive{padding:16px;border-radius:14px}.os-head{display:block}.os-head>span{display:inline-block;margin-top:10px}.os-metrics,.os-grid,.os-impact-grid,.os-graph-list{grid-template-columns:1fr}.os-module-tabs button{flex:1 1 46%}}
`;

export function ensureOperatingSystemStyles(doc=document){
 if(!doc?.head||doc.getElementById('bg-os-styles'))return;
 const style=doc.createElement('style');style.id='bg-os-styles';style.textContent=CSS;doc.head.appendChild(style);
}
