import { createClient } from 'npm:@supabase/supabase-js@2';
const CHANNELS=['email_newsletter','linkedin_personal','linkedin_company','linkedin_article_personal','linkedin_article_company','instagram_company','blog'];
const EXECUTABLE=new Set(['linkedin_personal','linkedin_company','blog']);
const PERSONAL_CONTRACT='arthur-personal-linkedin-identity-v4';
const PERSONAL_GATE='channel-identity-hard-gate-v3';
const PERSONAL_CHANNEL='6a70381699afb44349f0fb35';
const VERSION='v8';
const json=(b,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{'content-type':'application/json','cache-control':'no-store'}});
const clean=v=>String(v??'').trim();
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Amsterdam',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
async function digest(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function callAI(key,model,system,user,tool,max_tokens=3000){const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'x-api-key':key,'anthropic-version':'2023-06-01','content-type':'application/json'},body:JSON.stringify({model,max_tokens,system,messages:[{role:'user',content:JSON.stringify(user)}],tools:[tool],tool_choice:{type:'tool',name:tool.name}})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`AI_${r.status}:${clean(b?.error?.message).slice(0,220)}`);const t=(b.content||[]).find(x=>x.type==='tool_use'&&x.name===tool.name);if(!t?.input)throw new Error('AI_TOOL_OUTPUT_MISSING');return t.input;}
function validPersonalSource(r){const e=r?.evidence||{};const lineage=Array.isArray(e.source_lineage)?e.source_lineage.length>0:!!e.source_lineage;return r?.target_channel==='linkedin_personal'&&e.identity_contract===PERSONAL_CONTRACT&&e.identity_gate_version===PERSONAL_GATE&&clean(e.content_id)&&lineage&&e.arthur_anchor_verified===true&&e.first_person_claims_verified===true&&e.personal_life_topic===true&&e.business_topic===false&&e.corporate_voice===false&&e.company_page_interchangeable===false&&e.forced_business_moral===false&&(e.sensitive_private_detail!==true||e.sensitive_private_approval===true);}
function commercialValue(r){return num(r?.evidence?.commercial_value);}
function relevance(r,channel){const topic=clean(r?.topic_key).toLowerCase();const target=clean(r?.target_channel).toLowerCase();let score=num(r?.priority)+commercialValue(r)/10;if(channel==='blog'){if(topic==='blog')score+=60;if(target==='blog')score+=80;if(r?.evidence?.experiment_recipe?.blog)score+=25;}if(channel==='linkedin_company'){if(topic.includes('linkedin'))score+=60;if(target.includes('linkedin')||target.includes('company'))score+=80;if(r?.evidence?.experiment_recipe?.company)score+=25;}return score;}
function pickFallbackRecommendation(recs,channel){return [...(recs||[])].filter(r=>clean(r?.status)==='suggested'||!clean(r?.status)).sort((a,b)=>relevance(b,channel)-relevance(a,channel))[0]||null;}
function fallbackDecision(channel,recs,personalSource){
 if(channel==='linkedin_personal')return {channel,decision:'hold',priority:0,confidence:0,topic_key:'',rationale:'FAIL_CLOSED v4: geen canonieke, volledig geverifieerde Arthur-persoonlijke bron/evidence-lineage beschikbaar; geen zakelijke fallback toegestaan.',scheduled_hour_local:11,content_brief:'',forecast_id:'',prediction_mode:'none',prediction_rationale:'Geen geldige persoonlijke bron.',plan_repaired:true,decision_source:'identity-gate-hold',fallback_recommendation_id:null};
 if(channel==='blog'||channel==='linkedin_company'){
  const rec=pickFallbackRecommendation(recs,channel);
  if(rec){const confidence=Math.max(.55,Math.min(.85,num(rec.priority)/100));return {channel,decision:'publish',priority:Math.min(100,num(rec.priority)),confidence,topic_key:clean(rec.topic_key),rationale:`Deterministische recovery na ongeldige AI-planning; bestaande aanbeveling ${rec.recommendation_id} geselecteerd. Hard gates blijven leidend.`,scheduled_hour_local:channel==='blog'?12:13,content_brief:`${clean(rec.reason)}\nGebruik alleen bewijs uit recommendation ${rec.recommendation_id}; creative policy/recipe: ${JSON.stringify(channel==='blog'?rec?.evidence?.experiment_recipe?.blog:rec?.evidence?.experiment_recipe?.company||{})}`,forecast_id:'',prediction_mode:'none',prediction_rationale:'Recovery is evidence-bound aan bestaande recommendation, niet aan een forecast.',plan_repaired:true,decision_source:'deterministic-recommendation-fallback',fallback_recommendation_id:rec.recommendation_id};}
 }
 return {channel,decision:'hold',priority:0,confidence:0,topic_key:'',rationale:'FAIL_CLOSED: geen ondersteunde executor of geen voldoende recommendation voor deterministische recovery.',scheduled_hour_local:9,content_brief:'',forecast_id:'',prediction_mode:'none',prediction_rationale:'Geen veilige uitvoerbare recovery.',plan_repaired:true,decision_source:'capability-hold',fallback_recommendation_id:null};
}
function normalizePlan(rawDecisions,predictiveById,recs,personalSource){
 const source=Array.isArray(rawDecisions)?rawDecisions:[];const byChannel=new Map();const invalid=[];
 for(const item of source){const channel=clean(item?.channel);if(!CHANNELS.includes(channel)){invalid.push(`unknown:${channel||'missing'}`);continue;}if(byChannel.has(channel)){invalid.push(`duplicate:${channel}`);continue;}byChannel.set(channel,item);}
 const normalized=CHANNELS.map(channel=>{const item=byChannel.get(channel);if(!item)return fallbackDecision(channel,recs,personalSource);const forecastId=clean(item.forecast_id);if(forecastId&&!predictiveById.has(forecastId)){const d=fallbackDecision(channel,recs,personalSource);return {...d,rationale:`FAIL_CLOSED: onbekende forecast_id ${forecastId}; ${d.rationale}`,decision_source:`forecast-repair:${d.decision_source}`};}let decision=['publish','skip','hold'].includes(item.decision)?item.decision:'hold';if(decision==='publish'&&!EXECUTABLE.has(channel))decision='hold';if(channel==='linkedin_personal'&&decision==='publish'&&!personalSource)return fallbackDecision(channel,recs,personalSource);return {...item,channel,decision,priority:num(item.priority),confidence:num(item.confidence),topic_key:clean(item.topic_key),rationale:clean(item.rationale)||'AI-besluit zonder rationale; fail-closed behouden.',scheduled_hour_local:Math.min(18,Math.max(9,num(item.scheduled_hour_local)||9)),content_brief:clean(item.content_brief),forecast_id:forecastId,prediction_mode:['none','reactive','anticipatory','category_creation'].includes(item.prediction_mode)?item.prediction_mode:'none',prediction_rationale:clean(item.prediction_rationale),plan_repaired:false,decision_source:'ai-plan',fallback_recommendation_id:null};});
 return {decisions:normalized,repaired:invalid.length>0||normalized.some(x=>x.plan_repaired),invalid,raw_count:source.length};
}
Deno.serve(async req=>{
 if(req.method!=='POST')return json({ok:false,error:'POST_ONLY'},405);
 const url=Deno.env.get('SUPABASE_URL')||'',service=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!service)return json({ok:false,error:'CONFIG'},500);const db=createClient(url,service,{auth:{persistSession:false,autoRefreshToken:false}});const expected=clean((await db.rpc('bg_geheim',{p_naam:'powerhouse_daily_scheduler_token'})).data);if(!expected||req.headers.get('x-powerhouse-token')!==expected)return json({ok:false,error:'UNAUTHORIZED'},401);let body={};try{body=await req.json()}catch{}const runDate=clean(body.runDate)||localDate();let stage='load-context';
 try{
  const [{data:run},{data:recs},{data:rules},{data:perf},{data:gov},{data:existing},{data:predictive}]=await Promise.all([
   db.from('powerhouse_daily_runs').select('*').eq('run_date',runDate).maybeSingle(),
   db.from('powerhouse_content_recommendations').select('recommendation_id,topic_key,target_channel,recommendation_type,priority,reason,evidence,status').eq('run_date',runDate).order('priority',{ascending:false}).limit(30),
   db.from('bg_schrijfregels').select('regel_id,onderwerp,regel,vertrouwen,status').eq('status','actief').order('vertrouwen',{ascending:false}).limit(30),
   db.from('bg_post_prestatie').select('*').order('bijgewerkt_op',{ascending:false}).limit(30),
   db.from('brain_ai_governance_registry').select('model_id,provider,approved,lifecycle_status').eq('tenant_id','canonical').eq('use_case_id','supabase-bg-native-content-generate-v4').maybeSingle(),
   db.from('powerhouse_channel_decisions').select('channel,decision,state,priority,topic_key,delivery_ref,delivery_evidence').eq('run_date',runDate),
   db.from('powerhouse_first_mover_queue').select('*').order('action_score',{ascending:false}).limit(12)
  ]);
  stage='validate-context';if(!run)throw new Error('DAILY_RUN_MISSING');if(!gov||gov.approved!==true||gov.lifecycle_status!=='ACTIVE'||gov.provider!=='Anthropic')throw new Error('AI_GOVERNANCE_UNAVAILABLE');const apiKey=clean((await db.rpc('bg_geheim',{p_naam:'ANTHROPIC_API_KEY'})).data);if(!apiKey)throw new Error('AI_KEY_UNAVAILABLE');const predictiveById=new Map((predictive||[]).map(p=>[p.forecast_id,p]));const personalSources=(recs||[]).filter(validPersonalSource);const personalSource=personalSources[0]||null;const repairable=(existing||[]).length<7||((existing||[]).length===7&&(existing||[]).every(r=>r.decision==='hold'&&r.state==='decided'&&!r.delivery_ref&&r.delivery_evidence?.plan_repaired===true));
  if(repairable){
   stage='plan-ai';const decisionTool={name:'daily_plan',description:'Exact zeven evidence-led kanaalbesluiten',input_schema:{type:'object',additionalProperties:false,properties:{decisions:{type:'array',minItems:7,maxItems:7,items:{type:'object',additionalProperties:false,properties:{channel:{type:'string',enum:CHANNELS},decision:{type:'string',enum:['publish','skip','hold']},priority:{type:'number',minimum:0,maximum:100},confidence:{type:'number',minimum:0,maximum:1},topic_key:{type:'string'},rationale:{type:'string'},scheduled_hour_local:{type:'integer',minimum:9,maximum:18},content_brief:{type:'string'},forecast_id:{type:'string'},prediction_mode:{type:'string',enum:['none','reactive','anticipatory','category_creation']},prediction_rationale:{type:'string'}},required:['channel','decision','priority','confidence','topic_key','rationale','scheduled_hour_local','content_brief','forecast_id','prediction_mode','prediction_rationale']}}},required:['decisions']}};
   let aiPlan={decisions:[]};try{aiPlan=await callAI(apiKey,gov.model_id,'Je bent het canonieke Brein/Powerhouse. Beslis voor exact zeven kanalen evidence-led PUBLISH, SKIP of HOLD. PERSONAL LINKEDIN IS HARD FAIL-CLOSED: Arthur persoonlijk is persoonlijk. Business, Bedrijfsgeheugen, consultancy, AI/data/digitalisering, generieke directeur/eigenaar-problemen, propositionele content en corporate thought leadership zijn autonoom NIET toegestaan. Kies linkedin_personal alleen PUBLISH als verified_personal_source exact v4-geldig is. LinkedIn bedrijf en blog zijn zakelijke kanalen. Verzin geen feiten of ervaringen. Unsupported kanalen HOLD/SKIP.',{run_date:runDate,daily_run:run,recommendations:recs||[],verified_personal_source:personalSource,predictive_candidates:predictive||[],recent_performance:perf||[],active_rules:rules||[],revenue_goal:{target_eur:1000000,deadline:'2027-09-14'},executor_capabilities:{linkedin_personal:!!personalSource,linkedin_company:true,blog:true,email_newsletter:false,linkedin_article_personal:false,linkedin_article_company:false,instagram_company:false}},decisionTool,3800);}catch(aiError){aiPlan={decisions:[]};console.error('ORCHESTRATOR_PLAN_AI_RECOVERY',String(aiError?.message||aiError));}
   stage='normalize-plan';const plan=normalizePlan(aiPlan?.decisions,predictiveById,recs||[],personalSource);
   stage='write-decisions';for(const d of plan.decisions){const hh=String(d.scheduled_hour_local).padStart(2,'0');const pf=d.forecast_id?predictiveById.get(d.forecast_id):null;const {error}=await db.from('powerhouse_channel_decisions').upsert({run_date:runDate,channel:d.channel,decision:d.decision,state:d.decision==='skip'?'skipped':'decided',priority:d.priority,confidence:d.confidence,topic_key:d.topic_key,rationale:d.rationale,scheduled_for:`${runDate}T${hh}:00:00+02:00`,delivery_evidence:{content_brief:d.content_brief,decision_engine:'powerhouse-content-orchestrator-v8',decision_source:d.decision_source,plan_raw_count:plan.raw_count,forecast_id:d.forecast_id||null,prediction_mode:d.prediction_mode,prediction_rationale:d.prediction_rationale,forecast_action_score:pf?.action_score??null,forecast_probability:pf?.probability??null,forecast_confidence:pf?.confidence??null,plan_repaired:plan.repaired,plan_invalid_entries:plan.invalid,fallback_recommendation_id:d.fallback_recommendation_id||null,personal_identity_contract:d.channel==='linkedin_personal'?PERSONAL_CONTRACT:null,personal_source_recommendation_id:d.channel==='linkedin_personal'?personalSource?.recommendation_id||null:null,personal_fail_closed:d.channel==='linkedin_personal'&&!personalSource},source_recommendation_ids:(recs||[]).map(x=>x.recommendation_id),updated_at:new Date().toISOString()});if(error)throw new Error(`DECISION_WRITE:${error.message}`);}
  }
  stage='select-pending';const {data:pending,error:pendingError}=await db.from('powerhouse_channel_decisions').select('*').eq('run_date',runDate).eq('decision','publish').eq('state','decided').order('priority',{ascending:false}).limit(1).maybeSingle();if(pendingError)throw new Error(`PENDING_READ:${pendingError.message}`);if(!pending)return json({ok:true,runDate,decision_count:7,generated:false,reason:'NO_PENDING_ARTIFACT',personal_source_ready:!!personalSource,predictive_candidates:(predictive||[]).length});
  if(pending.channel==='linkedin_personal'&&!personalSource){const {error}=await db.from('powerhouse_channel_decisions').update({decision:'hold',state:'decided',rationale:'FAIL_CLOSED v4: persoonlijke bron/evidence-lineage ontbreekt; geen zakelijke fallback.',delivery_evidence:{...(pending.delivery_evidence||{}),personal_fail_closed:true,identity_contract:PERSONAL_CONTRACT,identity_gate_version:PERSONAL_GATE},updated_at:new Date().toISOString()}).eq('run_date',runDate).eq('channel','linkedin_personal');if(error)throw new Error(`PERSONAL_HOLD_WRITE:${error.message}`);return json({ok:true,runDate,generated:false,channel:'linkedin_personal',reason:'PERSONAL_IDENTITY_SOURCE_MISSING_HOLD'});}
  stage='artifact-ai';const selectedForecast=pending.delivery_evidence?.forecast_id?predictiveById.get(pending.delivery_evidence.forecast_id):null;const artifactTool={name:'content_artifact',description:'Definitieve kanaaleigen content',input_schema:{type:'object',additionalProperties:false,properties:{title:{type:'string'},body:{type:'string'},cta:{type:'string'},artifact_type:{type:'string',enum:['linkedin_post','blog']},hook_type:{type:'string'},focus_keyword:{type:'string'},meta_description:{type:'string'}},required:['title','body','cta','artifact_type','hook_type','focus_keyword','meta_description']}};const lengths={linkedin_personal:'80-300 woorden',linkedin_company:'100-300 woorden',blog:'900-1600 woorden'};const brief=clean(pending.delivery_evidence?.content_brief)||clean(pending.rationale);const personalInstruction=pending.channel==='linkedin_personal'?'Arthur persoonlijk: gebruik UITSLUITEND verified_personal_source. Geen business/Bedrijfsgeheugen/consultancy/AI-data/digitalisering, geen managementles, geen verkoopdoel, geen verplichte CTA en geen verzonnen eerste-persoonsfeit.':'LinkedIn bedrijf: merk/expertise/probleemgericht. Blog: inhoudelijk, SEO en commercieel relevant zonder opgeblazen claims.';
  const artifact=await callAI(apiKey,gov.model_id,`Schrijf definitieve kanaaleigen content. Verzin geen cases, cijfers, quotes of persoonlijke ervaringen. ${personalInstruction}`,{channel:pending.channel,length:lengths[pending.channel],brief,rationale:pending.rationale,recommendations:pending.channel==='linkedin_personal'?[personalSource]:recs||[],verified_personal_source:pending.channel==='linkedin_personal'?personalSource:null,forecast_context:selectedForecast||null,active_rules:rules||[]},artifactTool,pending.channel==='blog'?4500:2400);
  stage='write-artifact';const contentKey=`${runDate}:${pending.channel}`;const hash=await digest(clean(artifact.body));let identityEvidence=null;if(pending.channel==='linkedin_personal'){const e=personalSource.evidence||{};identityEvidence={content_id:clean(e.content_id)||contentKey,calendar_date:runDate,channel_id:PERSONAL_CHANNEL,channel_kind:'linkedin_personal',identity_contract:PERSONAL_CONTRACT,identity_gate_version:PERSONAL_GATE,source_lineage:e.source_lineage,arthur_anchor_verified:true,first_person_claims_verified:true,personal_life_topic:true,business_topic:false,corporate_voice:false,company_page_interchangeable:false,forced_business_moral:false,sensitive_private_detail:e.sensitive_private_detail===true,sensitive_private_approval:e.sensitive_private_approval===true,prediction_lineage_present:true,prior_prediction_decision_id:`decision:${runDate}:linkedin_personal`,publication_intent:'publish',final_text_hash:hash};}
  const {error:artifactError}=await db.from('powerhouse_content_artifacts').upsert({run_date:runDate,channel:pending.channel,artifact_type:artifact.artifact_type,title:artifact.title,body:artifact.body,cta:artifact.cta,content_brief:brief,generation_evidence:{model:gov.model_id,orchestrator:'powerhouse-content-orchestrator-v8',hook_type:artifact.hook_type,focus_keyword:artifact.focus_keyword,meta_description:artifact.meta_description,recommendation_ids:(recs||[]).map(x=>x.recommendation_id),fallback_recommendation_id:pending.delivery_evidence?.fallback_recommendation_id||null,forecast_id:selectedForecast?.forecast_id||null,prediction_mode:selectedForecast?.prediction_mode||'none',identity_gate_evidence:identityEvidence},status:'content_ready',updated_at:new Date().toISOString()});if(artifactError)throw new Error(`ARTIFACT_WRITE:${artifactError.message}`);
  const {error:decisionError}=await db.from('powerhouse_channel_decisions').update({state:'content_ready',delivery_evidence:{...(pending.delivery_evidence||{}),identity_gate_evidence:identityEvidence},updated_at:new Date().toISOString()}).eq('run_date',runDate).eq('channel',pending.channel).eq('state','decided');if(decisionError)throw new Error(`DECISION_STATE_WRITE:${decisionError.message}`);return json({ok:true,runDate,decision_count:7,generated:true,channel:pending.channel,title:artifact.title,decision_source:pending.delivery_evidence?.decision_source||'ai-plan',fallback_recommendation_id:pending.delivery_evidence?.fallback_recommendation_id||null,personal_identity_evidence_bound:!!identityEvidence});
 }catch(e){const message=String(e?.message||e).slice(0,500);try{const {error:healthError}=await db.from('bg_gezondheid').insert({gemeten_op:new Date().toISOString(),onderdeel:'powerhouse-content-orchestrator',soort:'edge-function',status:'fout',detail:`${stage}:${message}`.slice(0,400),gegevens:{runDate,version:VERSION,contract:PERSONAL_CONTRACT,stage}});if(healthError)console.error('ORCHESTRATOR_HEALTH_WRITE_FAILED',healthError.message);}catch(writeError){console.error('ORCHESTRATOR_HEALTH_WRITE_THROW',String(writeError?.message||writeError));}console.error('ORCHESTRATOR_ERROR',stage,message);return json({ok:false,error:message,stage,runDate},500);}
});