import { normalizePortalFlowState } from './portal-flow-state.js';
import { renderPortalFlow, renderStatusClass } from './portal-flow-renderer.js';
import { mapRuntimeSnapshotToPortalFlow } from './portal-powerhouse-adapter.js';

export function reducePortalSelection(state, action) {
  const current = { source: state?.source ?? null, module: state?.module ?? null };
  if (action?.type === 'SELECT_SOURCE') return { ...current, source: current.source === action.id ? null : action.id };
  if (action?.type === 'SELECT_MODULE') return { ...current, module: current.module === action.id ? null : action.id };
  if (action?.type === 'CLEAR') return { source:null, module:null };
  return current;
}
export function getPortalCustomerSlug(search = window.location.search) { return new URLSearchParams(search).get('klant') || null; }
export function withCustomer(path, klant = getPortalCustomerSlug()) { const url = new URL(path, window.location.origin); if (klant) url.searchParams.set('klant', klant); return url.pathname + url.search + url.hash; }

const SOURCE_COPY={systemen:['Systemen','ERP, CRM, finance, e-mail en HR leveren operationele data aan.'],documenten:['Documenten','Contracten, notities, rapporten en beleid leveren ongestructureerde kennis aan.'],processen:['Processen','Werkstromen, procedures en taken laten zien hoe werk werkelijk loopt.'],mensen:['Mensen','Expertise, verantwoordelijkheid en impliciete kennis worden zichtbaar.'],dashboards:['Dashboards','KPI’s en rapportages geven het cijfermatige beeld van de organisatie.'],extern:['Externe data','Markt, concurrentie en regelgeving voegen actuele context van buiten toe.'],modellen:['Modellen','Rekenmodellen en scenario’s laten mogelijke impact van keuzes zien.'],canvassen:['Canvassen','Strategie en plannen geven richting en maken gewenste verandering expliciet.']};
const MODULE_COPY={inzicht:['Inzicht','Managementsamenvatting, signalen en stand van zaken.'],vergelijken:['Vergelijken','Opties, verschillen en afwegingen naast elkaar.'],denken:['Denken','Redeneren, verklaren en advies.'],overname:['Overname','Due diligence, kansen en risico’s.'],doen:['Doen','Acties, eigenaarschap en opvolging.'],dna:['Strategy DNA','Richting, keuzes en strategische fit.'],canvas:['Execution Canvas','Afhankelijkheden en uitvoering.'],roadmap:['Roadmap','Volgorde, planning en milestones.'],documenten:['Documenten','Vastgelegde kennis en context.'],notities:['Notities','Observaties en besluiten.'],activiteit:['Activiteit','Wie deed wat en wanneer.'],wijzigingen:['Wijzigingen','Nieuwe signalen en mutaties.'],koppelingen:['Koppelingen','Status van bronnen en synchronisaties.'],taken:['Taken & werkstromen','Van inzicht naar toegewezen uitvoering.'],uren:['Uren & facturen','Tijd, administratie en opbrengst.'],actueel:['Actueel houden','Feedback, actualisatie en leren.']};

let selection={source:null,module:null}; let runtimeState=normalizePortalFlowState({}); let demoMode=false;
function buildPreviewState(){ if(!demoMode) return normalizePortalFlowState({}); return mapRuntimeSnapshotToPortalFlow({source:{id:selection.source??'documenten',status:'running',lastSync:'zojuist',quality:'preview'},datahub:{status:'verified'},brain:{status:'running',capabilities:['begrijpt-context','legt-verbanden','vat-samen','prioriteert','adviseert']},agents:[{id:'monitor',name:'Detectie',category:'detectie',status:'completed',evidence:['preview-evidence-monitor']},{id:'analyse',name:'Analyse',category:'analyse',status:'running',evidence:[]},{id:'execute',name:'Uitvoering',category:'uitvoering',status:'waiting',evidence:[]},{id:'verify',name:'Verificatie',category:'verificatie',status:'waiting',evidence:[]},{id:'heal',name:'Self-heal',category:'self-heal',status:'idle',evidence:[]},{id:'learning',name:'Learning/writeback',category:'learning',status:'waiting',evidence:[],learningPending:true}],module:selection.module?{id:selection.module,status:'running'}:{id:'inzicht',status:'running'},action:{status:'queued',label:'Bekijk en beoordeel de nieuwe inzichten'},outcome:{status:'waiting',evidenceId:null},learning:{status:'waiting'},updatedAt:new Date().toISOString()}); }
function statusText(status){return({idle:'Idle',queued:'In wachtrij',running:'Actief',waiting:'Wacht',blocked:'Geblokkeerd',failed:'Fout',recovering:'Herstelt',verified:'Geverifieerd',completed:'Afgerond',disconnected:'Niet gekoppeld'})[status]??status}
function applyNodeStatus(el,status){if(!el)return;el.classList.remove('is-idle','is-queued','is-running','is-waiting','is-blocked','is-failed','is-recovering','is-verified','is-completed','is-disconnected');el.classList.add(renderStatusClass(status))}
function renderSelections(state){const sourceList=document.querySelector('[data-source-selector]'),moduleGrid=document.querySelector('[data-module-selector]');sourceList?.classList.toggle('has-selection',!!selection.source);moduleGrid?.classList.toggle('has-selection',!!selection.module);document.querySelectorAll('[data-source-id]').forEach(el=>el.classList.toggle('is-selected',el.dataset.sourceId===selection.source));document.querySelectorAll('[data-module-id]').forEach(el=>el.classList.toggle('is-selected',el.dataset.moduleId===selection.module));if(state.source)applyNodeStatus(document.querySelector(`[data-source-id="${state.source.id}"]`),state.source.status);applyNodeStatus(document.querySelector('[data-flow-node="datahub"]'),state.datahub.status);applyNodeStatus(document.querySelector('[data-flow-node="brain"]'),state.brain.status);if(state.module)applyNodeStatus(document.querySelector(`[data-module-id="${state.module.id}"]`),state.module.status)}
function renderCapabilities(state){document.querySelectorAll('[data-capability]').forEach(el=>el.classList.toggle('is-active',state.brain.capabilities.includes(el.dataset.capability)))}
function renderAgents(state){const slots=[...document.querySelectorAll('#agentList .agent')],mapped=new Map(state.powerhouse.map(a=>[a.category,a])),categories=['detectie','analyse','uitvoering','verificatie','self-heal','learning'];slots.forEach((slot,index)=>{const agent=mapped.get(categories[index]);const status=agent?.status??'idle';applyNodeStatus(slot,status);slot.querySelector('small').textContent=statusText(status);slot.title=agent?[agent.triggerReason,agent.error,agent.recoveryObligation?.reason].filter(Boolean).join(' · '):'Geen runtime-status beschikbaar'})}
function renderStage(state){document.getElementById('stageSource').textContent=state.source?`${SOURCE_COPY[state.source.id]?.[0]??state.source.id}: ${statusText(state.source.status)}`:'Geen actieve bron';document.getElementById('stageHub').textContent=statusText(state.datahub.status);document.getElementById('stageBrain').textContent=statusText(state.brain.status);const activeAgents=state.powerhouse.filter(a=>a.status!=='idle');document.getElementById('stagePowerhouse').textContent=activeAgents.length?`${activeAgents.length} agent(s) · ${statusText(activeAgents[0].status)}`:'Geen agent actief';document.getElementById('stageModule').textContent=state.module?`${MODULE_COPY[state.module.id]?.[0]??state.module.id}: ${statusText(state.module.status)}`:'Geen outputmodule';document.getElementById('stageOutcome').textContent=state.outcome?.evidenceId?'Evidence aanwezig':'Geen evidence';document.querySelectorAll('.stage-strip>div').forEach(el=>el.classList.remove('is-active'));if(state.source)document.querySelector('[data-stage="source"]')?.classList.add('is-active');if(state.datahub.status!=='idle')document.querySelector('[data-stage="datahub"]')?.classList.add('is-active');if(state.brain.status!=='idle')document.querySelector('[data-stage="brain"]')?.classList.add('is-active');if(activeAgents.length)document.querySelector('[data-stage="powerhouse"]')?.classList.add('is-active');if(state.module)document.querySelector('[data-stage="module"]')?.classList.add('is-active');if(state.outcome?.evidenceId)document.querySelector('[data-stage="outcome"]')?.classList.add('is-active')}
function renderExplanation(state){const s=state.source?SOURCE_COPY[state.source.id]:null,m=state.module?MODULE_COPY[state.module.id]:null;document.getElementById('explainSource').textContent=s?`${s[0]} (${statusText(state.source.status)})`:'Niets actief';document.getElementById('explainSourceText').textContent=s?.[1]??'Selecteer een bron of gebruik de expliciete demo-route.';document.getElementById('explainBrain').textContent=state.brain.status==='idle'?'Geen actieve verwerking':`AI Brain: ${statusText(state.brain.status)}`;document.getElementById('explainBrainText').textContent=state.brain.status==='idle'?'Zonder runtime-evidence wordt geen verwerking geclaimd.':`Actieve capabilities: ${state.brain.capabilities.map(c=>c.replaceAll('-',' ')).join(', ')||'geen opgegeven'}.`;document.getElementById('explainModule').textContent=m?`${m[0]} (${statusText(state.module.status)})`:'Geen module actief';document.getElementById('explainModuleText').textContent=m?.[1]??'Geen outputflow zolang er geen actieve module is.';document.getElementById('actionText').textContent=state.action?.label??'Geen actie actief';document.getElementById('outcomeText').textContent=state.outcome?.evidenceId?'Geverifieerd met evidence':'Niet geverifieerd';document.getElementById('learningText').textContent=statusText(state.learning.status)}
function renderMobileSheet(state,tab='info'){const t=document.getElementById('mobileSheetContent');if(!t)return;if(tab==='info')t.textContent=state.source?`${SOURCE_COPY[state.source.id]?.[0]??state.source.id}: ${SOURCE_COPY[state.source.id]?.[1]??''}`:'Geen actieve bron.';if(tab==='processing')t.textContent=state.brain.status==='idle'?'Geen actieve verwerking.':`Datahub ${statusText(state.datahub.status)} · AI Brain ${statusText(state.brain.status)} · ${state.powerhouse.filter(a=>a.status!=='idle').length} Powerhouse-agent(s) actief.`;if(tab==='result')t.textContent=state.module?`${MODULE_COPY[state.module.id]?.[0]??state.module.id}: ${MODULE_COPY[state.module.id]?.[1]??''} Outcome: ${state.outcome?.evidenceId?'geverifieerd':'nog niet geverifieerd'}.`:'Geen portaalmodule actief.'}
export function renderCockpit(){runtimeState=buildPreviewState();const root=document.getElementById('brain-cockpit');renderSelections(runtimeState);renderCapabilities(runtimeState);renderAgents(runtimeState);renderStage(runtimeState);renderExplanation(runtimeState);renderPortalFlow(root,runtimeState);renderMobileSheet(runtimeState,document.querySelector('[data-mobile-tab].is-active')?.dataset.mobileTab??'info')}
export function selectSource(id){selection=reducePortalSelection(selection,{type:'SELECT_SOURCE',id});if(!demoMode)demoMode=true;renderCockpit()}
export function selectModule(id){selection=reducePortalSelection(selection,{type:'SELECT_MODULE',id});if(!demoMode)demoMode=true;renderCockpit()}
export function clearFlowSelection(){selection=reducePortalSelection(selection,{type:'CLEAR'});demoMode=false;renderCockpit()}
function bind(){document.querySelectorAll('[data-source-id]').forEach(el=>el.addEventListener('click',()=>selectSource(el.dataset.sourceId)));document.querySelectorAll('[data-module-id]').forEach(el=>el.addEventListener('click',()=>selectModule(el.dataset.moduleId)));document.getElementById('demoRoute')?.addEventListener('click',()=>{selection={source:'documenten',module:'inzicht'};demoMode=true;renderCockpit()});document.getElementById('clearRoute')?.addEventListener('click',clearFlowSelection);document.querySelectorAll('[data-mobile-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-mobile-tab]').forEach(x=>x.classList.toggle('is-active',x===btn));renderMobileSheet(runtimeState,btn.dataset.mobileTab)}));window.addEventListener('resize',()=>renderPortalFlow(document.getElementById('brain-cockpit'),runtimeState))}
if(typeof document!=='undefined'){bind();renderCockpit()}
