import { normalizePortalFlowState } from './portal-flow-state.js';
import { renderPortalFlow, renderStatusClass } from './portal-flow-renderer.js';
import { mapRuntimeSnapshotToPortalFlow } from './portal-powerhouse-adapter.js';
import { PORTAL_SECTIONS, PORTAL_PAGE_INDEX, findPortalPage } from './portal-content-map.js';

export function reducePortalSelection(state, action) {
  const current = { source: state?.source ?? null, module: state?.module ?? null };
  if (action?.type === 'SELECT_SOURCE') return { ...current, source: current.source === action.id ? null : action.id };
  if (action?.type === 'SELECT_MODULE') return { ...current, module: current.module === action.id ? null : action.id };
  if (action?.type === 'CLEAR') return { source:null, module:null };
  return current;
}
export function getPortalCustomerSlug(search = typeof window !== 'undefined' ? window.location.search : '') { return new URLSearchParams(search).get('klant') || null; }
export function withCustomer(path, klant = getPortalCustomerSlug()) { const origin = typeof window !== 'undefined' ? window.location.origin : 'https://www.bedrijfsgeheugen.nl'; const url = new URL(path, origin); if (klant) url.searchParams.set('klant', klant); return url.pathname + url.search + url.hash; }
export function legacyTabForPage(pageId) { return findPortalPage(pageId)?.legacyTab ?? null; }
export function buildLegacyPortalUrl(klant = getPortalCustomerSlug()) { return withCustomer('/klantportaal', klant); }

const SOURCE_COPY={systemen:['Systemen','ERP, CRM, finance, e-mail en HR leveren operationele data aan.'],documenten:['Documenten','Contracten, notities, rapporten en beleid leveren ongestructureerde kennis aan.'],processen:['Processen','Werkstromen, procedures en taken laten zien hoe werk werkelijk loopt.'],mensen:['Mensen','Expertise, verantwoordelijkheid en impliciete kennis worden zichtbaar.'],dashboards:['Dashboards','KPI’s en rapportages geven het cijfermatige beeld van de organisatie.'],extern:['Externe data','Markt, concurrentie en regelgeving voegen actuele context van buiten toe.'],modellen:['Modellen','Rekenmodellen en scenario’s laten mogelijke impact van keuzes zien.'],canvassen:['Canvassen','Strategie en plannen geven richting en maken gewenste verandering expliciet.']};
const MODULE_COPY={inzicht:['Inzicht','Managementsamenvatting, signalen en stand van zaken.'],vergelijken:['Vergelijken','Opties, verschillen en afwegingen naast elkaar.'],denken:['Denken','Redeneren, verklaren en advies.'],overname:['Overname','Due diligence, kansen en risico’s.'],doen:['Doen','Acties, eigenaarschap en opvolging.'],dna:['Strategy DNA','Richting, keuzes en strategische fit.'],canvas:['Execution Canvas','Afhankelijkheden en uitvoering.'],roadmap:['Roadmap','Volgorde, planning en milestones.'],documenten:['Documenten','Vastgelegde kennis en context.'],notities:['Notities','Observaties en besluiten.'],activiteit:['Activiteit','Wie deed wat en wanneer.'],wijzigingen:['Wijzigingen','Nieuwe signalen en mutaties.'],koppelingen:['Koppelingen','Status van bronnen en synchronisaties.'],taken:['Taken & werkstromen','Van inzicht naar toegewezen uitvoering.'],uren:['Uren & facturen','Tijd, administratie en opbrengst.'],actueel:['Actueel houden','Feedback, actualisatie en leren.']};

let selection={source:null,module:null}; let runtimeState=normalizePortalFlowState({}); let demoMode=false; let legacyRequestedPage='overzicht'; let legacyPoll=null;
function buildPreviewState(){ if(!demoMode) return normalizePortalFlowState({}); return mapRuntimeSnapshotToPortalFlow({source:{id:selection.source??'documenten',status:'running',lastSync:'zojuist',quality:'preview'},datahub:{status:'verified'},brain:{status:'running',capabilities:['begrijpt-context','legt-verbanden','vat-samen','prioriteert','adviseert']},agents:[{id:'monitor',name:'Detectie',category:'detectie',status:'completed',evidence:['preview-evidence-monitor']},{id:'analyse',name:'Analyse',category:'analyse',status:'running',evidence:[]},{id:'execute',name:'Uitvoering',category:'uitvoering',status:'waiting',evidence:[]},{id:'verify',name:'Verificatie',category:'verificatie',status:'waiting',evidence:[]},{id:'heal',name:'Self-heal',category:'self-heal',status:'idle',evidence:[]},{id:'learning',name:'Learning/writeback',category:'learning',status:'waiting',evidence:[],learningPending:true}],module:selection.module?{id:selection.module,status:'running'}:{id:'inzicht',status:'running'},action:{status:'queued',label:'Bekijk en beoordeel de nieuwe inzichten'},outcome:{status:'waiting',evidenceId:null},learning:{status:'waiting'},updatedAt:new Date().toISOString()}); }
function statusText(status){return({idle:'Idle',queued:'In wachtrij',running:'Actief',waiting:'Wacht',blocked:'Geblokkeerd',failed:'Fout',recovering:'Herstelt',verified:'Geverifieerd',completed:'Afgerond',disconnected:'Niet gekoppeld'})[status]??status}
function applyNodeStatus(el,status){if(!el)return;el.classList.remove('is-idle','is-queued','is-running','is-waiting','is-blocked','is-failed','is-recovering','is-verified','is-completed','is-disconnected');el.classList.add(renderStatusClass(status))}
function renderSelections(state){const sourceList=document.querySelector('[data-source-selector]'),moduleGrid=document.querySelector('[data-module-selector]');sourceList?.classList.toggle('has-selection',!!selection.source);moduleGrid?.classList.toggle('has-selection',!!selection.module);document.querySelectorAll('[data-source-id]').forEach(el=>el.classList.toggle('is-selected',el.dataset.sourceId===selection.source));document.querySelectorAll('[data-module-id]').forEach(el=>el.classList.toggle('is-selected',el.dataset.moduleId===selection.module));if(state.source)applyNodeStatus(document.querySelector(`[data-source-id="${state.source.id}"]`),state.source.status);applyNodeStatus(document.querySelector('[data-flow-node="datahub"]'),state.datahub.status);applyNodeStatus(document.querySelector('[data-flow-node="brain"]'),state.brain.status);if(state.module)applyNodeStatus(document.querySelector(`[data-module-id="${state.module.id}"]`),state.module.status)}
function renderCapabilities(state){document.querySelectorAll('[data-capability]').forEach(el=>el.classList.toggle('is-active',state.brain.capabilities.includes(el.dataset.capability)))}
function renderAgents(state){const slots=[...document.querySelectorAll('#agentList .agent')],mapped=new Map(state.powerhouse.map(a=>[a.category,a])),categories=['detectie','analyse','uitvoering','verificatie','self-heal','learning'];slots.forEach((slot,index)=>{const agent=mapped.get(categories[index]);const status=agent?.status??'idle';applyNodeStatus(slot,status);slot.querySelector('small').textContent=statusText(status);slot.title=agent?[agent.triggerReason,agent.error,agent.recoveryObligation?.reason].filter(Boolean).join(' · '):'Geen runtime-status beschikbaar'})}
function renderStage(state){document.getElementById('stageSource').textContent=state.source?`${SOURCE_COPY[state.source.id]?.[0]??state.source.id}: ${statusText(state.source.status)}`:'Geen actieve bron';document.getElementById('stageHub').textContent=statusText(state.datahub.status);document.getElementById('stageBrain').textContent=statusText(state.brain.status);const activeAgents=state.powerhouse.filter(a=>a.status!=='idle');document.getElementById('stagePowerhouse').textContent=activeAgents.length?`${activeAgents.length} agent(s) · ${statusText(activeAgents[0].status)}`:'Geen agent actief';document.getElementById('stageModule').textContent=state.module?`${MODULE_COPY[state.module.id]?.[0]??state.module.id}: ${statusText(state.module.status)}`:'Geen outputmodule';document.getElementById('stageOutcome').textContent=state.outcome?.evidenceId?'Evidence aanwezig':'Geen evidence';document.querySelectorAll('.stage-strip>div').forEach(el=>el.classList.remove('is-active'));if(state.source)document.querySelector('[data-stage="source"]')?.classList.add('is-active');if(state.datahub.status!=='idle')document.querySelector('[data-stage="datahub"]')?.classList.add('is-active');if(state.brain.status!=='idle')document.querySelector('[data-stage="brain"]')?.classList.add('is-active');if(activeAgents.length)document.querySelector('[data-stage="powerhouse"]')?.classList.add('is-active');if(state.module)document.querySelector('[data-stage="module"]')?.classList.add('is-active');if(state.outcome?.evidenceId)document.querySelector('[data-stage="outcome"]')?.classList.add('is-active')}
function renderExplanation(state){const s=state.source?SOURCE_COPY[state.source.id]:null,m=state.module?MODULE_COPY[state.module.id]:null;document.getElementById('explainSource').textContent=s?`${s[0]} (${statusText(state.source.status)})`:'Niets actief';document.getElementById('explainSourceText').textContent=s?.[1]??'Selecteer een bron of gebruik de expliciete demo-route.';document.getElementById('explainBrain').textContent=state.brain.status==='idle'?'Geen actieve verwerking':`AI Brain: ${statusText(state.brain.status)}`;document.getElementById('explainBrainText').textContent=state.brain.status==='idle'?'Zonder runtime-evidence wordt geen verwerking geclaimd.':`Actieve capabilities: ${state.brain.capabilities.map(c=>c.replaceAll('-',' ')).join(', ')||'geen opgegeven'}.`;document.getElementById('explainModule').textContent=m?`${m[0]} (${statusText(state.module.status)})`:'Geen module actief';document.getElementById('explainModuleText').textContent=m?.[1]??'Geen outputflow zolang er geen actieve module is.';document.getElementById('actionText').textContent=state.action?.label??'Geen actie actief';document.getElementById('outcomeText').textContent=state.outcome?.evidenceId?'Geverifieerd met evidence':'Niet geverifieerd';document.getElementById('learningText').textContent=statusText(state.learning.status)}
function renderMobileSheet(state,tab='info'){const t=document.getElementById('mobileSheetContent');if(!t)return;if(tab==='info')t.textContent=state.source?`${SOURCE_COPY[state.source.id]?.[0]??state.source.id}: ${SOURCE_COPY[state.source.id]?.[1]??''}`:'Geen actieve bron.';if(tab==='processing')t.textContent=state.brain.status==='idle'?'Geen actieve verwerking.':`Datahub ${statusText(state.datahub.status)} · AI Brain ${statusText(state.brain.status)} · ${state.powerhouse.filter(a=>a.status!=='idle').length} Powerhouse-agent(s) actief.`;if(tab==='result')t.textContent=state.module?`${MODULE_COPY[state.module.id]?.[0]??state.module.id}: ${MODULE_COPY[state.module.id]?.[1]??''} Outcome: ${state.outcome?.evidenceId?'geverifieerd':'nog niet geverifieerd'}.`:'Geen portaalmodule actief.'}
export function renderCockpit(){runtimeState=buildPreviewState();const root=document.getElementById('brain-cockpit');renderSelections(runtimeState);renderCapabilities(runtimeState);renderAgents(runtimeState);renderStage(runtimeState);renderExplanation(runtimeState);renderPortalFlow(root,runtimeState);renderMobileSheet(runtimeState,document.querySelector('[data-mobile-tab].is-active')?.dataset.mobileTab??'info')}
export function selectSource(id){selection=reducePortalSelection(selection,{type:'SELECT_SOURCE',id});if(!demoMode)demoMode=true;renderCockpit()}
export function selectModule(id){selection=reducePortalSelection(selection,{type:'SELECT_MODULE',id});if(!demoMode)demoMode=true;renderCockpit()}
export function clearFlowSelection(){selection=reducePortalSelection(selection,{type:'CLEAR'});demoMode=false;renderCockpit()}

function bridgeStyle(){if(document.getElementById('legacy-bridge-style'))return;const style=document.createElement('style');style.id='legacy-bridge-style';style.textContent=`.portal-library-btn{border:1px solid var(--line);background:#fff;border-radius:13px;padding:10px 12px;font-weight:800;color:var(--ink);cursor:pointer}.portal-workspace{position:fixed;inset:0;z-index:80;background:#f4f7fc;display:grid;grid-template-rows:auto 1fr;transform:translateY(105%);transition:transform .24s ease}.portal-workspace.is-open{transform:none}.portal-workspace__head{display:flex;align-items:center;gap:10px;padding:10px 14px;background:#fff;border-bottom:1px solid var(--line)}.portal-workspace__head strong{font-size:16px}.portal-workspace__head small{color:var(--muted)}.portal-workspace__head button{border:1px solid var(--line);background:#fff;border-radius:11px;padding:9px 11px;font-weight:800}.portal-workspace__close{margin-left:auto}.portal-workspace__body{min-height:0;display:grid;grid-template-columns:270px 1fr}.portal-library{overflow:auto;padding:12px;background:#fbfcff;border-right:1px solid var(--line)}.portal-library section{margin-bottom:14px}.portal-library h4{margin:0 0 6px;font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:#6175aa}.portal-library button{display:block;width:100%;text-align:left;border:0;background:transparent;border-radius:10px;padding:8px 10px;font-size:12px;color:var(--ink)}.portal-library button:hover,.portal-library button.is-active{background:#eaf2ff;color:#064fd3;font-weight:800}.portal-library button[data-new=true]{color:#6944da}.portal-frame{width:100%;height:100%;border:0;background:#fff}.portal-workspace__note{padding:7px 10px;border-radius:999px;background:#eef9f5;color:#12734f;font-size:10px;font-weight:800}@media(max-width:760px){.portal-workspace__body{grid-template-columns:1fr}.portal-library{display:flex;gap:5px;overflow:auto;border-right:0;border-bottom:1px solid var(--line);padding:8px}.portal-library section{display:flex;gap:5px;margin:0}.portal-library h4{display:none}.portal-library button{width:auto;white-space:nowrap;border:1px solid var(--line);background:#fff}.portal-workspace__head small,.portal-workspace__note{display:none}}`;document.head.append(style)}
function mountPortalLibrary(){if(document.getElementById('legacyWorkspace'))return;bridgeStyle();const opener=document.createElement('button');opener.id='allPortalPages';opener.className='portal-library-btn';opener.textContent='Alle portalpagina’s';const target=document.querySelector('.head-actions');if(target)target.append(opener);else document.querySelector('.top-actions')?.append(opener);const workspace=document.createElement('aside');workspace.id='legacyWorkspace';workspace.className='portal-workspace';workspace.setAttribute('aria-hidden','true');workspace.innerHTML=`<header class="portal-workspace__head"><strong id="legacyTitle">Alle bestaande portalinhoud</strong><small id="legacySubtitle">De live functionaliteit blijft intact binnen de nieuwe cockpit.</small><span class="portal-workspace__note">1-op-1 bestaande inhoud</span><button id="legacyExternal">Open volledig portaal ↗</button><button id="legacyClose" class="portal-workspace__close" aria-label="Sluiten">×</button></header><div class="portal-workspace__body"><nav id="fullPortalNav" class="portal-library" aria-label="Alle bestaande portalpagina's"></nav><iframe id="legacyFrame" class="portal-frame" title="Bestaand klantenportaal"></iframe></div>`;document.body.append(workspace);renderPortalLibraryNav();opener.addEventListener('click',()=>openLegacyPortalPage('overzicht'));document.getElementById('legacyClose')?.addEventListener('click',closeLegacyWorkspace);document.getElementById('legacyExternal')?.addEventListener('click',()=>window.open(buildLegacyPortalUrl(),'_blank','noopener'));document.getElementById('legacyFrame')?.addEventListener('load',activateRequestedLegacyTab)}
function renderPortalLibraryNav(){const nav=document.getElementById('fullPortalNav');if(!nav)return;nav.innerHTML='';for(const [sectionId,section] of Object.entries(PORTAL_SECTIONS)){const group=document.createElement('section');const h=document.createElement('h4');h.textContent=section.label;group.append(h);for(const pageId of section.pages){const page=PORTAL_PAGE_INDEX[pageId];const button=document.createElement('button');button.type='button';button.dataset.pageId=pageId;button.dataset.new=page.legacyTab? 'false':'true';button.textContent=page.label+(page.legacyTab?'':' · nieuw');button.addEventListener('click',()=>page.legacyTab?openLegacyPortalPage(pageId):focusNewCockpitPage(pageId));group.append(button)}nav.append(group)}}
function focusNewCockpitPage(pageId){document.querySelectorAll('#fullPortalNav button').forEach(b=>b.classList.toggle('is-active',b.dataset.pageId===pageId));document.getElementById('legacyTitle').textContent=findPortalPage(pageId)?.label??pageId;document.getElementById('legacySubtitle').textContent='Dit is nieuwe Brain/Powerhouse-functionaliteit en heeft geen oude live tab om te embedden.';if(['bronnenstatus','datahubstatus','brain-verwerking','agentstatus','actieve-acties','recovery-obligations','outcomes-evidence','learning-writeback','self-heal','audittrail'].includes(pageId)){closeLegacyWorkspace();document.querySelector('.cockpit-card')?.scrollIntoView({behavior:'smooth',block:'start'})}}
export function activateLegacyTabInDocument(doc,pageId){const tab=legacyTabForPage(pageId);if(!tab||!doc)return false;const button=doc.querySelector(`[data-p="${tab}"]`);if(!button)return false;button.click();return true}
function activateRequestedLegacyTab(){const frame=document.getElementById('legacyFrame');if(!frame)return;clearInterval(legacyPoll);let attempts=0;legacyPoll=setInterval(()=>{attempts++;try{if(activateLegacyTabInDocument(frame.contentDocument,legacyRequestedPage)||attempts>=40)clearInterval(legacyPoll)}catch{clearInterval(legacyPoll)}},500)}
export function openLegacyPortalPage(pageId){const page=findPortalPage(pageId);if(!page?.legacyTab)return false;legacyRequestedPage=pageId;const workspace=document.getElementById('legacyWorkspace');const frame=document.getElementById('legacyFrame');if(!workspace||!frame)return false;workspace.classList.add('is-open');workspace.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';document.querySelectorAll('#fullPortalNav button').forEach(b=>b.classList.toggle('is-active',b.dataset.pageId===pageId));document.getElementById('legacyTitle').textContent=page.label;document.getElementById('legacySubtitle').textContent=`Bestaande live pagina · ${PORTAL_SECTIONS[page.sectionId].label} · klantcontext blijft behouden.`;const src=buildLegacyPortalUrl();if(frame.getAttribute('src')!==src){frame.setAttribute('src',src)}else{activateRequestedLegacyTab()}return true}
export function closeLegacyWorkspace(){const workspace=document.getElementById('legacyWorkspace');workspace?.classList.remove('is-open');workspace?.setAttribute('aria-hidden','true');if(typeof document!=='undefined')document.body.style.overflow=''}

function bind(){document.querySelectorAll('[data-source-id]').forEach(el=>el.addEventListener('click',()=>selectSource(el.dataset.sourceId)));document.querySelectorAll('[data-module-id]').forEach(el=>el.addEventListener('click',()=>selectModule(el.dataset.moduleId)));document.getElementById('demoRoute')?.addEventListener('click',()=>{selection={source:'documenten',module:'inzicht'};demoMode=true;renderCockpit()});document.getElementById('clearRoute')?.addEventListener('click',clearFlowSelection);document.querySelectorAll('[data-mobile-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-mobile-tab]').forEach(x=>x.classList.toggle('is-active',x===btn));renderMobileSheet(runtimeState,btn.dataset.mobileTab)}));window.addEventListener('resize',()=>renderPortalFlow(document.getElementById('brain-cockpit'),runtimeState));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLegacyWorkspace()});mountPortalLibrary()}
if(typeof document!=='undefined'){bind();renderCockpit()}
