const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const clone=value=>typeof structuredClone==='function'?structuredClone(value):JSON.parse(JSON.stringify(value));
const sprintValue=value=>value===null||value===undefined||value==='backlog'?null:Math.max(1,Number(value)||1);

export function normalizeDeliveryState(state={}){
 const next=clone(state||{});next.epics=Array.isArray(next.epics)?next.epics:[];next.features=Array.isArray(next.features)?next.features:[];next.stories=Array.isArray(next.stories)?next.stories:[];next.sprints=Math.max(1,Math.min(12,Number(next.sprints)||6));
 next.features=next.features.map((feature,index)=>({...feature,id:String(feature.id||`f-${index+1}`),sprint:sprintValue(feature.sprint)}));
 next.stories=next.stories.map((story,index)=>({...story,id:String(story.id||`s-${index+1}`),feature:String(story.feature||'')}));return next;
}
export function moveFeature(state,featureId,sprint){const next=normalizeDeliveryState(state);next.features=next.features.map(feature=>feature.id===String(featureId)?{...feature,sprint:sprintValue(sprint)}:feature);return next;}
export function moveStory(state,storyId,featureId){const next=normalizeDeliveryState(state);next.stories=next.stories.map(story=>story.id===String(storyId)?{...story,feature:String(featureId)}:story);return next;}
export function reorderFeature(state,sourceId,targetId){const next=normalizeDeliveryState(state);const from=next.features.findIndex(feature=>feature.id===String(sourceId));const to=next.features.findIndex(feature=>feature.id===String(targetId));if(from<0||to<0||from===to)return next;const [item]=next.features.splice(from,1);next.features.splice(to,0,item);return next;}

function storyMarkup(story,features){return `<div class="v2story" draggable="true" data-story-id="${esc(story.id)}"><label><input type="checkbox" data-story-done ${story.done?'checked':''}><span>${esc(story.role||'Rol')} · ${esc(story.wish||story.title||'User story')}</span></label>${story.reason?`<small>${esc(story.reason)}</small>`:''}<select data-story-target aria-label="Verplaats user story"><option value="">Verplaats naar…</option>${features.filter(feature=>feature.id!==story.feature).map(feature=>`<option value="${esc(feature.id)}">${esc(feature.title||feature.id)}</option>`).join('')}</select></div>`;}
function featureMarkup(feature,state){const stories=state.stories.filter(story=>story.feature===feature.id);return `<article class="v2feature" draggable="true" data-feature-id="${esc(feature.id)}" data-sprint="${feature.sprint??'backlog'}"><header><label><input type="checkbox" data-feature-done ${feature.done?'checked':''}><span>Feature</span></label><b>${esc(feature.title||'Nieuwe feature')}</b>${feature.outcome?`<small>Levert op: ${esc(feature.outcome)}</small>`:''}</header><div class="v2stories" data-story-drop="${esc(feature.id)}">${stories.map(story=>storyMarkup(story,state.features)).join('')||'<p class="v2deliveryempty">Sleep een user story hierheen</p>'}</div><button type="button" data-add-story>+ User story</button><div class="v2featuremove"><button type="button" data-feature-move-left aria-label="Feature naar vorige sprint">←</button><span>${feature.sprint==null?'Backlog':`Sprint ${feature.sprint}`}</span><button type="button" data-feature-move-right aria-label="Feature naar volgende sprint">→</button></div></article>`;}
function laneMarkup(key,state){const features=state.features.filter(feature=>key==='backlog'?feature.sprint==null:feature.sprint===key);const value=features.reduce((sum,feature)=>sum+(Number(feature.value)||0),0);return `<section class="v2deliverylane" data-delivery-sprint="${key}"><header><b>${key==='backlog'?'Backlog':`Sprint ${key}`}</b><span>${features.length} features${value?` · € ${Math.round(value).toLocaleString('nl-NL')}`:''}</span></header><div class="v2featuredrop" data-feature-drop="${key}">${features.map(feature=>featureMarkup(feature,state)).join('')||'<p class="v2deliveryempty">Geen features</p>'}</div></section>`;}
function boardMarkup(state){const lanes=['backlog',...Array.from({length:state.sprints},(_,index)=>index+1)];return `<div class="v2deliverytoolbar"><div><strong>Deliveryplan</strong><span>Features naar backlog/sprints · stories naar een andere feature.</span></div><button type="button" data-add-feature>+ Feature</button></div><div class="v2deliveryboard" data-delivery-board>${lanes.map(key=>laneMarkup(key,state)).join('')}</div>`;}

export function mountDeliveryBoard(root,{domainState,onSaveStatus}={}){
 if(!root?.replaceChildren)throw new TypeError('DELIVERY_BOARD_ROOT_REQUIRED');if(!domainState?.get||!domainState?.set)throw new TypeError('DELIVERY_DOMAIN_STATE_REQUIRED');
 let state=normalizeDeliveryState(domainState.get('portal.deliveryPlan')||{});let draggedFeature=null,draggedStory=null,saveTimer=null;
 const persist=next=>{state=normalizeDeliveryState(next);domainState.set('portal.deliveryPlan',state);onSaveStatus?.(domainState.status?.()||'dirty');clearTimeout(saveTimer);saveTimer=setTimeout(()=>domainState.flush?.().then(()=>onSaveStatus?.(domainState.status?.()||'saved')).catch(()=>onSaveStatus?.('error')),250);render();};
 const updateFeature=(id,patch)=>persist({...state,features:state.features.map(feature=>feature.id===id?{...feature,...patch}:feature)});
 const updateStory=(id,patch)=>persist({...state,stories:state.stories.map(story=>story.id===id?{...story,...patch}:story)});
 const render=()=>{root.innerHTML=boardMarkup(state);root.querySelector('[data-add-feature]')?.addEventListener('click',()=>{const id=`f-${Date.now()}`;persist({...state,features:[...state.features,{id,title:'Nieuwe feature',epic:'',sprint:null,value:0,outcome:'',done:false}]});});
 root.querySelectorAll('[data-feature-id]').forEach(card=>{const id=card.dataset.featureId;card.addEventListener('dragstart',event=>{if(event.target.closest('[data-story-id]'))return;draggedFeature=id;draggedStory=null;event.dataTransfer?.setData('text/plain',`F:${id}`);card.classList.add('dragging');});card.addEventListener('dragend',()=>{draggedFeature=null;card.classList.remove('dragging');});card.addEventListener('dragover',event=>{if(!draggedFeature||draggedFeature===id)return;event.preventDefault();card.classList.add('dragover');});card.addEventListener('dragleave',()=>card.classList.remove('dragover'));card.addEventListener('drop',event=>{if(!draggedFeature||draggedFeature===id)return;event.preventDefault();event.stopPropagation();const sprint=card.dataset.sprint==='backlog'?null:Number(card.dataset.sprint);persist(reorderFeature(moveFeature(state,draggedFeature,sprint),draggedFeature,id));});card.querySelector('[data-feature-done]')?.addEventListener('change',event=>updateFeature(id,{done:event.target.checked}));card.querySelector('[data-add-story]')?.addEventListener('click',()=>persist({...state,stories:[...state.stories,{id:`s-${Date.now()}`,feature:id,role:'Rol',wish:'Nieuwe user story',reason:'',done:false}]}));card.querySelector('[data-feature-move-left]')?.addEventListener('click',()=>{const current=card.dataset.sprint==='backlog'?null:Number(card.dataset.sprint);if(current===null)return;persist(moveFeature(state,id,current<=1?null:current-1));});card.querySelector('[data-feature-move-right]')?.addEventListener('click',()=>{const current=card.dataset.sprint==='backlog'?null:Number(card.dataset.sprint);persist(moveFeature(state,id,current===null?1:Math.min(state.sprints,current+1)));});});
 root.querySelectorAll('[data-feature-drop]').forEach(lane=>{lane.addEventListener('dragover',event=>{if(!draggedFeature)return;event.preventDefault();lane.classList.add('dragover');});lane.addEventListener('dragleave',()=>lane.classList.remove('dragover'));lane.addEventListener('drop',event=>{if(!draggedFeature)return;event.preventDefault();const key=lane.dataset.featureDrop;persist(moveFeature(state,draggedFeature,key==='backlog'?null:Number(key)));});});
 root.querySelectorAll('[data-story-id]').forEach(story=>{const id=story.dataset.storyId;story.addEventListener('dragstart',event=>{event.stopPropagation();draggedStory=id;draggedFeature=null;event.dataTransfer?.setData('text/plain',`S:${id}`);story.classList.add('dragging');});story.addEventListener('dragend',()=>{draggedStory=null;story.classList.remove('dragging');});story.querySelector('[data-story-done]')?.addEventListener('change',event=>updateStory(id,{done:event.target.checked}));story.querySelector('[data-story-target]')?.addEventListener('change',event=>{if(event.target.value)persist(moveStory(state,id,event.target.value));});});
 root.querySelectorAll('[data-story-drop]').forEach(zone=>{zone.addEventListener('dragover',event=>{if(!draggedStory)return;event.preventDefault();zone.classList.add('dragover');});zone.addEventListener('dragleave',()=>zone.classList.remove('dragover'));zone.addEventListener('drop',event=>{if(!draggedStory)return;event.preventDefault();event.stopPropagation();persist(moveStory(state,draggedStory,zone.dataset.storyDrop));});});};render();return Object.freeze({getState:()=>normalizeDeliveryState(state),moveFeature:(id,sprint)=>persist(moveFeature(state,id,sprint)),moveStory:(id,feature)=>persist(moveStory(state,id,feature))});
}