import { createClient } from 'npm:@supabase/supabase-js@2';

const BRON='bg-analytics-sync-composio';
const FAILOVER_CONTRACT='ga4-auth-failover-v1';
const DEFAULT_PROPERTY='properties/546874601';
const DEFAULT_WINDSOR_ACCOUNT='546874601';
const WINDSOR_SOURCE='windsor-googleanalytics4';
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
const clean=(v:unknown)=>{const s=String(v??'').trim();return!s||s==='(not set)'||s==='(direct)'?null:s};
const csvCell=(v:unknown)=>{const s=String(v??'');return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s};
const b64url=(buf:ArrayBuffer|Uint8Array)=>btoa(String.fromCharCode(...new Uint8Array(buf as ArrayBuffer))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const enc=(o:unknown)=>b64url(new TextEncoder().encode(JSON.stringify(o)));
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function yesterdayUtc(){const d=new Date();d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10)}
function parseAccount(raw:string|null):{client_email:string;private_key:string}|null{if(!raw)return null;try{const j=JSON.parse(raw);if(j?.client_email&&j?.private_key)return j}catch{}return null}
function classifyFailure(detail:string){return /401|403|TOKEN|PERMISSION/i.test(detail)?'AUTH':'REMOTE'}
async function secret(db:any,name:string){const env=Deno.env.get(name);if(env)return env;const {data}=await db.rpc('bg_geheim',{p_naam:name});return typeof data==='string'&&data.trim()?data.trim():null}
async function accessToken(sa:{client_email:string;private_key:string}){const pem=sa.private_key.replace(/\\n/g,'\n').replace(/-----[^-]+-----/g,'').replace(/\s+/g,'');const der=Uint8Array.from(atob(pem),c=>c.charCodeAt(0));const key=await crypto.subtle.importKey('pkcs8',der,{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const now=Math.floor(Date.now()/1000);const unsigned=`${enc({alg:'RS256',typ:'JWT'})}.${enc({iss:sa.client_email,scope:'https://www.googleapis.com/auth/analytics.readonly',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600})}`;const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(unsigned));const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:`${unsigned}.${b64url(sig)}`})});const b:any=await r.json().catch(()=>({}));if(!r.ok||!b.access_token)throw new Error(`GOOGLE_TOKEN_${r.status}:${String(b.error_description||b.error||'').slice(0,160)}`);return b.access_token}
function reportRows(report:any){const dims=(report.dimensionHeaders||[]).map((x:any)=>x.name);const metrics=(report.metricHeaders||[]).map((x:any)=>x.name);return (report.rows||[]).map((row:any)=>{const out:Record<string,string>={};dims.forEach((name:string,i:number)=>out[name]=row.dimensionValues?.[i]?.value??'');metrics.forEach((name:string,i:number)=>out[name]=row.metricValues?.[i]?.value??'');return out})}
async function directGA4(sa:{client_email:string;private_key:string},property:string,day:string){const token=await accessToken(sa);const r=await fetch(`https://analyticsdata.googleapis.com/v1beta/${property}:runReport`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({dateRanges:[{startDate:day,endDate:day}],dimensions:[{name:'date'},{name:'pagePath'},{name:'sessionCampaignName'}],metrics:[{name:'sessions'},{name:'activeUsers'},{name:'eventCount'}],limit:250000,keepEmptyRows:false})});const b:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`GA4_${r.status}:${String(b?.error?.message||'').slice(0,200)}`);return reportRows(b)}
async function windsorGA4(apiKey:string,accountId:string,day:string){const u=new URL('https://connectors.windsor.ai/googleanalytics4');u.searchParams.set('api_key',apiKey);u.searchParams.set('fields','date,page_path,campaign_name,sessions,active_users,event_count,measurement_id');u.searchParams.set('date_from',day);u.searchParams.set('date_to',day);u.searchParams.set('select_accounts',accountId);u.searchParams.set('_renderer','json');u.searchParams.set('refresh_since','3d');u.searchParams.set('refresh_interval','1h');const r=await fetch(u,{headers:{'user-agent':'Bedrijfsgeheugen-Powerhouse/1.0'}});const b:any=await r.json().catch(()=>({}));if(!r.ok||!Array.isArray(b?.data))throw new Error(`WINDSOR_API_${r.status}:${String(b?.error?.message||b?.error||'invalid response').slice(0,200)}`);return b.data.map((x:any)=>({date:String(x.date||'').replaceAll('-',''),pagePath:String(x.page_path||'/'),sessionCampaignName:String(x.campaign_name||''),sessions:String(x.sessions??0),activeUsers:String(x.active_users??0),eventCount:String(x.event_count??0),measurementId:String(x.measurement_id||'')}))}
async function recentWindsorReadback(db:any){const cutoff=new Date(Date.now()-48*3600*1000).toISOString();const {data,error}=await db.from('bg_ga4_csv_batches').select('run_id,period_start,period_end,rows_total,rows_attributed,completed_at,source,detail').ilike('source','windsor%').gte('completed_at',cutoff).gt('rows_total',0).order('completed_at',{ascending:false}).limit(1);if(error)throw new Error(`WINDSOR_READBACK_LOOKUP:${error.message}`);return data?.[0]||null}
async function writeRuntime(db:any,dedupeKey:string,state:string,evidence:any){await db.from('powerhouse_runtime_events').upsert({dedupe_key:dedupeKey,event_type:'ga4_failover_observed',source:BRON,subject_key:'ga4-analytics',channel:'website',occurred_at:new Date().toISOString(),evidence,context:{contract:FAILOVER_CONTRACT,canonical_collector:BRON},state,data_quality:'verified',confidence:1},{onConflict:'dedupe_key'})}

Deno.serve(async(req:Request)=>{
 if(req.method!=='POST')return json({error:'POST_ONLY'},405);
 const url=(Deno.env.get('SUPABASE_URL')||'').replace(/\/$/,'');const serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!url||!serviceKey)return json({error:'CONFIG'},500);
 const db=createClient(url,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});
 const bewijs=(groen:boolean,detail:unknown,klasse:string|null=null)=>db.rpc('bg_bewijs',{p_bron:BRON,p_groen:groen,p_detail:detail,p_foutklasse:klasse}).then(()=>{},()=>{});
 const property=Deno.env.get('GA4_PROPERTY_RESOURCE')||DEFAULT_PROPERTY;
 const envSa=parseAccount(Deno.env.get('GOOGLE_SERVICE_ACCOUNT')||null);const {data:vaultSa}=await db.rpc('bg_geheim',{p_naam:'GOOGLE_SERVICE_ACCOUNT'});const sa=envSa||parseAccount((vaultSa as string)||null);
 const runId=crypto.randomUUID(),day=yesterdayUtc(),started=new Date().toISOString();let rows:any[]=[];let sourceRoute='google-analytics-data-api';let primaryFailure:string|null=null;
 try{
  if(!sa)throw new Error('GOOGLE_SERVICE_ACCOUNT_ONVOLLEDIG');
  try{rows=await directGA4(sa,property,day)}catch(error){
   primaryFailure=error instanceof Error?error.message.slice(0,300):'unknown';const failureClass=classifyFailure(primaryFailure);
   if(failureClass!=='AUTH')throw new Error(`DIRECT_NON_AUTH_FAILURE:${primaryFailure}`);
   const apiKey=await secret(db,'WINDSOR_API_KEY');const accountId=(await secret(db,'WINDSOR_GA4_ACCOUNT_ID'))||DEFAULT_WINDSOR_ACCOUNT;
   if(apiKey){try{rows=await windsorGA4(apiKey,accountId,day);sourceRoute=WINDSOR_SOURCE}catch(fallbackError){const cached=await recentWindsorReadback(db);if(!cached)throw fallbackError;sourceRoute='windsor-verified-readback-cache';await db.from('bg_ga4_sync').insert({run_id:runId,afgelopen_uur:started,pages_opgehaald:Number(cached.rows_total||0),pages_bijgewerkt:Number(cached.rows_attributed||0),metingen_ingevuld:Number(cached.rows_attributed||0),status:'ok',fout:`primary AUTH failed; live Windsor API failed; reused verified Windsor readback ${cached.run_id}`,uitgevoerd_op:new Date().toISOString()});const out={ok:true,contract:FAILOVER_CONTRACT,run_id:runId,day,status:'READBACK_REUSED',source:sourceRoute,source_route:sourceRoute,primary_failure:primaryFailure,readback_run_id:cached.run_id,readback_completed_at:cached.completed_at};await writeRuntime(db,`ga4-failover:${day}:${cached.run_id}`, 'observed',out);await bewijs(true,out);return json(out,200)}}
   else {const cached=await recentWindsorReadback(db);if(!cached)throw new Error(`WINDSOR_FALLBACK_UNAVAILABLE:missing WINDSOR_API_KEY; primary=${primaryFailure}`);sourceRoute='windsor-verified-readback-cache';await db.from('bg_ga4_sync').insert({run_id:runId,afgelopen_uur:started,pages_opgehaald:Number(cached.rows_total||0),pages_bijgewerkt:Number(cached.rows_attributed||0),metingen_ingevuld:Number(cached.rows_attributed||0),status:'ok',fout:`primary AUTH failed; WINDSOR_API_KEY absent; reused verified Windsor readback ${cached.run_id}`,uitgevoerd_op:new Date().toISOString()});const out={ok:true,contract:FAILOVER_CONTRACT,run_id:runId,day,status:'READBACK_REUSED',source:sourceRoute,source_route:sourceRoute,primary_failure:primaryFailure,readback_run_id:cached.run_id,readback_completed_at:cached.completed_at};await writeRuntime(db,`ga4-failover:${day}:${cached.run_id}`, 'observed',out);await bewijs(true,out);return json(out,200)}
  }
  const headers=['date','pagePath','sessionCampaignName','sessions','activeUsers','eventCount'];const csv=[headers.join(','),...rows.map((r:any)=>headers.map(h=>csvCell(r[h])).join(','))].join('\n')+'\n';if(new TextEncoder().encode(csv).byteLength>5_000_000)throw new Error('GA4_CSV_TOO_LARGE');const csvHash=await sha256(csv);
  const {data:existing}=await db.from('bg_ga4_csv_batches').select('run_id,status,completed_at').eq('period_start',day).eq('period_end',day).eq('csv_sha256',csvHash).eq('source',sourceRoute).limit(1);
  if(existing?.length){const out={ok:true,contract:FAILOVER_CONTRACT,run_id:runId,day,status:'DUPLICATE_READBACK',source:sourceRoute,source_route:sourceRoute,primary_failure:primaryFailure,existing_run_id:existing[0].run_id,csv_sha256:csvHash};await db.from('bg_ga4_sync').insert({run_id:runId,afgelopen_uur:started,pages_opgehaald:rows.length,pages_bijgewerkt:0,metingen_ingevuld:0,status:'ok',fout:null,uitgevoerd_op:new Date().toISOString()});await writeRuntime(db,`ga4-sync:${day}:${csvHash}:${sourceRoute}`,'observed',out);await bewijs(true,out);return json(out,200)}
  const batch=await db.from('bg_ga4_csv_batches').insert({run_id:runId,period_start:day,period_end:day,csv_sha256:csvHash,csv_bytes:new TextEncoder().encode(csv).byteLength,csv_text:csv,source:sourceRoute,status:'RECEIVED',rows_total:rows.length,detail:{property,source_route:sourceRoute,primary_failure:primaryFailure,contract:FAILOVER_CONTRACT}});if(batch.error)throw new Error(`GA4_BATCH_STORE:${batch.error.message}`);
  const campaigns=[...new Set(rows.map((r:any)=>clean(r.sessionCampaignName)).filter(Boolean))] as string[];let matched:any[]=[];if(campaigns.length){const lookup=await db.from('social_posts').select('tenant_id,post_id,platform,external_post_id,source_campaign_id,topic,content_pillar,audience,funnel_stage,format,hook_type,narrative_type,emotion,cta_type,published_at').eq('tenant_id','bedrijfsgeheugen').in('source_campaign_id',campaigns);if(lookup.error)throw new Error(`CAMPAIGN_LOOKUP:${lookup.error.message}`);matched=lookup.data||[]}
  const byCampaign=new Map<string,any[]>();for(const p of matched){const k=clean(p.source_campaign_id);if(k)byCampaign.set(k,[...(byCampaign.get(k)||[]),p])}const imports:any[]=[];let unmatched=0;
  for(const r of rows){const campaign=clean(r.sessionCampaignName);if(!campaign)continue;const matches=byCampaign.get(campaign)||[];if(matches.length!==1){unmatched++;continue}const p=matches[0];imports.push({...p,campaign_key:campaign,source_campaign_id:campaign,observed_at:new Date().toISOString(),bron:sourceRoute==='google-analytics-data-api'?'ga4-direct':'ga4-windsor',source_event_id:`ga4:${day}:${p.post_id}:${r.pagePath||'/'}`,metrics:{sessions:Number(r.sessions||0),active_users:Number(r.activeUsers||0),event_count:Number(r.eventCount||0),page_path:r.pagePath||'/',ga4_date:r.date||day}})}
  let imported=0;for(let i=0;i<imports.length;i+=500){const posts=imports.slice(i,i+500);const res=await fetch(`${url}/functions/v1/bg-post-import`,{method:'POST',headers:{authorization:`Bearer ${serviceKey}`,'content-type':'application/json'},body:JSON.stringify({posts})});const body:any=await res.json().catch(()=>({}));if(!res.ok)throw new Error(`POST_IMPORT_${res.status}:${String(body?.error||'').slice(0,140)}`);imported+=Number(body?.metingen||posts.length)}
  const status=unmatched>0?'PARTIAL':'IMPORTED';await db.from('bg_ga4_csv_batches').update({status,rows_attributed:imports.length,rows_unmatched:unmatched,completed_at:new Date().toISOString(),detail:{property,source_route:sourceRoute,primary_failure:primaryFailure,campaigns:campaigns.length,matched_posts:matched.length,metrics_imported:imported,contract:FAILOVER_CONTRACT}}).eq('run_id',runId);await db.from('bg_ga4_sync').insert({run_id:runId,afgelopen_uur:started,pages_opgehaald:rows.length,pages_bijgewerkt:imports.length,metingen_ingevuld:imported,status:status==='IMPORTED'?'ok':'partial',fout:unmatched?`${unmatched} campaign rows unmatched or ambiguous`:null,uitgevoerd_op:new Date().toISOString()});const out={ok:true,contract:FAILOVER_CONTRACT,run_id:runId,day,rows:rows.length,attributed:imports.length,unmatched,imported,csv_sha256:csvHash,status,source:sourceRoute,source_route:sourceRoute,primary_failure:primaryFailure};await writeRuntime(db,`ga4-sync:${day}:${csvHash}:${sourceRoute}`,'observed',out);await bewijs(true,out);return json(out,unmatched?207:200)
 }catch(error){const detail=error instanceof Error?error.message.slice(0,500):'unknown';const failureClass=classifyFailure(detail);await db.from('bg_ga4_sync').insert({run_id:runId,afgelopen_uur:started,pages_opgehaald:0,pages_bijgewerkt:0,metingen_ingevuld:0,status:'error',fout:detail,uitgevoerd_op:new Date().toISOString()});const out={error:'ANALYTICS_SYNC_FAILED',contract:FAILOVER_CONTRACT,run_id:runId,detail,failure_class:failureClass,source_route:sourceRoute,primary_failure:primaryFailure};await writeRuntime(db,`ga4-failover-error:${runId}`,'error',out);await bewijs(false,out,failureClass);return json(out,503)}
});
