import { searchPortal, parsePortalLocation } from './core.mjs';
import { resolvePortalRoute } from './legacy-map.mjs';
import { createPortalDataAdapter } from './data-adapter.mjs';
import { createEmptyPortalState,readLegacyBrowserState } from './legacy-state.mjs';
import { buildTodayViewModel,buildHealthViewModel,buildBusinessGraphViewModel,buildImpactViewModel,buildAdminViewModel } from './view-model.mjs';
import { renderShell } from './render-shell.mjs';
import { renderToday } from './render-today.mjs';
import { renderCompany } from './render-company.mjs';
import { renderIntelligence } from './render-intelligence.mjs';
import { renderDecisions } from './render-decisions.mjs';
import { renderExecution } from './render-execution.mjs';
import { renderImpact } from './render-impact.mjs';
import { renderMemory } from './render-memory.mjs';
import { renderAdmin } from './render-admin.mjs';
const style=document.createElement('link');style.rel='stylesheet';style.href=new URL('./styles.css',window.location.href).href;document.head.append(style);
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=createEmptyPortalState();let source='empty';let adapter=null;let loadGeneration=0;let aiBusy=false;
function currentRoute(){return resolvePortalRoute(parsePortalLocation(location.hash)).route}
function renderContent(route){const top=route.split('/')[0];const renderers={today:()=>renderToday(buildTodayViewModel(state),route),company:()=>renderCompany({health:buildHealthViewModel(state),graph:buildBusinessGraphViewModel(state),route}),intelligence:()=>renderIntelligence(state,route),decisions:()=>renderDecisions(state,route),execution:()=>renderExecution(state,route),impact:()=>renderImpact(buildImpactViewModel(state),route),memory:()=>renderMemory(state,route),admin:()=>renderAdmin(buildAdminViewModel(state),route)};return(renderers[top]||renderers.today)()}
function appRender(){const route=currentRoute();$('#app').innerHTML=renderShell({activeRoute:route,user:state.user,company:state.company,lastSync:state.company?.lastSync,source,sourceMeta:state.sourceMeta,content:renderContent(route)});bindInteractions();$('#portal-main')?.focus({preventScroll:true})}
function navigate(route){location.hash=`#/${route}`}
function bindInteractions(){$$('[data-route]').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.route)));$$('[data-detail]').forEach(btn=>btn.addEventListener('click',()=>openDetail(btn.dataset.detail)));$$('[data-ai-prompt]').forEach(btn=>btn.addEventListener('click',()=>openAi(btn.dataset.aiPrompt,true)));$('#command-trigger')?.addEventListener('click',openCommand);$('#modal-backdrop')?.addEventListener('click',closeCommand);$('#cmd-input')?.addEventListener('input',renderSearch);$('#cmd-input')?.addEventListener('keydown',e=>{if(e.key==='Escape')closeCommand()});$('#ai-open')?.addEventListener('click',()=>openAi());$('#mobile-ai')?.addEventListener('click',()=>openAi());$('#ai-close')?.addEventListener('click',closeAi);$('#ai-input')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();const q=e.currentTarget.value.trim();if(q)sendPortalQuestion(q)}});$('#drawer-backdrop')?.addEventListener('click',closeDetail);$('#portal-login')?.addEventListener('click',()=>window.netlifyIdentity?.open?.());$('#profile-menu')?.addEventListener('click',()=>window.netlifyIdentity?.logout?.())}
function openCommand(){$('#command-modal')?.classList.add('open');$('#modal-backdrop')?.classList.add('open');$('#cmd-input')?.focus();renderSearch()}function closeCommand(){$('#command-modal')?.classList.remove('open');$('#modal-backdrop')?.classList.remove('open')}
function renderSearch(){const q=$('#cmd-input')?.value||'';const results=searchPortal(q,state);$('#command-results').innerHTML=results.length?results.map(x=>`<button class="command-result" data-route="${x.route}"><span><strong>${esc(x.title)}</strong><small>${esc(x.type)}</small></span><span>→</span></button>`).join(''):`<div class="empty-search">${q?'Geen resultaten':'Typ om bedrijfsbreed te zoeken.'}</div>`;$$('.command-result').forEach(btn=>btn.addEventListener('click',()=>{closeCommand();navigate(btn.dataset.route)}))}
function openAi(prompt='',submit=false){const panel=$('#ai-panel');if(!panel)return;panel.classList.add('open');panel.setAttribute('aria-hidden','false');const route=currentRoute();const label=route==='today'?'Overzicht':route.split('/').map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' / ');$('#ai-context-label').textContent=`Context: ${label}`;const input=$('#ai-input');if(prompt&&input)input.value=prompt;if(prompt&&submit)sendPortalQuestion(prompt);else input?.focus()}
function closeAi(){const p=$('#ai-panel');p?.classList.remove('open');p?.setAttribute('aria-hidden','true')}
async function sendPortalQuestion(vraag){if(aiBusy)return;const answer=$('#ai-answer');const input=$('#ai-input');const user=identityCurrent();if(!user){if(answer)answer.innerHTML='<strong>Log in om Bedrijfsgeheugen AI te gebruiken.</strong>';window.netlifyIdentity?.open?.();return}aiBusy=true;if(answer)answer.innerHTML=`<strong>${esc(vraag)}</strong><p>Bedrijfsgeheugen analyseert je beveiligde servercontext…</p>`;if(input)input.disabled=true;try{const headers=await authHeaders(user);if(!headers.authorization)throw new Error('auth');const r=await fetch('/api/portaalvraag',{method:'POST',headers:{'content-type':'application/json',...headers},credentials:'same-origin',body:JSON.stringify({vraag})});const data=await r.json().catch(()=>({}));if(!r.ok&&r.status!==404)throw new Error(data.fout||'request');if(answer)answer.innerHTML=`<strong>${esc(vraag)}</strong><p>${esc(data.antwoord||data.fout||'Geen antwoord beschikbaar.')}</p>${data.bijgewerkt?`<small>Bron bijgewerkt: ${esc(data.bijgewerkt)}</small>`:''}`;if(input)input.value=''}catch{if(answer)answer.innerHTML=`<strong>${esc(vraag)}</strong><p>Bedrijfsgeheugen AI is tijdelijk niet bereikbaar. Je bedrijfsdata is niet naar een alternatieve context doorgestuurd.</p>`}finally{aiBusy=false;if(input){input.disabled=false;input.focus()}}}
function openDetail(id){const drawer=$('#drawer');if(!drawer)return;drawer.innerHTML=`<div class="drawer-head"><div><small>Bedrijfsobject</small><h2>${esc(id)}</h2></div><button class="top-icon-btn" id="drawer-close">×</button></div><div class="detail-section"><h3>Wat is er aan de hand?</h3><p>Dit object blijft verbonden met de beschikbare broncontext, eigenaar, impact, besluiten, acties en resultaatmeting.</p></div><div class="detail-grid"><div><small>Bron</small><strong>${esc(state.sourceMeta?.label||'Niet gekoppeld')}</strong></div><div><small>Context</small><strong>${state.sourceMeta?.kind==='server'?'Server/LKG':source==='live'?'Live':'Lokaal/LKG'}</strong></div></div><div class="detail-section"><h3>Volgende stap</h3><div class="button-row"><button class="control-btn" data-ai-prompt="Analyseer impact voor ${esc(id)}">Analyseer impact</button><button class="primary-btn" data-route="decisions">Naar besluit →</button></div></div>`;drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');$('#drawer-backdrop')?.classList.add('open');$('#drawer-close')?.addEventListener('click',closeDetail);drawer.querySelectorAll('[data-route]').forEach(btn=>btn.addEventListener('click',()=>{closeDetail();navigate(btn.dataset.route)}));drawer.querySelectorAll('[data-ai-prompt]').forEach(btn=>btn.addEventListener('click',()=>{closeDetail();openAi(btn.dataset.aiPrompt,true)}))}function closeDetail(){const d=$('#drawer');d?.classList.remove('open');d?.setAttribute('aria-hidden','true');$('#drawer-backdrop')?.classList.remove('open')}
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape'){closeCommand();closeAi();closeDetail()}});window.addEventListener('hashchange',appRender);
function identityCurrent(){try{return window.netlifyIdentity?.currentUser?.()||null}catch{return null}}
function cacheKeyFor(user){const email=(user?.email||'scan').toLowerCase();return`bg.portal.state.v4.${encodeURIComponent(email)}`}
async function authHeaders(user){if(!user)return{};try{const token=await user.jwt();return token?{authorization:`Bearer ${token}`}:{}}catch{return{}}}
const timestamp=s=>Date.parse(s?.sourceMeta?.updatedAt||s?.company?.lastSync||0)||0;
async function readServerState(user){if(!user)return null;try{const headers=await authHeaders(user);if(!headers.authorization)return null;const r=await fetch('/api/portal-state',{headers:{accept:'application/json',...headers},credentials:'same-origin'});return r.ok?await r.json():null}catch{return null}}
async function writeServerState(user,local){if(!user||!local||local.sourceMeta?.kind==='empty')return false;try{const headers=await authHeaders(user);if(!headers.authorization)return false;const r=await fetch('/api/portal-state',{method:'POST',headers:{'content-type':'application/json',...headers},credentials:'same-origin',body:JSON.stringify(local)});return r.ok}catch{return false}}
async function loadBestState(user){const local=readLegacyBrowserState({storage:window.localStorage,user});if(!user)return local;const server=await readServerState(user);if(server&&(!local||timestamp(server)>=timestamp(local)))return server;if(local){await writeServerState(user,local);return await readServerState(user)||local}return server}
function makeAdapter(user,empty){return createPortalDataAdapter({storage:window.sessionStorage,cacheKey:cacheKeyFor(user),fallbackState:empty,loadLive:async()=>loadBestState(user)})}
async function loadForUser(user){const generation=++loadGeneration;const empty=createEmptyPortalState({user});const nextAdapter=makeAdapter(user,empty);const initial=await nextAdapter.loadInitial();if(generation!==loadGeneration)return;adapter=nextAdapter;state=initial.state||empty;source=initial.source||'empty';appRender();queueMicrotask(async()=>{const refreshed=await nextAdapter.refresh();if(generation!==loadGeneration)return;if(refreshed?.state&&(refreshed.changed||source!==refreshed.source)){state=refreshed.state;source=refreshed.source;appRender()}})}
function waitForIdentity(){if(!window.netlifyIdentity)return Promise.resolve(null);return new Promise(resolve=>{let done=false;const finish=u=>{if(done)return;done=true;resolve(u||null)};window.netlifyIdentity.on('init',finish);const current=identityCurrent();if(current)finish(current);setTimeout(()=>finish(identityCurrent()),500)})}
async function boot(){const user=await waitForIdentity();await loadForUser(user);if(window.netlifyIdentity){window.netlifyIdentity.on('login',u=>{window.netlifyIdentity.close();loadForUser(u)});window.netlifyIdentity.on('logout',()=>loadForUser(null))}}
boot();
