import { searchPortal, parsePortalLocation } from './core.mjs';
import { resolvePortalRoute } from './legacy-map.mjs';
import { createPortalDataAdapter } from './data-adapter.mjs';
import { createEmptyPortalState,readLegacyBrowserState } from './legacy-state.mjs';
import { choosePortalState,loadServerPortalState,saveServerPortalState } from './server-state.mjs';
import { buildTodayViewModel,buildHealthViewModel,buildBusinessGraphViewModel,buildImpactViewModel,buildAdminViewModel } from './view-model.mjs';
import { renderShell } from './render-shell.mjs';
import { renderToday } from './render-today.mjs';
import { renderCompany } from './render-company.mjs';
import { renderIntelligence } from './render-intelligence.mjs';
import { renderDecisions } from './render-decisions.mjs';
import { renderExecution } from './render-execution.mjs';
import { renderImpact } from './render-impact.mjs';
import { renderMemory } from './render-memory.mjs';
import { renderAdmin } from './render-admin.mjs';
const style=document.createElement('link');style.rel='stylesheet';style.href=new URL('./styles.css',window.location.href).href;document.head.append(style);
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=createEmptyPortalState();let source='empty';let adapter=null;let loadGeneration=0;
function currentRoute(){return resolvePortalRoute(parsePortalLocation(location.hash)).route}
function renderContent(route){const top=route.split('/')[0];const renderers={today:()=>renderToday(buildTodayViewModel(state)),company:()=>renderCompany({health:buildHealthViewModel(state),graph:buildBusinessGraphViewModel(state),route}),intelligence:()=>renderIntelligence(state,route),decisions:()=>renderDecisions(state,route),execution:()=>renderExecution(state,route),impact:()=>renderImpact(buildImpactViewModel(state),route),memory:()=>renderMemory(state,route),admin:()=>renderAdmin(buildAdminViewModel(state),route)};return(renderers[top]||renderers.today)()}
function appRender(){const route=currentRoute();$('#app').innerHTML=renderShell({activeRoute:route,user:state.user,company:state.company,lastSync:state.company?.lastSync,source,sourceMeta:state.sourceMeta,content:renderContent(route)});bindInteractions();$('#portal-main')?.focus({preventScroll:true})}
function navigate(route){location.hash=`#/${route}`}
function bindInteractions(){$$('[data-route]').forEach(btn=>btn.addEventListener('click',()=>navigate(btn.dataset.route)));$$('[data-detail]').forEach(btn=>btn.addEventListener('click',()=>openDetail(btn.dataset.detail)));$$('[data-ai-prompt]').forEach(btn=>btn.addEventListener('click',()=>openAi(btn.dataset.aiPrompt)));$('#command-trigger')?.addEventListener('click',openCommand);$('#modal-backdrop')?.addEventListener('click',closeCommand);$('#cmd-input')?.addEventListener('input',renderSearch);$('#cmd-input')?.addEventListener('keydown',e=>{if(e.key==='Escape')closeCommand()});$('#ai-open')?.addEventListener('click',()=>openAi());$('#mobile-ai')?.addEventListener('click',()=>openAi());$('#ai-close')?.addEventListener('click',closeAi);$('#drawer-backdrop')?.addEventListener('click',closeDetail);$('#portal-login')?.addEventListener('click',()=>window.netlifyIdentity?.open?.());$('#profile-menu')?.addEventListener('click',()=>window.netlifyIdentity?.logout?.())}
function openCommand(){$('#command-modal')?.classList.add('open');$('#modal-backdrop')?.classList.add('open');$('#cmd-input')?.focus();renderSearch()}function closeCommand(){$('#command-modal')?.classList.remove('open');$('#modal-backdrop')?.classList.remove('open')}
function renderSearch(){const q=$('#cmd-input')?.value||'';const results=searchPortal(q,state);$('#command-results').innerHTML=results.length?results.map(x=>`<button class="command-result" data-route="${x.route}"><span><strong>${esc(x.title)}</strong><small>${esc(x.type)}</small></span><span>→</span></button>`).join(''):`<div class="empty-search">${q?'Geen resultaten':'Typ om bedrijfsbreed te zoeken.'}</div>`;$$('.command-result').forEach(btn=>btn.addEventListener('click',()=>{closeCommand();navigate(btn.dataset.route)}))}
function openAi(prompt=''){const panel=$('#ai-panel');if(!panel)return;panel.classList.add('open');panel.setAttribute('aria-hidden','false');const route=currentRoute();const label=route==='today'?'Overzicht':route.split('/').map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' / ');$('#ai-context-label').textContent=`Context: ${label}`;if(prompt)$('#ai-answer').innerHTML=`<strong>${esc(prompt)}</strong><p>Ik gebruik alleen de bedrijfscontext die in deze sessie voor jou beschikbaar is.</p>`}function closeAi(){const p=$('#ai-panel');p?.classList.remove('open');p?.setAttribute('aria-hidden','true')}
function openDetail(id){const drawer=$('#drawer');if(!drawer)return;drawer.innerHTML=`<div class="drawer-head"><div><small>Bedrijfsobject</small><h2>${esc(id)}</h2></div><button class="top-icon-btn" id="drawer-close">×</button></div><div class="detail-section"><h3>Wat is er aan de hand?</h3><p>Dit object blijft verbonden met de beschikbare broncontext, eigenaar, impact, besluiten, acties en resultaatmeting.</p></div><div class="detail-grid"><div><small>Bron</small><strong>${esc(state.sourceMeta?.label||'Niet gekoppeld')}</strong></div><div><small>Context</small><strong>${source==='live'?'Live':'Lokaal/LKG'}</strong></div></div><div class="detail-section"><h3>Volgende stap</h3><div class="button-row"><button class="control-btn" data-ai-prompt="Analyseer impact voor ${esc(id)}">Analyseer impact</button><button class="primary-btn" data-route="decisions">Naar besluit →</button></div></div>`;drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');$('#drawer-backdrop')?.classList.add('open');$('#drawer-close')?.addEventListener('click',closeDetail);drawer.querySelectorAll('[data-route]').forEach(btn=>btn.addEventListener('click',()=>{closeDetail();navigate(btn.dataset.route)}));drawer.querySelectorAll('[data-ai-prompt]').forEach(btn=>btn.addEventListener('click',()=>{closeDetail();openAi(btn.dataset.aiPrompt)}))}function closeDetail(){const d=$('#drawer');d?.classList.remove('open');d?.setAttribute('aria-hidden','true');$('#drawer-backdrop')?.classList.remove('open')}
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape'){closeCommand();closeAi();closeDetail()}});window.addEventListener('hashchange',appRender);
function identityCurrent(){try{return window.netlifyIdentity?.currentUser?.()||null}catch{return null}}
function cacheKeyFor(user){const id=user?.id||user?.email||'scan';return`bg.portal.state.v4.${encodeURIComponent(String(id).toLowerCase())}`}
async function loadCanonicalState(user){const localState=readLegacyBrowserState({storage:window.localStorage,user});if(!user)return localState;let serverState=null;try{serverState=await loadServerPortalState({user})}catch{}const choice=choosePortalState({serverState,localState});if(choice.shouldPersist&&choice.state){try{await saveServerPortalState({user,state:choice.state})}catch{}}return choice.state}
function makeAdapter(user,empty){return createPortalDataAdapter({storage:window.sessionStorage,cacheKey:cacheKeyFor(user),fallbackState:empty,loadLive:async()=>loadCanonicalState(user)})}
async function loadForUser(user){const generation=++loadGeneration;const empty=createEmptyPortalState({user});const nextAdapter=makeAdapter(user,empty);const initial=await nextAdapter.loadInitial();if(generation!==loadGeneration)return;adapter=nextAdapter;state=initial.state||empty;source=initial.source||'empty';appRender();queueMicrotask(async()=>{const refreshed=await nextAdapter.refresh();if(generation!==loadGeneration)return;if(refreshed?.state&&(refreshed.changed||source!==refreshed.source)){state=refreshed.state;source=refreshed.source;appRender()}})}
function waitForIdentity(){if(!window.netlifyIdentity)return Promise.resolve(null);return new Promise(resolve=>{let done=false;const finish=u=>{if(done)return;done=true;resolve(u||null)};window.netlifyIdentity.on('init',finish);const current=identityCurrent();if(current)finish(current);setTimeout(()=>finish(identityCurrent()),500)})}
async function boot(){const user=await waitForIdentity();await loadForUser(user);if(window.netlifyIdentity){window.netlifyIdentity.on('login',u=>{window.netlifyIdentity.close();loadForUser(u)});window.netlifyIdentity.on('logout',()=>loadForUser(null))}}
boot();
