const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
const score5=v=>Math.round(clamp(v,0,5)*20);
const safeArray=v=>Array.isArray(v)?v:[];
const text=v=>typeof v==='string'?v.trim():'';
const LEVELS=[['sturing','Strategie en sturing'],['commercie','Commercie en klant'],['operatie','Operatie en levering'],['finance','Finance'],['mensen','Mensen en kennis'],['quality','Data'],['tech','Technologie'],['analytics','AI'],['governance','Governance']];
const level=(s,key,fallback=0)=>Number(s?.niveaus?.[key]??fallback)||0;
const avg=values=>values.length?values.reduce((a,b)=>a+b,0)/values.length:0;
const hasObjectData=o=>o&&typeof o==='object'&&Object.keys(o).length>0;
const trend=v=>Array(7).fill(Number(v)||0);
function liveTimestamp(s,scan,now){return text(s?.gewijzigd)||text(s?.updatedAt)||text(scan?.datum)||new Date(now).toISOString()}
function taskTitle(t,i){return text(t?.titel)||text(t?.title)||text(t?.naam)||`Actie ${i+1}`}
function taskStatus(t){if(t?.klaar===true||t?.done===true)return'Done';return text(t?.status)||'Open'}
function taskOwner(t){return text(t?.eigenaar)||text(t?.owner)||''}
function taskDue(t){return text(t?.deadline)||text(t?.due)||''}
function decisionTitle(d,i){return text(d?.titel)||text(d?.title)||text(d?.besluit)||`Besluit ${i+1}`}
function emptyAdmin(){return{integrations:{connected:null,healthy:null,attention:null},billing:{plan:'Niet gekoppeld',status:'Onbekend'},users:{count:null,admins:null},governance:{aiUseCases:null,autonomousAgents:null,approvalAgents:null,openIssues:null}}}
function emptySummary(){return{sections:[{id:'opportunities',label:'KANSEN',tone:'success',count:0,items:['Nog geen live kansenbron gekoppeld.']},{id:'threats',label:'BEDREIGINGEN',tone:'danger',count:0,items:['Nog geen live risicobron gekoppeld.']},{id:'trends',label:'TRENDS',tone:'primary',count:0,items:['Nog onvoldoende meetmomenten voor trends.']},{id:'conclusion',label:'CONCLUSIE',tone:'primary',score:null,delta:0,text:'Koppel bestaande portaaldata of voer de Frisse Blik uit om je live overzicht te vullen.'}]}}
export function createEmptyPortalState({user=null,now=Date.now()}={}){const stamp=new Date(now).toISOString();return{user:{name:user?.user_metadata?.full_name||user?.name||user?.email||'Gebruiker',email:user?.email||'',role:user?.role||''},company:{name:'Mijn bedrijf',health:null,delta:0,lastSync:'Nog niet gekoppeld',verifiedCoverage:0,potentialValue:0},period:'Actueel',managementSummary:emptySummary(),healthCards:[],roadmap:[],recommendedActions:[],monthlyImpact:[],activities:[],integrationStatus:{total:0,healthy:0,attention:0,disconnected:0},quickLinks:[{label:'Frisse Blik',route:'admin/frisse-blik'},{label:'Koppelingen',route:'admin/integrations'},{label:'Instellingen',route:'admin/settings'}],graph:{nodes:[],edges:[]},signals:[],decisions:[],actions:[],valueItems:[],memories:[],agents:[],audit:[],admin:emptyAdmin(),sourceMeta:{kind:'empty',live:false,updatedAt:stamp,label:'Nog geen live bedrijfsdata gekoppeld'}}}
export function hasMeaningfulLegacyState(s){return Boolean(s&&typeof s==='object'&&(Object.keys(s.niveaus||{}).length||safeArray(s.taken).length||safeArray(s.besluiten).length||safeArray(s.docs).length||safeArray(s.log).length||hasObjectData(s.fin)||hasObjectData(s.eigen)||hasObjectData(s.cijfers)))}
export function buildPortalStateFromLegacy({legacyState,scanPackage=null,user=null,lead=null,now=Date.now()}={}){const s=legacyState&&typeof legacyState==='object'?legacyState:{};const scan=scanPackage&&typeof scanPackage==='object'?scanPackage:null;if(!hasMeaningfulLegacyState(s)&&!scan)return null;
 const levels=LEVELS.map(([key,label])=>({key,label,raw:level(s,key,scan?.dimAvg?.[key]||0)})).filter(x=>x.raw>0);
 const health=levels.length?Math.round(avg(levels.map(x=>score5(x.raw)))):(Number(scan?.score)||null);
 const sorted=[...levels].sort((a,b)=>a.raw-b.raw),weakest=sorted.slice(0,2),strongest=[...sorted].sort((a,b)=>b.raw-a.raw).slice(0,2);
 const name=text(s?.eigen?.bedrijfsnaam)||text(s?.eigen?.bedrijf)||text(lead?.bedrijf)||'Mijn bedrijf';const updatedAt=liveTimestamp(s,scan,now);
 const mkCard=(id,label,value,tone)=>({id,label,value:value||null,delta:0,tone,trend:trend(value)});
 const knowledge=score5(level(s,'mensen',0)),processes=score5(level(s,'operatie',0)),dataSystems=Math.round(avg([level(s,'quality',0),level(s,'tech',0)].filter(Boolean))*20)||0,ai=score5(level(s,'analytics',0));
 const healthCards=[mkCard('bedrijfsgezondheid','Bedrijfsgezondheid',health,'blue'),mkCard('kennisborging','Kennisborging',knowledge,'purple'),mkCard('processen','Processen',processes,'green'),mkCard('data-systemen','Data & systemen',dataSystems,'violet'),mkCard('ai-volwassenheid','AI-volwassenheid',ai,'cyan')];
 const tasks=safeArray(s.taken).map((t,i)=>({id:String(t?.id||`legacy-action-${i+1}`),title:taskTitle(t,i),owner:taskOwner(t),status:taskStatus(t),executed:Boolean(t?.uitgevoerd||t?.executed||taskStatus(t)==='Done'),verified:Boolean(t?.verified),result:t?.resultaat||t?.result||null,due:taskDue(t),source:text(t?.bron)||'Bestaand portaal',progress:Number.isFinite(Number(t?.progress))?clamp(t.progress,0,100):(taskStatus(t)==='Done'?100:0)}));
 const decisions=safeArray(s.besluiten).map((d,i)=>({id:String(d?.id||`legacy-decision-${i+1}`),stage:text(d?.fase)||text(d?.status)||'Bestaand besluit',title:decisionTitle(d,i),why:text(d?.waarom)||text(d?.reason)||'',expected:text(d?.impact)||'',confidence:Number(d?.confidence)||null,risk:text(d?.risico)||'',owner:text(d?.eigenaar)||text(d?.owner)||'',options:safeArray(d?.opties)}));
 const docs=safeArray(s.docs).map((d,i)=>({type:'Document',title:text(d?.naam)||text(d?.title)||`Document ${i+1}`,excerpt:text(d?.omschrijving)||text(d?.description)||'',evidence:1,date:text(d?.datum)||''}));
 const rawLog=safeArray(s.log);const audit=rawLog.map((l,i)=>Array.isArray(l)?{time:text(l[0]),actor:text(l[1])||'Portaal',event:text(l[2])||`Wijziging ${i+1}`,status:text(l[3])||'Vastgelegd'}:{time:text(l?.tijd),actor:text(l?.actor)||'Portaal',event:text(l?.tekst)||text(l?.title)||`Wijziging ${i+1}`,status:text(l?.status)||'Vastgelegd'});const activities=audit.slice(0,10).map(x=>({type:'Actie',title:x.event,meta:[x.actor,x.time].filter(Boolean).join(' · ')}));
 const recommendations=tasks.filter(t=>t.status!=='Done').slice(0,6).map(t=>({title:t.title,priority:t.owner?'Middel':'Hoog'}));if(!recommendations.length)weakest.forEach(x=>recommendations.push({title:`Versterk ${x.label}`,priority:'Middel'}));
 const summary={sections:[{id:'opportunities',label:'KANSEN',tone:'success',count:strongest.length,items:strongest.length?strongest.map(x=>`${x.label}: ${x.raw.toFixed(1)}/5`):['Nog geen live kansenbron gekoppeld.']},{id:'threats',label:'BEDREIGINGEN',tone:'danger',count:weakest.length,items:weakest.length?weakest.map(x=>`${x.label}: ${x.raw.toFixed(1)}/5`):['Nog geen live risicobron gekoppeld.']},{id:'trends',label:'TRENDS',tone:'primary',count:0,items:['Trendberekening start zodra meerdere meetmomenten beschikbaar zijn.']},{id:'conclusion',label:'CONCLUSIE',tone:'primary',score:health,delta:0,text:health===null?'Nog onvoldoende live data voor een bedrijfsscore.':`Bedrijfsgezondheid ${health}/100 op basis van bestaande portaaldata.`}]};
 const openActions=tasks.filter(x=>x.status!=='Done').length;const graph={nodes:[{id:'knowledge',label:'Kennis',meta:`${docs.length} documenten`,legacy:true},{id:'processes',label:'Processen',meta:level(s,'operatie')?`Niveau ${level(s,'operatie').toFixed(1)}/5`:'Nog niet gemeten',legacy:true},{id:'people',label:'Mensen',meta:s.mw?`${s.mw} medewerkers`:'Nog niet gekoppeld',legacy:true},{id:'goals',label:'Doelen & strategie',meta:level(s,'sturing')?`Niveau ${level(s,'sturing').toFixed(1)}/5`:'Nog niet gemeten',legacy:true},{id:'systems',label:'Systemen',meta:'Koppelingen volgen uit live bronnen',legacy:true},{id:'data',label:'Data',meta:level(s,'quality')?`Niveau ${level(s,'quality').toFixed(1)}/5`:'Nog niet gemeten',legacy:true},{id:'actions',label:'Acties',meta:`${openActions} open acties`,legacy:true},{id:'decisions',label:'Besluiten',meta:`${decisions.length} vastgelegd`},{id:'finance',label:'Finance',meta:level(s,'finance')?`Niveau ${level(s,'finance').toFixed(1)}/5`:'Nog niet gemeten'}],edges:[['knowledge','processes'],['people','processes'],['goals','actions'],['data','actions'],['decisions','actions']]};
 return{user:{name:user?.user_metadata?.full_name||user?.name||user?.email||'Gebruiker',email:user?.email||'',role:user?.role||''},company:{name,health,delta:0,lastSync:updatedAt,verifiedCoverage:0,potentialValue:0},period:'Actueel',managementSummary:summary,healthCards,roadmap:tasks.map(x=>({title:x.title,status:x.status,progress:x.progress})),recommendedActions:recommendations,monthlyImpact:[],activities,integrationStatus:{total:0,healthy:0,attention:0,disconnected:0},quickLinks:[{label:'Kennisbank',route:'memory/knowledge'},{label:'Besluiten',route:'decisions'},{label:'Mijn taken',route:'execution'},{label:'Koppelingen',route:'admin/integrations'},{label:'Instellingen',route:'admin/settings'}],graph,signals:[],decisions,actions:tasks,valueItems:[],memories:docs,agents:[],audit,admin:emptyAdmin(),sourceMeta:{kind:'legacy-local',live:true,updatedAt,label:'Bestaande portaaldata op dit apparaat'}}
}
export function readLegacyBrowserState({storage,user,now=Date.now()}={}){if(!storage)return null;const email=text(user?.email).toLowerCase();let legacy=null,scan=null,lead=null;try{if(email){const raw=storage.getItem(`bg_portaal_${email}`);if(raw)legacy=JSON.parse(raw)}const scanRaw=storage.getItem('bg_scan_pakket');if(scanRaw)scan=JSON.parse(scanRaw);const leadRaw=storage.getItem('bg_portaal_lead');if(leadRaw)lead=JSON.parse(leadRaw)}catch{return null}return buildPortalStateFromLegacy({legacyState:legacy,scanPackage:scan,user,lead,now})}
