import { LEGACY_WORKSPACES } from './core.mjs';
import { readLegacyOffer } from './offer-state.mjs';
import { renderOffer } from './render-offer.mjs';
import { PASSPORT_STATUS, passportCoverage, publicPassportView } from './data-ai-passport.mjs';
import { buildPlatformPassport } from './data-ai-passport-platform.mjs';

const known=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const show=v=>known(v)?String(v):'—';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const groups=()=>[...new Set(LEGACY_WORKSPACES.map(x=>x.group))].map(group=>({group,items:LEGACY_WORKSPACES.filter(x=>x.group===group)}));
function currentOffer(){try{const slug=new URLSearchParams(globalThis.location?.search||'').get('klant')||'';const user=globalThis.netlifyIdentity?.currentUser?.()||null;return readLegacyOffer({storage:globalThis.sessionStorage,extraStorage:globalThis.localStorage,slug,user,allowDemo:true})}catch{return null}}

const STATUS_META=Object.freeze({
 [PASSPORT_STATUS.VERIFIED]:{label:'Geverifieerd',cls:'verified-pill',style:''},
 [PASSPORT_STATUS.CONFIGURED]:{label:'Geconfigureerd',cls:'count-badge',style:''},
 [PASSPORT_STATUS.NEEDS_EVIDENCE]:{label:'Nog te bewijzen',cls:'count-badge',style:'background:#fff7ed;color:#9a3412;border-color:#fdba74'},
});
function statusPill(status){const meta=STATUS_META[status]||STATUS_META[PASSPORT_STATUS.NEEDS_EVIDENCE];return`<span class="${meta.cls}"${meta.style?` style="${meta.style}"`:''}>${meta.label}</span>`}
function passportRow(label,value,status,detail=''){return`<div class="card" style="padding:14px 16px;display:grid;grid-template-columns:minmax(150px,.75fr) minmax(180px,1.35fr) auto;gap:14px;align-items:center"><div><small>${esc(label)}</small></div><div><strong>${esc(value||'Niet vastgesteld')}</strong>${detail?`<p style="margin:.25rem 0 0">${esc(detail)}</p>`:''}</div>${statusPill(status)}</div>`}
function renderDataAiPassport(vm){
 const passport=buildPlatformPassport({company:vm.company,user:vm.user,persisted:vm.dataAiPassport});
 const view=publicPassportView(passport);const coverage=passportCoverage(passport);const make=view.automation?.find(x=>x.provider==='Make');const ai=view.aiSystems?.[0];const storage=view.storage?.[0];const transfer=view.transfers?.[0];const checkedAt=make?.evidence?.[0]?.checkedAt||null;
 return`<section class="page"><div class="page-head"><div><span class="eyebrow">Data · AI · Soevereiniteit</span><h1>Data & AI Passport</h1><p>Geen generieke compliance-score, maar bewijs per verwerking. Alleen wat aantoonbaar is wordt groen.</p></div><div>${statusPill(coverage.needsEvidence===0&&coverage.total>0?PASSPORT_STATUS.VERIFIED:PASSPORT_STATUS.NEEDS_EVIDENCE)}</div></div>
 <div class="card governance-card"><div class="card-head"><div><h2>Bewijsdekking</h2><p>${coverage.verified} van ${coverage.total} controlepunten zijn met evidence geverifieerd.</p></div><strong style="font-size:2rem">${coverage.percentage}%</strong></div><div class="governance-stats"><div><b>${coverage.verified}</b><span>Geverifieerd</span></div><div><b>${coverage.configured}</b><span>Geconfigureerd</span></div><div><b>${coverage.needsEvidence}</b><span>Nog te bewijzen</span></div><div><b>${coverage.total}</b><span>Controlepunten</span></div></div></div>
 <div style="display:grid;gap:10px;margin-top:14px">
 ${passportRow('Data-eigenaar',view.ownership?.owner,view.ownership?.status,'Eigendom en privacyrol worden per verwerking contractueel vastgelegd.')}
 ${passportRow('Automatiseringslaag',make?.provider,make?.status,make?`Zone ${make.zone||'onbekend'} · runtime ${make.state||'onbekend'}`:'Geen orchestration evidence beschikbaar.')}
 ${passportRow('Opslagland',storage?.country||storage?.region,storage?.status,'Een geverifieerde provider bewijst niet automatisch het opslagland.')}
 ${passportRow('AI-provider & model',ai?[ai.provider,ai.model].filter(Boolean).join(' · '):null,ai?.status,'Per use-case registreren; geen platformbrede AI Act-vink.')}
 ${passportRow('AI-verwerkingsregio',ai?.processingRegion,ai?.processingRegionStatus,'De locatie van AI-verwerking krijgt eigen infrastructuur- of providerbewijs.')}
 ${passportRow('EU AI Act-classificatie',ai?.aiAct?.riskClass&&ai.aiAct.riskClass!=='unclassified'?`${ai.aiAct.riskClass}${ai.aiAct.role?` · rol ${ai.aiAct.role}`:''}`:null,ai?.aiAct?.status,'Classificatie en verplichtingen worden per AI-use-case vastgesteld.')}
 ${passportRow('Menselijke controle',ai?.humanOversight===true?'Ja':ai?.humanOversight===false?'Nee':typeof ai?.humanOversight==='string'?ai.humanOversight:null,ai?.humanOversightStatus,'Human oversight wordt per proces vastgelegd en afzonderlijk bewezen.')}
 ${passportRow('Modeltraining met klantdata',ai?.trainingUse===false?'Nee':ai?.trainingUse===true?'Ja':null,ai?.trainingUseStatus,'Providerbewijs is onvoldoende: traininggebruik vereist eigen contract- of configuratiebewijs.')}
 ${passportRow('Doorgifte buiten EER',transfer?.destination,transfer?.status,'Bestemming en transfermechanisme moeten aantoonbaar zijn.')}
 ${passportRow('Alle data binnen EU/EER',view.assertions?.allDataWithinEer?.value===true?'Ja':view.assertions?.allDataWithinEer?.value===false?'Nee':null,view.assertions?.allDataWithinEer?.status,'Geen EU/EER-claim zolang opslag én verwerking niet volledig bewezen zijn.')}
 </div>
 <div class="card" style="margin-top:14px"><div class="card-head"><div><h2>Wat het passport afdwingt</h2><p>Iedere nieuwe bron, workflow, agent of AI-use-case krijgt dezelfde evidencevelden.</p></div></div><div class="admin-grid"><div class="admin-card"><strong>Wie</strong><p>Eigenaar, controller, processor en subprocessor.</p></div><div class="admin-card"><strong>Waar</strong><p>Opslagland, verwerkingsregio en grensoverschrijdende doorgifte.</p></div><div class="admin-card"><strong>Welke AI</strong><p>Provider, model, doel, AI Act-rol/risicoklasse en human oversight.</p></div><div class="admin-card"><strong>Bewijs</strong><p>Bron, gecontroleerd op, retentie, export en verwijderpad.</p></div></div></div>
 <div class="card" style="margin-top:14px"><div class="card-head"><div><h2>Laatst gecontroleerde harde waarheid</h2><p>De Make-omgeving is aantoonbaar <strong>eu1.make.com</strong>. Dat bewijst de Make-zone, maar niet automatisch waar alle klantdata of AI-verwerking plaatsvindt. De twee gecontroleerde portal-scenario’s stonden bij de laatste inspectie gepauzeerd.${checkedAt?` Bewijs vastgelegd op ${esc(checkedAt)}.`:''}</p></div>${statusPill(make?.status)}</div></div>
 </section>`
}

export function renderAdmin(vm,route='admin'){
 if(route==='admin/legacy/offerte')return renderOffer(currentOffer());
 if(route==='admin/data-ai-passport')return renderDataAiPassport(vm);
 const sub=route.split('/')[1]||'overview';const a=vm.admin||{};const integrations=a.integrations||{};const billing=a.billing||{};const users=a.users||{};const governance=a.governance||{};const hasIntegrationMetrics=known(integrations.connected)||known(integrations.attention);const hasUserMetrics=known(users.count)||known(users.admins);const hasGovernanceMetrics=known(governance.aiUseCases)||known(governance.openIssues)||known(governance.autonomousAgents)||known(governance.approvalAgents);const cards=[['integrations','Koppelingen & systemen',hasIntegrationMetrics?`${show(integrations.connected)} gekoppeld · ${show(integrations.attention)} aandacht`:'Status nog niet gekoppeld'],['integration-builder','Koppeling bouwen','Nieuwe databron veilig aansluiten'],['data-ai-passport','Data & AI Passport','Waar data staat, welke AI werkt en welk bewijs beschikbaar is'],['billing','Facturen & abonnement',billing.plan&&billing.plan!=='Niet gekoppeld'?`${billing.plan} · ${billing.status||'Onbekend'}`:'Abonnementsbron nog niet gekoppeld'],['users','Organisatie & gebruikers',hasUserMetrics?`${show(users.count)} gebruikers · ${show(users.admins)} beheerders`:'Gebruikersbron nog niet gekoppeld'],['permissions','Rollen & rechten','RBAC + ABAC + objectrechten'],['ai-governance','AI Governance',hasGovernanceMetrics?`${show(governance.aiUseCases)} use-cases · ${show(governance.openIssues)} issues`:'Governance-register nog niet gekoppeld'],['agents','Agents & automatisering',vm.agents.length?`${vm.agents.length} agentrollen`:'Agentstatus nog niet gekoppeld'],['audit','Audit','Volledige wijzigingshistorie'],['settings','Instellingen','Organisatie, notificaties en voorkeuren']];
 return`<section class="page"><div class="page-head"><div><h1>Beheer</h1><p>Bronnen, gebruikers, rechten, AI-governance, agents en abonnement centraal beheerd.</p></div></div><div class="admin-grid">${cards.map(([id,title,desc])=>`<button class="card admin-card ${sub===id?'is-selected':''}" data-route="admin/${id}"><span class="admin-icon">◌</span><strong>${title}</strong><p>${desc}</p><span>Open →</span></button>`).join('')}</div><div class="card governance-card"><div class="card-head"><h2>AI Governance</h2><span class="verified-pill">Governance-model beschikbaar</span></div>${hasGovernanceMetrics?`<div class="governance-stats"><div><b>${show(governance.aiUseCases)}</b><span>AI use-cases</span></div><div><b>${show(governance.autonomousAgents)}</b><span>Autonome agents</span></div><div><b>${show(governance.approvalAgents)}</b><span>Approval vereist</span></div><div><b>${show(governance.openIssues)}</b><span>Open issues</span></div></div>`:'<div class="empty-search">Nog geen live AI-governance-register gekoppeld. Er worden geen aantallen verondersteld.</div>'}</div><section class="legacy-workspaces card"><div class="card-head"><div><h2>Bestaande werkruimtes</h2><p>Alle functies uit het vorige klantportaal blijven bereikbaar terwijl ze native worden gemigreerd.</p></div><span class="count-badge">${LEGACY_WORKSPACES.length} behouden</span></div><div class="legacy-workspace-groups">${groups().map(g=>`<div class="legacy-workspace-group"><strong>${g.group}</strong><div>${g.items.map(item=>`<button data-route="${item.route}">${item.label}<span>→</span></button>`).join('')}</div></div>`).join('')}</div></section></section>`
}
