const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const known=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
const arr=v=>Array.isArray(v)?v:[];
const delta=n=>`${Number(n)>=0?'▲':'▼'} ${Math.abs(Number(n)||0)} deze maand`;
const empty=label=>`<div class="empty-search">${esc(label)}</div>`;

const KPI_ORDER=[
  ['health','Bedrijfsgezondheid','♡'],['knowledge','Kennisborging','▤'],['process','Processen','⚙'],['data','Data & systemen','◫'],['ai','AI-volwassenheid','✦']
];
const PORTAL_MODULES=[
  ['Inzicht','today'],['Vergelijken','intelligence'],['Denken','decisions'],['Overname','company/legacy/dd'],['Doen','execution'],['Strategy DNA','company/legacy/dna'],['Canvas','decisions/legacy/canvassen'],['Roadmap','execution/roadmap'],['Documenten','memory']
];
const CAPABILITIES=['Begrijpt context','Legt verbanden','Vat samen','Prioriteert','Adviseert','Simuleert','Leert'];

function findKpi(cards,id,label){const lower=label.toLowerCase();return cards.find(c=>String(c.id||'').toLowerCase()===id)||cards.find(c=>String(c.label||'').toLowerCase()===lower)||cards.find(c=>String(c.label||'').toLowerCase().includes(lower.split(' ')[0]));}
function kpiCard(c,label,icon){const has=c&&known(c.value);return`<button class="ref-kpi" data-detail="health-${esc(c?.id||label)}"><div class="ref-kpi-title"><span>${icon}</span><strong>${esc(label)}</strong></div><div class="ref-kpi-value"><b>${has?esc(c.value):'—'}</b><small>${has?'/100':''}</small></div><div class="ref-kpi-delta ${Number(c?.delta)>=0?'positive':'negative'}">${has?delta(c.delta):'Nog niet gemeten'}</div></button>`}
function sourceIcon(id=''){if(/system|data|dashboard/i.test(id))return'◫';if(/process/i.test(id))return'↗';if(/people|mens/i.test(id))return'♙';if(/knowledge|document|kennis/i.test(id))return'▤';return'◌'}
function evidenceOf(a){return a?.evidenceId||a?.evidence_id||a?.evidence?.id||''}
function verifiedAgent(a){return ['verified','completed'].includes(String(a?.status||'').toLowerCase())&&Boolean(evidenceOf(a))&&!a?.recoveryObligation&&!a?.recovery_obligation}
function blockedAgent(a){return ['blocked','failed','recovering','paused','disabled'].includes(String(a?.status||'').toLowerCase())||Boolean(a?.recoveryObligation||a?.recovery_obligation)}
function runtime(vm){
  const agents=arr(vm.agents), blocked=agents.some(blockedAgent), verified=agents.filter(verifiedAgent);
  const explicit=vm.runtimeFlow&&typeof vm.runtimeFlow==='object'?vm.runtimeFlow:null;
  const source=explicit?.source||explicit?.sourceId||null, module=explicit?.module||explicit?.moduleId||null;
  const capabilities=arr(explicit?.capabilities).map(String);
  const evidence=verified.map(evidenceOf).filter(Boolean);
  const sourceActive=!blocked&&verified.length>0&&Boolean(source)&&arr(vm.graph?.nodes).some(n=>String(n.id)===String(source));
  const portalActive=sourceActive&&Boolean(module)&&PORTAL_MODULES.some(([label,route])=>String(module)===route||String(module)===label);
  return{active:portalActive,sourceActive,portalActive,blocked,verified,source,module,capabilities,evidence};
}
function sourceCards(vm,rt){const nodes=arr(vm.graph?.nodes).slice(0,8);if(!nodes.length)return empty('Nog geen bronnen gekoppeld.');return nodes.map(n=>{const selected=rt.sourceActive&&String(rt.source)===String(n.id);return`<button class="brain-source ${selected?'active':rt.sourceActive?'dim':''}" data-detail="graph-${esc(n.id)}"><span class="source-icon">${sourceIcon(`${n.id} ${n.label}`)}</span><span><strong>${esc(n.label)}</strong><small>${esc(n.meta||'Gekoppelde bedrijfsbron')}</small></span></button>`}).join('')}
function moduleCards(rt){return PORTAL_MODULES.map(([label,route],i)=>{const selected=rt.portalActive&&(String(rt.module)===route||String(rt.module)===label);return`<button class="brain-module ${selected?'active':rt.portalActive?'dim':''}" data-route="${route}"><span>${['◉','▥','✦','⌂','✓','◎','▦','↗','▤'][i]}</span><strong>${label}</strong></button>`}).join('')}
function brainCockpit(vm){
  const rt=runtime(vm), evidence=rt.evidence.join(','), used=new Set(rt.capabilities);
  return`<section class="brain-card card" data-flow-active="${rt.active?'true':'false'}" data-source-flow-active="${rt.sourceActive?'true':'false'}" data-portal-flow-active="${rt.portalActive?'true':'false'}" data-runtime-blocked="${rt.blocked?'true':'false'}" data-evidence="${esc(evidence)}"><div class="brain-head"><div><h2>Het brein van je bedrijf</h2><p>Van informatie naar inzicht — je bedrijfsgeheugen in werking.</p></div><div class="runtime-badge ${rt.blocked?'blocked':rt.active?'verified':'idle'}">${rt.blocked?'Herstel nodig':rt.active?'Geverifieerde runtime':'Geen actieve flow'}</div></div><div class="brain-layout"><div class="brain-sources"><div class="brain-column-title">1. Bronnen</div>${sourceCards(vm,rt)}</div><div class="brain-core-wrap"><div class="brain-column-title">2. Het bedrijfsgeheugen</div><div class="brain-capabilities">${CAPABILITIES.map(x=>`<span class="${rt.active&&used.has(x)?'on':''}"><i>✦</i>${x}</span>`).join('')}</div><div class="brain-core-visual"><div class="brain-glow"></div><div class="brain-glyph">🧠</div><div class="brain-layer brain-ai"><strong>AI Brain</strong><small>begrijpen · redeneren · adviseren</small></div><div class="brain-layer brain-datahub"><strong>Datahub</strong><small>verbinden · verrijken · structureren</small></div><div class="brain-layer brain-powerhouse"><strong>Powerhouse</strong><small>detectie · uitvoering · verificatie · learning</small></div>${rt.sourceActive?`<div class="flow-pulse in"></div>`:''}${rt.portalActive?`<div class="flow-pulse out"></div>`:''}</div><div class="powerhouse-status">${rt.blocked?'<span class="status blocked">Flow gestopt: herstelverplichting open</span>':rt.active?`<span class="status verified">✓ Execution evidence ${esc(evidence)}</span>`:rt.sourceActive?'<span class="status idle">Bron verwerkt; nog geen bewezen portaalbestemming</span>':'<span class="status idle">Geen complete runtime-evidence — daarom geen end-to-end stroom</span>'}</div></div><div class="brain-modules"><div class="brain-column-title">3. Klantenportaal</div><div class="brain-module-grid">${moduleCards(rt)}</div></div></div><div class="brain-flow-summary"><div><strong>Nu in flow</strong><span>${rt.sourceActive?esc(rt.source):'Geen bewezen bron actief'}</span></div><div><strong>Het Bedrijfsgeheugen doet</strong><span>${rt.blocked?'Herstellen voordat uitvoering doorgaat':rt.sourceActive?'Verwerken via Datahub, AI Brain en Powerhouse':'Wacht op bron + execution evidence'}</span></div><div><strong>Resultaat</strong><span>${rt.portalActive?esc(rt.module):'Geen bewezen portaaloutput'}</span></div></div></section>`}
function summaryCounts(vm){const sections=arr(vm.managementSummary?.sections);const get=(ids)=>sections.find(s=>ids.includes(s.id));return{op:get(['opportunities','kansen']),th:get(['threats','risks','bedreigingen']),tr:get(['trends'])}}
function managementCard(vm){const s=summaryCounts(vm);return`<section class="card rail-card ref-summary"><div class="card-head"><h2>AI Management Summary</h2><button class="text-link" data-ai-prompt="Vat de actuele managementsignalen samen">✦</button></div><p>Gebaseerd op de bedrijfsdata en signalen die daadwerkelijk zijn gekoppeld.</p><div class="summary-pills"><button data-route="intelligence/kansen"><span class="green-dot"></span><strong>Kansen</strong><b>${Number(s.op?.count)||arr(s.op?.items).length||0}</b></button><button data-route="intelligence/risks"><span class="orange-dot"></span><strong>Risico’s</strong><b>${Number(s.th?.count)||arr(s.th?.items).length||0}</b></button><button data-route="intelligence/trends"><span class="blue-dot"></span><strong>Trends</strong><b>${Number(s.tr?.count)||arr(s.tr?.items).length||0}</b></button></div></section>`}
function recommendationCard(vm){const actions=arr(vm.recommendedActions).slice(0,5);return`<section class="card rail-card"><div class="card-head"><h2>Aanbevelingen</h2><span class="count-badge">${actions.length}</span></div>${actions.length?`<div class="recommendation-list">${actions.map(a=>`<button data-route="execution"><span>↗</span><strong>${esc(a.title)}</strong><small>${esc(a.priority||'Open')}</small></button>`).join('')}</div>`:empty('Nog geen aanbevelingen uit de huidige broncontext.')}</section>`}
function quickCard(vm){const q=arr(vm.quickLinks);const fallback=[['Koppelingen','admin/integrations'],['Mijn taken','execution'],['Kennisbank','memory'],['Rapportages','impact']];const links=q.length?q:fallback.map(([label,route])=>({label,route}));return`<section class="card rail-card"><div class="card-head"><h2>Snelle links</h2></div><div class="ref-quick-grid">${links.slice(0,8).map(x=>`<button data-route="${esc(x.route)}"><span>◌</span><small>${esc(x.label)}</small></button>`).join('')}</div></section>`}
function roadmapCard(vm){const items=arr(vm.roadmap).slice(0,4);return`<section class="card lower-card"><div class="card-head"><h2>Roadmap &amp; voortgang</h2><button class="text-link" data-route="execution/roadmap">Bekijk roadmap →</button></div>${items.length?items.map(x=>`<button class="ref-roadmap-row" data-route="execution/roadmap"><span><strong>${esc(x.title)}</strong><small>${esc(x.status||'Open')}</small></span><i><b style="width:${Math.max(0,Math.min(100,Number(x.progress)||0))}%"></b></i><em>${Math.max(0,Math.min(100,Number(x.progress)||0))}%</em></button>`).join(''):empty('Nog geen roadmap-items gekoppeld.')}</section>`}
function opportunitiesCard(vm){const s=summaryCounts(vm);const opp=arr(s.op?.items).slice(0,2), threats=arr(s.th?.items).slice(0,2);return`<section class="card lower-card"><div class="card-head"><h2>Kansen &amp; bedreigingen</h2><button class="text-link" data-route="intelligence">Bekijk alles →</button></div><div class="opportunity-stack">${opp.map(x=>`<button data-route="intelligence/kansen"><span class="green-dot"></span><strong>${esc(x)}</strong><small>Kans</small></button>`).join('')}${threats.map(x=>`<button data-route="intelligence/risks"><span class="orange-dot"></span><strong>${esc(x)}</strong><small>Risico</small></button>`).join('')}${!opp.length&&!threats.length?empty('Nog geen geverifieerde kansen of bedreigingen.'):''}</div></section>`}
function impactCard(vm){const items=arr(vm.monthlyImpact).slice(0,4);return`<section class="card lower-card"><div class="card-head"><h2>Impact overzicht</h2><button class="text-link" data-route="impact">Impact Engine →</button></div>${items.length?`<div class="ref-impact-list">${items.map(x=>`<div><span>◌</span><small>${esc(x.label)}</small><strong>${esc(x.value)}</strong><em>${esc(x.delta||'')}</em></div>`).join('')}</div>`:empty('Nog geen geverifieerde impactmetingen.')}</section>`}
function activitiesCard(vm){const items=arr(vm.activities).slice(0,6);return`<section class="card recent-card"><div class="card-head"><h2>Recente activiteiten</h2><button class="text-link" data-route="memory">Bekijk alles →</button></div>${items.length?`<div class="ref-activities">${items.map(x=>`<div><span class="activity-icon">${x.type==='Data'?'▱':x.type==='Proces'?'↗':x.type==='Actie'?'✓':'▤'}</span><span><strong>${esc(x.title)}</strong><small>${esc(x.meta||'')}</small></span><em>${esc(x.type||'Activiteit')}</em></div>`).join('')}</div>`:empty('Nog geen activiteiten vastgelegd.')}</section>`}
function renderConclusion(vm){const sections=arr(vm.managementSummary?.sections);const conclusion=sections.find(x=>x.id==='conclusion');return`<section class="page"><div class="page-head"><div><h1>De eindconclusie</h1><p>De bestaande eindconclusie, native opgebouwd uit de actuele bedrijfscontext.</p></div><button class="control-btn" data-ai-prompt="Onderbouw de eindconclusie met kansen, bedreigingen, trends en bewijs">✦ Analyseer conclusie</button></div><section class="card"><div class="card-head"><h2>Managementconclusie</h2></div>${conclusion?`<p>${esc(conclusion.text||'')}</p>`:empty('Nog geen geverifieerde eindconclusie beschikbaar.')}</section></section>`}

export function renderToday(vm,route='today'){
  if(route==='today/legacy/eindconclusie')return renderConclusion(vm);
  const cards=arr(vm.healthCards);
  return`<section class="page reference-dashboard"><div class="page-head ref-page-head"><div><h1>Welkom terug, ${esc((vm.user?.name||'Gebruiker').split(' ')[0])}</h1><p>Grip op je bedrijf. Ruimte om te groeien.</p></div><div class="head-controls"><button class="control-btn" id="command-trigger">⌕ Zoek in kennis, processen, data, systemen…</button><button class="control-btn primary-outline" data-ai-prompt="Geef me het belangrijkste inzicht voor vandaag">✦ Vraag het Bedrijfsgeheugen AI</button><button class="control-btn">Periode: ${esc(vm.period||'Actueel')}　▣</button></div></div><section class="reference-kpis">${KPI_ORDER.map(([id,label,icon])=>kpiCard(findKpi(cards,id,label),label,icon)).join('')}</section><div class="reference-main-grid"><div class="reference-center">${brainCockpit(vm)}</div><aside class="reference-right-rail">${managementCard(vm)}${recommendationCard(vm)}${quickCard(vm)}</aside></div><section class="reference-lower-grid">${roadmapCard(vm)}${opportunitiesCard(vm)}${impactCard(vm)}</section>${activitiesCard(vm)}</section>`;
}
