-- Powerhouse invariant: public schema does not imply public data access.
-- Every ordinary or partitioned table in public must have RLS enabled.

create table if not exists public.powerhouse_security_guard_events (
  id bigint generated by default as identity primary key,
  detected_at timestamptz not null default now(),
  source text not null check (source in ('ddl', 'scheduled_scan', 'manual_verify')),
  table_schema text not null,
  table_name text not null,
  action text not null,
  details jsonb not null default '{}'::jsonb
);

alter table public.powerhouse_security_guard_events enable row level security;
revoke all on table public.powerhouse_security_guard_events from anon, authenticated;

create or replace function public.powerhouse_public_rls_on_create()
returns event_trigger
language plpgsql
security definer
set search_path = pg_catalog
as $function$
declare
  r record;
begin
  for r in
    select c.oid, n.nspname as schema_name, c.relname as table_name
    from pg_event_trigger_ddl_commands() d
    join pg_class c on c.oid = d.objid
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relkind in ('r', 'p')
  loop
    execute format('alter table %I.%I enable row level security', r.schema_name, r.table_name);

    insert into public.powerhouse_security_guard_events
      (source, table_schema, table_name, action, details)
    values
      ('ddl', r.schema_name, r.table_name, 'enable_rls', jsonb_build_object('tag', tg_tag));
  end loop;
end;
$function$;

-- Keep both explicit EXECUTE revocation and ALL revocation: the former is the generic
-- security-contract marker; the latter is the dedicated regression guard's fail-closed proof.
revoke execute on function public.powerhouse_public_rls_on_create() from public, anon, authenticated;
revoke all on function public.powerhouse_public_rls_on_create() from public, anon, authenticated;

drop event trigger if exists powerhouse_public_rls_default_deny;
create event trigger powerhouse_public_rls_default_deny
  on ddl_command_end
  when tag in ('CREATE TABLE', 'CREATE TABLE AS')
  execute function public.powerhouse_public_rls_on_create();

create or replace function public.powerhouse_public_rls_guard_scan()
returns integer
language plpgsql
security definer
set search_path = pg_catalog
as $function$
declare
  r record;
  fixed_count integer := 0;
begin
  for r in
    select n.nspname as schema_name, c.relname as table_name
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relkind in ('r', 'p')
      and not c.relrowsecurity
  loop
    execute format('alter table %I.%I enable row level security', r.schema_name, r.table_name);

    insert into public.powerhouse_security_guard_events
      (source, table_schema, table_name, action)
    values
      ('scheduled_scan', r.schema_name, r.table_name, 'enable_rls');

    fixed_count := fixed_count + 1;
  end loop;

  return fixed_count;
end;
$function$;

revoke execute on function public.powerhouse_public_rls_guard_scan() from public, anon, authenticated;
revoke all on function public.powerhouse_public_rls_guard_scan() from public, anon, authenticated;

-- Replace any previous job deterministically before scheduling the reconciler.
do $do$
declare
  existing_job bigint;
begin
  select jobid
    into existing_job
  from cron.job
  where jobname = 'powerhouse-public-rls-guard-scan'
  limit 1;

  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
end;
$do$;

select cron.schedule(
  'powerhouse-public-rls-guard-scan',
  '*/5 * * * *',
  $cron$select public.powerhouse_public_rls_guard_scan();$cron$
);

-- Repair any pre-existing drift immediately during installation.
select public.powerhouse_public_rls_guard_scan();

-- Transactional install probe: a new public table must become RLS-on at DDL end.
create table public.__powerhouse_rls_guard_probe (
  id bigint generated by default as identity primary key
);
alter table public.__powerhouse_rls_guard_probe enable row level security;
revoke all on table public.__powerhouse_rls_guard_probe from anon, authenticated;

do $probe$
begin
  if not exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = '__powerhouse_rls_guard_probe'
      and c.relrowsecurity
  ) then
    raise exception 'powerhouse public RLS guard probe failed';
  end if;
end;
$probe$;

drop table public.__powerhouse_rls_guard_probe;
