-- Powerhouse AI Model Intelligence Registry v1
create table if not exists public.powerhouse_ai_model_registry (
  model_id text primary key,
  provider_id text not null,
  display_name text not null,
  lifecycle text not null check (lifecycle in ('active','preview','legacy','deprecated','retired','unknown')),
  modality jsonb not null default '{}'::jsonb,
  capabilities jsonb not null default '{}'::jsonb,
  pricing jsonb not null default '{}'::jsonb,
  limits jsonb not null default '{}'::jsonb,
  governance jsonb not null default '{}'::jsonb,
  best_for text[] not null default '{}',
  avoid_for text[] not null default '{}',
  official_source text not null,
  verified_at timestamptz,
  source_hash text,
  freshness_state text not null default 'unknown' check (freshness_state in ('fresh','stale','unknown')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.powerhouse_ai_model_registry enable row level security;
revoke all on public.powerhouse_ai_model_registry from anon, authenticated;
grant select,insert,update,delete on public.powerhouse_ai_model_registry to service_role;

create table if not exists public.powerhouse_ai_model_advisor_events (
  event_id bigint generated always as identity primary key,
  occurred_at timestamptz not null default now(),
  anonymous_session text,
  goal_text text,
  priority text,
  eu_requirement text,
  recommended_model_ids text[] not null default '{}',
  estimated_monthly_cost_usd numeric,
  lead_id text,
  outcome_state text not null default 'advice',
  metadata jsonb not null default '{}'::jsonb
);
alter table public.powerhouse_ai_model_advisor_events enable row level security;
revoke all on public.powerhouse_ai_model_advisor_events from anon, authenticated;
grant select,insert,update,delete on public.powerhouse_ai_model_advisor_events to service_role;

create table if not exists public.powerhouse_ai_model_source_watch (
  source_id text primary key,
  provider_id text not null,
  models_url text not null,
  pricing_url text,
  governance_urls jsonb not null default '[]'::jsonb,
  last_checked_at timestamptz,
  last_changed_at timestamptz,
  last_hash text,
  status text not null default 'candidate',
  metadata jsonb not null default '{}'::jsonb
);
alter table public.powerhouse_ai_model_source_watch enable row level security;
revoke all on public.powerhouse_ai_model_source_watch from anon, authenticated;
grant select,insert,update,delete on public.powerhouse_ai_model_source_watch to service_role;

insert into public.powerhouse_ai_model_source_watch(source_id,provider_id,models_url,pricing_url,governance_urls,status)
values
('openai-official','openai','https://platform.openai.com/docs/models','https://openai.com/api/pricing/','["https://openai.com/enterprise-privacy/"]'::jsonb,'active'),
('anthropic-official','anthropic','https://docs.anthropic.com/en/docs/about-claude/models','https://docs.anthropic.com/en/docs/about-claude/pricing','["https://privacy.anthropic.com/"]'::jsonb,'active'),
('google-gemini-official','google','https://ai.google.dev/gemini-api/docs/models','https://ai.google.dev/gemini-api/docs/pricing','["https://ai.google.dev/gemini-api/terms"]'::jsonb,'active'),
('mistral-official','mistral','https://docs.mistral.ai/getting-started/models/models_overview/','https://mistral.ai/pricing','["https://mistral.ai/terms/"]'::jsonb,'active'),
('deepseek-official','deepseek','https://api-docs.deepseek.com/quick_start/pricing','https://api-docs.deepseek.com/quick_start/pricing','[]'::jsonb,'active')
on conflict (source_id) do update set
  models_url=excluded.models_url, pricing_url=excluded.pricing_url,
  governance_urls=excluded.governance_urls, status=excluded.status;

comment on table public.powerhouse_ai_model_registry is
'Canonical Powerhouse registry for model capability/pricing/governance intelligence. Unknown governance fields remain unknown; never infer green suitability.';
comment on table public.powerhouse_ai_model_advisor_events is
'Closed-loop events for AI Model Advisor: goal -> recommendation -> lead/order outcome.';
comment on table public.powerhouse_ai_model_source_watch is
'Official provider source registry for freshness/change detection.';

create or replace view public.powerhouse_ai_model_freshness_v1
with (security_invoker=true) as
select model_id,provider_id,display_name,lifecycle,verified_at,
       case
         when verified_at is null then 'unknown'
         when verified_at < now()-interval '14 days' then 'stale'
         else 'fresh'
       end as computed_freshness_state,
       official_source
from public.powerhouse_ai_model_registry;

revoke all on public.powerhouse_ai_model_freshness_v1 from anon, authenticated;
grant select on public.powerhouse_ai_model_freshness_v1 to service_role;


insert into public.powerhouse_ai_model_registry(
  model_id,provider_id,display_name,lifecycle,modality,capabilities,pricing,limits,governance,best_for,avoid_for,official_source,verified_at,freshness_state
) values
('gpt-5.6-sol','openai','GPT-5.6 Sol','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":6,"coding":10,"writing":9,"analysis":10,"speed":6,"cost_efficiency":5,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":4,"cached_input_usd_mtok":0.4,"output_usd_mtok":20,"pricing_note":null}'::jsonb,'{"context_tokens":1050000,"max_output_tokens":128000}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"no-by-default-api","jurisdiction":"United States"}'::jsonb,ARRAY['complex reasoning','coding','architecture','research','professional knowledge work']::text[],ARRAY['simple bulk classification when cost dominates']::text[],'https://developers.openai.com/api/docs/models/gpt-5.6-sol','2026-09-30'::timestamptz,'fresh'),
('gpt-5.6-terra','openai','GPT-5.6 Terra','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":6,"coding":9,"writing":9,"analysis":9,"speed":7,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":2,"cached_input_usd_mtok":0.2,"output_usd_mtok":12,"pricing_note":null}'::jsonb,'{"context_tokens":1050000,"max_output_tokens":128000}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"no-by-default-api","jurisdiction":"United States"}'::jsonb,ARRAY['balanced enterprise work','coding','document analysis','agents']::text[],ARRAY['ultra-low-cost high-volume classification']::text[],'https://developers.openai.com/api/docs/models/gpt-5.6-terra','2026-09-30'::timestamptz,'fresh'),
('gpt-5.6-luna','openai','GPT-5.6 Luna','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":6,"coding":8,"writing":8,"analysis":8,"speed":9,"cost_efficiency":10,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":0.2,"cached_input_usd_mtok":0.02,"output_usd_mtok":1.2,"pricing_note":null}'::jsonb,'{"context_tokens":1050000,"max_output_tokens":128000}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"no-by-default-api","jurisdiction":"United States"}'::jsonb,ARRAY['high-volume workflows','classification','summaries','cost-sensitive agents']::text[],ARRAY['highest-stakes complex reasoning where quality dominates']::text[],'https://developers.openai.com/api/docs/models/gpt-5.6-luna','2026-09-30'::timestamptz,'fresh'),
('claude-opus-5','anthropic','Claude Opus 5','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":10,"coding":10,"writing":10,"analysis":10,"speed":5,"cost_efficiency":4,"vision":true,"audio":false,"image_generation":false,"web":"tool-dependent","tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"contract-dependent","jurisdiction":"United States"}'::jsonb,ARRAY['deep reasoning','long-form analysis','complex coding','agents']::text[],ARRAY['simple bulk jobs where latency/cost dominate']::text[],'https://docs.anthropic.com/en/docs/about-claude/model-deprecations','2026-09-30'::timestamptz,'fresh'),
('claude-sonnet-5','anthropic','Claude Sonnet 5','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":9,"coding":10,"writing":10,"analysis":9,"speed":7,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":"tool-dependent","tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"contract-dependent","jurisdiction":"United States"}'::jsonb,ARRAY['coding','writing','analysis','general business work']::text[],ARRAY['lowest-cost batch classification']::text[],'https://docs.anthropic.com/en/docs/about-claude/model-deprecations','2026-09-30'::timestamptz,'fresh'),
('claude-fable-5','anthropic','Claude Fable 5','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":8,"writing":9,"analysis":8,"speed":8,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":"tool-dependent","tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"contract-dependent","jurisdiction":"United States"}'::jsonb,ARRAY['general business tasks','content','moderate reasoning']::text[],ARRAY['specialized multimodal production']::text[],'https://docs.anthropic.com/en/docs/about-claude/model-deprecations','2026-09-30'::timestamptz,'fresh'),
('claude-opus-4-8','anthropic','Claude Opus 4.8','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":9,"coding":9,"writing":9,"analysis":9,"speed":5,"cost_efficiency":4,"vision":true,"audio":false,"image_generation":false,"web":"tool-dependent","tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"contract-dependent","jurisdiction":"United States"}'::jsonb,ARRAY['complex reasoning','coding']::text[],ARRAY['cost-sensitive batch']::text[],'https://docs.anthropic.com/en/docs/about-claude/model-deprecations','2026-09-30'::timestamptz,'fresh'),
('claude-sonnet-4-6','anthropic','Claude Sonnet 4.6','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":9,"writing":9,"analysis":8,"speed":7,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":"tool-dependent","tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"contract-dependent","jurisdiction":"United States"}'::jsonb,ARRAY['coding','business writing','agents']::text[],ARRAY['heavy multimodal generation']::text[],'https://docs.anthropic.com/en/docs/about-claude/model-deprecations','2026-09-30'::timestamptz,'fresh'),
('claude-haiku-4-5-20251001','anthropic','Claude Haiku 4.5','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":6,"coding":7,"writing":7,"analysis":6,"speed":10,"cost_efficiency":9,"vision":true,"audio":false,"image_generation":false,"web":"tool-dependent","tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"contract-dependent","jurisdiction":"United States"}'::jsonb,ARRAY['fast classification','routing','summaries','high volume']::text[],ARRAY['highest-complexity reasoning']::text[],'https://docs.anthropic.com/en/docs/about-claude/model-deprecations','2026-09-30'::timestamptz,'fresh'),
('gemini-embedding-2-preview','google','Gemini Embedding 2 Preview','preview','{"vision":false,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":1,"coding":1,"writing":1,"analysis":5,"speed":9,"cost_efficiency":9,"vision":false,"audio":false,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider/service-dependent","training_on_api_data":"tier-dependent","jurisdiction":"United States"}'::jsonb,ARRAY['semantic search','RAG','classification','embeddings']::text[],ARRAY['generation','chat']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-embedding-001','google','Gemini Embedding 001','active','{"vision":false,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":1,"coding":1,"writing":1,"analysis":4,"speed":9,"cost_efficiency":9,"vision":false,"audio":false,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider/service-dependent","training_on_api_data":"tier-dependent","jurisdiction":"United States"}'::jsonb,ARRAY['semantic search','RAG','classification']::text[],ARRAY['generation']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-robotics-er-2-preview','google','Gemini Robotics ER 2 Preview','preview','{"vision":true,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":9,"coding":5,"writing":5,"analysis":9,"speed":6,"cost_efficiency":6,"vision":true,"audio":true,"image_generation":false,"web":false,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":1,"cached_input_usd_mtok":null,"output_usd_mtok":5,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider/service-dependent","training_on_api_data":"tier-dependent","jurisdiction":"United States"}'::jsonb,ARRAY['robotics','spatial reasoning','video understanding','embodied agents']::text[],ARRAY['ordinary office writing']::text[],'https://ai.google.dev/gemini-api/docs/pricing','2026-09-30'::timestamptz,'fresh'),
('deepseek-flash','deepseek','DeepSeek V4.1 Flash','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":7,"coding":8,"writing":7,"analysis":8,"speed":9,"cost_efficiency":10,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":0.3,"cached_input_usd_mtok":0.006,"output_usd_mtok":1.2,"pricing_note":"peak pricing; off-peak is lower"}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"no-verified-eu-residency","data_residency":"verify-before-business-use","training_on_api_data":"verify-policy","jurisdiction":"China"}'::jsonb,ARRAY['cost-sensitive reasoning','coding','high-volume inference']::text[],ARRAY['regulated/sensitive data without governance review']::text[],'https://api-docs.deepseek.com/quick_start/pricing','2026-09-30'::timestamptz,'fresh'),
('deepseek-v4-pro','deepseek','DeepSeek V4 Pro','active','{"vision":false,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":9,"coding":9,"writing":8,"analysis":9,"speed":6,"cost_efficiency":8,"vision":false,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":1.32,"cached_input_usd_mtok":0.044,"output_usd_mtok":3.96,"pricing_note":"peak pricing; off-peak is lower"}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"no-verified-eu-residency","data_residency":"verify-before-business-use","training_on_api_data":"verify-policy","jurisdiction":"China"}'::jsonb,ARRAY['agents','complex reasoning','coding']::text[],ARRAY['regulated/sensitive data without governance review']::text[],'https://api-docs.deepseek.com/quick_start/pricing','2026-09-30'::timestamptz,'fresh'),
('mistral-small-4','mistral','Mistral Small 4','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":7,"coding":7,"writing":8,"analysis":7,"speed":9,"cost_efficiency":10,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":"model-dependent","self_host":"model-dependent"}'::jsonb,'{"input_usd_mtok":0.15,"cached_input_usd_mtok":null,"output_usd_mtok":0.6,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"strong-eu-provider-fit","data_residency":"deployment-option-dependent","training_on_api_data":"contract-dependent","jurisdiction":"France / EU"}'::jsonb,ARRAY['EU-oriented workloads','cost-sensitive business tasks','multilingual work']::text[],ARRAY['use cases requiring maximum frontier reasoning']::text[],'https://docs.mistral.ai/getting-started/models/models_overview/','2026-09-30'::timestamptz,'fresh'),
('gpt-6-astra','openai','GPT-6 Astra','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":10,"coding":10,"writing":10,"analysis":10,"speed":5,"cost_efficiency":3,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":10,"cached_input_usd_mtok":null,"output_usd_mtok":50,"pricing_note":null}'::jsonb,'{"context_tokens":1050000,"max_output_tokens":128000}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"EU availability requires current eligibility check","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['hardest end-to-end work','complex reasoning','coding','agents']::text[],ARRAY['routine high-volume work']::text[],'https://developers.openai.com/api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gpt-6.1-sol','openai','GPT-6.1 Sol','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":10,"coding":10,"writing":9,"analysis":10,"speed":7,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":2,"cached_input_usd_mtok":0.1,"output_usd_mtok":10,"pricing_note":null}'::jsonb,'{"context_tokens":1050000,"max_output_tokens":128000}'::jsonb,'{"eu_option":"EU data residency supported","data_residency":"US and EU residency documented; regional processing premium may apply","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['complex coding','computer use','professional work','agents']::text[],ARRAY['ultra-cheap classification']::text[],'https://developers.openai.com/api/docs/models/gpt-6.1-sol','2026-09-30'::timestamptz,'fresh'),
('gpt-6-sol','openai','GPT-6 Sol','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":9,"coding":10,"writing":9,"analysis":9,"speed":7,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":2,"cached_input_usd_mtok":0.2,"output_usd_mtok":10,"pricing_note":null}'::jsonb,'{"context_tokens":1050000,"max_output_tokens":128000}'::jsonb,'{"eu_option":"EU data residency supported","data_residency":"EU residency documented for Standard/Flex/Batch","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['coding','agentic workflows','complex professional work']::text[],ARRAY['lowest-cost bulk']::text[],'https://developers.openai.com/api/docs/models/gpt-6-sol','2026-09-30'::timestamptz,'fresh'),
('gpt-6-luna','openai','GPT-6 Luna','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":8,"writing":8,"analysis":8,"speed":10,"cost_efficiency":10,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":0.1,"cached_input_usd_mtok":0.01,"output_usd_mtok":0.5,"pricing_note":null}'::jsonb,'{"context_tokens":1050000,"max_output_tokens":128000}'::jsonb,'{"eu_option":"EU data residency supported","data_residency":"EU residency documented for Standard/Flex/Batch","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['focused high-volume tasks','classification','summaries','routing']::text[],ARRAY['hardest end-to-end reasoning']::text[],'https://developers.openai.com/api/docs/models/gpt-6-luna','2026-09-30'::timestamptz,'fresh'),
('gpt-image-2.5-sunburst','openai','GPT-Image-2.5 Sunburst','active','{"vision":true,"audio":false,"image_generation":true}'::jsonb,'{"reasoning":2,"coding":1,"writing":2,"analysis":3,"speed":6,"cost_efficiency":5,"vision":true,"audio":false,"image_generation":true,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['highest-quality image generation','image editing']::text[],ARRAY['text reasoning']::text[],'https://developers.openai.com/api/docs/models/all','2026-09-30'::timestamptz,'fresh'),
('gpt-image-2.5-flare','openai','GPT-Image-2.5 Flare','active','{"vision":true,"audio":false,"image_generation":true}'::jsonb,'{"reasoning":2,"coding":1,"writing":2,"analysis":2,"speed":9,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":true,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['fast image generation','high-volume image editing']::text[],ARRAY['text reasoning']::text[],'https://developers.openai.com/api/docs/models/all','2026-09-30'::timestamptz,'fresh'),
('gpt-image-2','openai','GPT-Image-2','active','{"vision":true,"audio":false,"image_generation":true}'::jsonb,'{"reasoning":2,"coding":1,"writing":2,"analysis":2,"speed":7,"cost_efficiency":6,"vision":true,"audio":false,"image_generation":true,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['image generation','image editing']::text[],ARRAY['text reasoning']::text[],'https://developers.openai.com/api/docs/models/gpt-image-2','2026-09-30'::timestamptz,'fresh'),
('gpt-live-1','openai','GPT-Live 1','active','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":7,"coding":4,"writing":7,"analysis":7,"speed":10,"cost_efficiency":5,"vision":false,"audio":true,"image_generation":false,"web":false,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['natural realtime voice conversations','voice agents']::text[],ARRAY['offline batch text']::text[],'https://developers.openai.com/api/docs/models/all','2026-09-30'::timestamptz,'fresh'),
('gpt-realtime-2.1','openai','GPT-Realtime-2.1','active','{"vision":true,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":6,"writing":7,"analysis":8,"speed":10,"cost_efficiency":5,"vision":true,"audio":true,"image_generation":false,"web":false,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['realtime reasoning','voice with tools']::text[],ARRAY['cheap batch processing']::text[],'https://developers.openai.com/api/docs/models/all','2026-09-30'::timestamptz,'fresh'),
('gpt-realtime-2.1-mini','openai','GPT-Realtime-2.1 Mini','active','{"vision":true,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":7,"coding":5,"writing":6,"analysis":7,"speed":10,"cost_efficiency":8,"vision":true,"audio":true,"image_generation":false,"web":false,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['cost-sensitive realtime agents']::text[],ARRAY['maximum reasoning']::text[],'https://developers.openai.com/api/docs/models/all','2026-09-30'::timestamptz,'fresh'),
('gpt-realtime-translate','openai','GPT-Realtime-Translate','active','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":5,"analysis":4,"speed":10,"cost_efficiency":7,"vision":false,"audio":true,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['streaming speech-to-speech translation']::text[],ARRAY['general reasoning']::text[],'https://developers.openai.com/api/docs/models/all','2026-09-30'::timestamptz,'fresh'),
('gpt-live-transcribe','openai','GPT-Live-Transcribe','active','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":2,"coding":1,"writing":2,"analysis":4,"speed":10,"cost_efficiency":7,"vision":false,"audio":true,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['realtime transcription']::text[],ARRAY['general generation']::text[],'https://developers.openai.com/api/docs/models/all','2026-09-30'::timestamptz,'fresh'),
('text-embedding-3-large','openai','Text Embedding 3 Large','active','{"vision":false,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":1,"coding":2,"writing":1,"analysis":6,"speed":9,"cost_efficiency":7,"vision":false,"audio":false,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['embeddings','semantic search','RAG']::text[],ARRAY['generation']::text[],'https://developers.openai.com/api/docs/models/text-embedding-3-large','2026-09-30'::timestamptz,'fresh'),
('text-embedding-3-small','openai','Text Embedding 3 Small','active','{"vision":false,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":1,"coding":2,"writing":1,"analysis":5,"speed":10,"cost_efficiency":9,"vision":false,"audio":false,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['cost-sensitive embeddings','semantic search']::text[],ARRAY['generation']::text[],'https://developers.openai.com/api/docs/models/all','2026-09-30'::timestamptz,'fresh'),
('omni-moderation-latest','openai','Omni Moderation','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":2,"coding":1,"writing":1,"analysis":5,"speed":10,"cost_efficiency":10,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":0,"cached_input_usd_mtok":null,"output_usd_mtok":0,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['text moderation','image moderation','safety classification']::text[],ARRAY['generation']::text[],'https://developers.openai.com/api/docs/guides/moderation','2026-09-30'::timestamptz,'fresh'),
('gpt-oss-120b','openai','gpt-oss-120b','active','{"vision":false,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":8,"writing":8,"analysis":8,"speed":6,"cost_efficiency":8,"vision":false,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":true,"self_host":true}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"self-hostable","data_residency":"controlled by chosen deployment when self-hosted","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['self-hosted reasoning','data sovereignty','H100-class deployment']::text[],ARRAY['managed multimodal workloads']::text[],'https://developers.openai.com/api/docs/models/all','2026-09-30'::timestamptz,'fresh'),
('gpt-oss-20b','openai','gpt-oss-20b','active','{"vision":false,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":6,"coding":7,"writing":7,"analysis":7,"speed":9,"cost_efficiency":9,"vision":false,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":true,"self_host":true}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"self-hostable","data_residency":"controlled by chosen deployment when self-hosted","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['low-latency self-hosting','edge/private inference']::text[],ARRAY['maximum frontier quality']::text[],'https://developers.openai.com/api/docs/models/all','2026-09-30'::timestamptz,'fresh'),
('gemini-3.8-flash','google','Gemini 3.8 Flash','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":9,"coding":9,"writing":6,"analysis":9,"speed":9,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['complex coding, agents, enterprise workflows']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.8-live','google','Gemini 3.8 Live','active','{"vision":true,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":7,"writing":6,"analysis":8,"speed":10,"cost_efficiency":7,"vision":true,"audio":true,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['low-latency voice agents']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.8-live-extended-thinking','google','Gemini 3.8 Live Extended Thinking','active','{"vision":true,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":9,"coding":8,"writing":6,"analysis":9,"speed":9,"cost_efficiency":7,"vision":true,"audio":true,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['reasoning voice agents']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.8-flash-tts','google','Gemini 3.8 Flash TTS','active','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":6,"analysis":3,"speed":9,"cost_efficiency":7,"vision":false,"audio":true,"image_generation":false,"web":true,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['studio-grade text to speech']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.8-flash-lite-tts','google','Gemini 3.8 Flash-Lite TTS','active','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":2,"coding":1,"writing":6,"analysis":2,"speed":10,"cost_efficiency":10,"vision":false,"audio":true,"image_generation":false,"web":true,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['high-volume text to speech']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.7-flash','google','Gemini 3.7 Flash','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":9,"writing":6,"analysis":8,"speed":9,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['coding and agentic workflows']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.6-flash','google','Gemini 3.6 Flash','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":8,"writing":6,"analysis":8,"speed":9,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['general multimodal and agents']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.5-flash','google','Gemini 3.5 Flash','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":9,"writing":6,"analysis":8,"speed":9,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":1000000,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['agentic coding at scale']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.5-flash-lite','google','Gemini 3.5 Flash-Lite','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":6,"coding":7,"writing":6,"analysis":6,"speed":10,"cost_efficiency":10,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":1000000,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['high-throughput low-cost tasks']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.1-flash-lite','google','Gemini 3.1 Flash-Lite','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":6,"coding":6,"writing":6,"analysis":6,"speed":10,"cost_efficiency":10,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['cost-efficient high-volume work']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.1-flash-image','google','Nano Banana 2','active','{"vision":true,"audio":false,"image_generation":true}'::jsonb,'{"reasoning":3,"coding":1,"writing":6,"analysis":3,"speed":9,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":true,"web":true,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['image generation and editing']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.1-flash-lite-image','google','Nano Banana 2 Lite','active','{"vision":true,"audio":false,"image_generation":true}'::jsonb,'{"reasoning":2,"coding":1,"writing":6,"analysis":2,"speed":10,"cost_efficiency":10,"vision":true,"audio":false,"image_generation":true,"web":true,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['low-latency image generation']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3-pro-image','google','Nano Banana Pro','active','{"vision":true,"audio":false,"image_generation":true}'::jsonb,'{"reasoning":4,"coding":1,"writing":6,"analysis":4,"speed":7,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":true,"web":true,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['highest-quality image generation']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.1-pro-preview','google','Gemini 3.1 Pro','preview','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":10,"coding":10,"writing":6,"analysis":10,"speed":6,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['complex multimodal reasoning and coding']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3-flash-preview','google','Gemini 3 Flash','preview','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":9,"writing":6,"analysis":8,"speed":9,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['fast frontier general work']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.5-live-translate-preview','google','Gemini 3.5 Live Translate','preview','{"vision":true,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":4,"coding":1,"writing":6,"analysis":4,"speed":10,"cost_efficiency":7,"vision":true,"audio":true,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['realtime speech translation']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.1-flash-live-preview','google','Gemini 3.1 Flash Live','preview','{"vision":true,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":7,"coding":5,"writing":6,"analysis":7,"speed":9,"cost_efficiency":7,"vision":true,"audio":true,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['legacy realtime voice']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.1-flash-tts-preview','google','Gemini 3.1 Flash TTS','preview','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":6,"analysis":3,"speed":9,"cost_efficiency":7,"vision":false,"audio":true,"image_generation":false,"web":true,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['speech generation']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-omni-1.1-flash','google','Gemini Omni Flash','preview','{"vision":true,"audio":true,"image_generation":true}'::jsonb,'{"reasoning":5,"coding":2,"writing":6,"analysis":5,"speed":8,"cost_efficiency":7,"vision":true,"audio":true,"image_generation":true,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['video generation and editing']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-3.5-transcribe','google','Gemini 3.5 Transcribe','active','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":6,"analysis":3,"speed":10,"cost_efficiency":7,"vision":false,"audio":true,"image_generation":false,"web":true,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['speech to text and diarization']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-2.5-pro','google','Gemini 2.5 Pro','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":9,"writing":6,"analysis":8,"speed":6,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['complex reasoning and coding']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-2.5-flash-native-audio-preview-12-2025','google','Gemini 2.5 Flash Live','preview','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":7,"coding":5,"writing":6,"analysis":7,"speed":9,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['bidirectional voice and video agents']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-2.5-flash-preview-tts','google','Gemini 2.5 Flash TTS','preview','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":6,"analysis":3,"speed":9,"cost_efficiency":7,"vision":false,"audio":true,"image_generation":false,"web":true,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['low-latency text to speech']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-2.5-pro-preview-tts','google','Gemini 2.5 Pro TTS','preview','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":6,"analysis":3,"speed":7,"cost_efficiency":7,"vision":false,"audio":true,"image_generation":false,"web":true,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['high-fidelity speech synthesis']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('gemini-robotics-er-1.6-preview','google','Gemini Robotics ER 1.6','preview','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":9,"coding":4,"writing":6,"analysis":9,"speed":6,"cost_efficiency":7,"vision":true,"audio":false,"image_generation":false,"web":true,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"provider-dependent","data_residency":"provider-plan-and-region-dependent","training_on_api_data":"verify-current-contract","jurisdiction":"United States"}'::jsonb,ARRAY['embodied spatial reasoning']::text[],ARRAY['verify exact pricing and residency for production use']::text[],'https://ai.google.dev/gemini-api/docs/models','2026-09-30'::timestamptz,'fresh'),
('mistral-medium-3.5','mistral','Mistral Medium 3.5','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":9,"coding":9,"writing":7,"analysis":9,"speed":7,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":256000,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['frontier multimodal agents and coding']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('mistral-large-3','mistral','Mistral Large 3','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":9,"coding":9,"writing":7,"analysis":9,"speed":6,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":true,"self_host":true}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":256000,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['open-weight general multimodal work']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('ministral-3-14b','mistral','Ministral 3 14B','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":7,"coding":7,"writing":7,"analysis":7,"speed":8,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":true,"self_host":true}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":256000,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['edge/private text and vision']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('ministral-3-8b','mistral','Ministral 3 8B','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":6,"coding":6,"writing":7,"analysis":6,"speed":9,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":true,"self_host":true}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":256000,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['lightweight edge inference']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('ministral-3-3b','mistral','Ministral 3 3B','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":5,"coding":5,"writing":7,"analysis":5,"speed":10,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":true,"self_host":true}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":256000,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['small edge inference']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('mistral-ocr-4.1','mistral','Mistral OCR 4.1','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":7,"analysis":3,"speed":9,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['OCR and document structure']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('mistral-ocr-4.0','mistral','Mistral OCR 4.0','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":7,"analysis":3,"speed":9,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['OCR and document structure']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('mistral-ocr-3','mistral','Mistral OCR 3','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":7,"analysis":3,"speed":8,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['document OCR']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('voxtral-tts','mistral','Voxtral TTS','active','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":7,"analysis":3,"speed":8,"cost_efficiency":8,"vision":false,"audio":true,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['multilingual text to speech and voice cloning']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('voxtral-mini-transcribe-2','mistral','Voxtral Mini Transcribe 2','active','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":7,"analysis":3,"speed":10,"cost_efficiency":8,"vision":false,"audio":true,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['speech transcription']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('voxtral-mini-transcribe-realtime','mistral','Voxtral Mini Transcribe Realtime','active','{"vision":false,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":7,"analysis":3,"speed":10,"cost_efficiency":8,"vision":false,"audio":true,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['realtime transcription']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('voxtral-small','mistral','Voxtral Small','active','{"vision":true,"audio":true,"image_generation":false}'::jsonb,'{"reasoning":6,"coding":4,"writing":7,"analysis":6,"speed":8,"cost_efficiency":8,"vision":true,"audio":true,"image_generation":false,"web":false,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['audio input instruction following']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('codestral','mistral','Codestral','active','{"vision":false,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":6,"coding":10,"writing":7,"analysis":6,"speed":9,"cost_efficiency":8,"vision":false,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":128000,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['code completion and generation']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('codestral-embed','mistral','Codestral Embed','active','{"vision":false,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":2,"coding":4,"writing":7,"analysis":2,"speed":10,"cost_efficiency":8,"vision":false,"audio":false,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['code embeddings and retrieval']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('mistral-embed','mistral','Mistral Embed','active','{"vision":false,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":2,"coding":3,"writing":7,"analysis":2,"speed":10,"cost_efficiency":8,"vision":false,"audio":false,"image_generation":false,"web":false,"tools":false,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['text/code embeddings and retrieval']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('shieldstral-1','mistral','Shieldstral 1.0','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":3,"coding":1,"writing":7,"analysis":3,"speed":10,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":true,"self_host":true}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['multimodal moderation']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('mistral-moderation-2','mistral','Mistral Moderation 2','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":4,"coding":1,"writing":7,"analysis":4,"speed":10,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":false,"self_host":false}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":128000,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['moderation and jailbreak detection']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('leanstral-1.5','mistral','Leanstral 1.5','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":10,"writing":7,"analysis":8,"speed":6,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":true,"self_host":true}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":null,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['Lean 4 formal proofs']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('zai-glm-5.3','mistral','Z.ai GLM 5.3 via Mistral','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":8,"writing":7,"analysis":8,"speed":7,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":true,"self_host":true}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":1000000,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['open-weight text and long context']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh'),
('zai-glm-5.2','mistral','Z.ai GLM 5.2 via Mistral','active','{"vision":true,"audio":false,"image_generation":false}'::jsonb,'{"reasoning":8,"coding":8,"writing":7,"analysis":8,"speed":7,"cost_efficiency":8,"vision":true,"audio":false,"image_generation":false,"web":false,"tools":true,"open_weights":true,"self_host":true}'::jsonb,'{"input_usd_mtok":null,"cached_input_usd_mtok":null,"output_usd_mtok":null,"pricing_note":null}'::jsonb,'{"context_tokens":1000000,"max_output_tokens":null}'::jsonb,'{"eu_option":"EU provider; deployment option still must be verified","data_residency":"deployment/contract dependent; verify exact region","training_on_api_data":"verify-current-contract","jurisdiction":"France / EU"}'::jsonb,ARRAY['open-weight text and long context']::text[],ARRAY['verify exact pricing/hosting for chosen endpoint']::text[],'https://docs.mistral.ai/models','2026-09-30'::timestamptz,'fresh')
on conflict (model_id) do update set
  provider_id=excluded.provider_id,
  display_name=excluded.display_name,
  lifecycle=excluded.lifecycle,
  modality=excluded.modality,
  capabilities=excluded.capabilities,
  pricing=excluded.pricing,
  limits=excluded.limits,
  governance=excluded.governance,
  best_for=excluded.best_for,
  avoid_for=excluded.avoid_for,
  official_source=excluded.official_source,
  verified_at=excluded.verified_at,
  freshness_state=excluded.freshness_state,
  updated_at=now();
