-- Fingerprint: powerhouse-structure-hygiene-v2
-- Goal: resolve the two remaining no-primary-key advisor findings using existing natural/runtime keys.
-- No synthetic identity columns and no business behavior changes.

-- content_publication_obligations already enforces this exact non-null business key as UNIQUE.
-- Promote the same key to the table primary key so identity and constraint semantics are explicit.
alter table public.content_publication_obligations
  drop constraint if exists content_publication_obligatio_tenant_id_publication_date_ch_key;

alter table public.content_publication_obligations
  add constraint content_publication_obligations_pkey
  primary key (tenant_id, publication_date, channel);

-- The revenue snapshot is fully replaced by powerhouse_refresh_revenue_intelligence_snapshot_v1().
-- revenue_rank is generated by row_number() on every refresh, so it is the existing unique/non-null row identity.
alter table public.powerhouse_revenue_command_center_snapshot_v1
  alter column revenue_rank set not null;

alter table public.powerhouse_revenue_command_center_snapshot_v1
  add constraint powerhouse_revenue_command_center_snapshot_v1_pkey
  primary key (revenue_rank);
