revoke all on public.powerhouse_action_evidence_maturity_v1 from service_role;
grant select on public.powerhouse_action_evidence_maturity_v1 to service_role;
revoke all on public.powerhouse_commercial_next_best_action_v5 from service_role;
grant select on public.powerhouse_commercial_next_best_action_v5 to service_role;
