-- Governed Composio/Groq artifact fallback for content generation.
-- Fingerprint: linkedin-composio-chain-provider-isolation-v1
-- The fallback generates artifacts only. Publication authority remains separate.

INSERT INTO public.brain_ai_governance_registry (
  tenant_id,use_case_id,name,provider,model_id,model_revision,purpose,owner_id,
  lifecycle_status,risk_class,human_oversight,data_categories,prohibited_data_categories,
  retention_policy,transparency_required,impact_assessment_required,approved,
  approval_evidence_ids,evidence_ids,last_reviewed_at,next_review_at,
  inference_platform,training_use,processing_scope,cross_border_transfer,
  subprocessors,transfer_safeguard,provider_evidence_urls,updated_at
) VALUES (
  'canonical',
  'supabase-bg-composio-content-fallback-v1',
  'BG Native Content Generator Composio Fallback',
  'Composio/Groq',
  'openai/gpt-oss-120b',
  NULL,
  'Fallback artifact generation only when the governed primary content provider is unavailable; never publishes directly.',
  'content-growth',
  'ACTIVE',
  'LIMITED',
  'Generates only the existing six-field content artifact. All personal-truth, company-tracking, identity, publication-authority, dedupe and exact LinkedIn URN readback gates remain mandatory before publication.',
  ARRAY['business_context','content_context']::text[],
  ARRAY['secrets','raw_private_payloads','raw_dm_bodies','personal_contact_data']::text[],
  'Store only the generated artifact plus provider/model/fallback reason; do not retain prompts, raw private payloads or credentials.',
  true,
  true,
  true,
  ARRAY['decision:user-2026-09-25-composio-chain']::text[],
  ARRAY[
    'fingerprint:linkedin-composio-chain-provider-isolation-v1',
    'incident:anthropic-credit-exhaustion-2026-09-25',
    'dry-run:composio-groq-openai-gpt-oss-120b-json-artifact'
  ]::text[],
  now(),
  now() + interval '30 days',
  'Composio Search / Groq',
  'UNKNOWN',
  'GLOBAL',
  'POSSIBLE_OUTSIDE_EEA',
  ARRAY['Composio','Groq']::text[],
  'Provider routing is restricted to approved content context; prohibited data categories remain blocked and publication stays behind canonical gates.',
  ARRAY[]::text[],
  now()
)
ON CONFLICT (tenant_id,use_case_id) DO UPDATE SET
  name=EXCLUDED.name,
  provider=EXCLUDED.provider,
  model_id=EXCLUDED.model_id,
  model_revision=EXCLUDED.model_revision,
  purpose=EXCLUDED.purpose,
  owner_id=EXCLUDED.owner_id,
  lifecycle_status=EXCLUDED.lifecycle_status,
  risk_class=EXCLUDED.risk_class,
  human_oversight=EXCLUDED.human_oversight,
  data_categories=EXCLUDED.data_categories,
  prohibited_data_categories=EXCLUDED.prohibited_data_categories,
  retention_policy=EXCLUDED.retention_policy,
  transparency_required=EXCLUDED.transparency_required,
  impact_assessment_required=EXCLUDED.impact_assessment_required,
  approved=EXCLUDED.approved,
  approval_evidence_ids=EXCLUDED.approval_evidence_ids,
  evidence_ids=EXCLUDED.evidence_ids,
  last_reviewed_at=EXCLUDED.last_reviewed_at,
  next_review_at=EXCLUDED.next_review_at,
  inference_platform=EXCLUDED.inference_platform,
  training_use=EXCLUDED.training_use,
  processing_scope=EXCLUDED.processing_scope,
  cross_border_transfer=EXCLUDED.cross_border_transfer,
  subprocessors=EXCLUDED.subprocessors,
  transfer_safeguard=EXCLUDED.transfer_safeguard,
  provider_evidence_urls=EXCLUDED.provider_evidence_urls,
  updated_at=now();
