-- Source Universe expansion v1
-- Extends catalog coverage only. No connection/live claim is inferred from catalog presence.

insert into public.powerhouse_source_catalog_v1
(source_key,domain_key,source_type,provider,label,authority_tier,geography,acquisition_mode,official_url,refresh_cadence,availability_state,description)
values
('iso','STANDARDS_GOVERNANCE','standards-body','ISO','ISO standards','OFFICIAL','GLOBAL','official-web','https://www.iso.org/standards.html',interval '7 days','CATALOGUED','International management, security, quality, AI and continuity standards'),
('nen','STANDARDS_GOVERNANCE','standards-body','NEN','NEN standards','OFFICIAL','NL','official-web','https://www.nen.nl/',interval '7 days','CATALOGUED','Dutch and European standards'),
('cencenelec','STANDARDS_GOVERNANCE','standards-body','CEN-CENELEC','European standards','OFFICIAL','EU','official-web','https://www.cencenelec.eu/',interval '7 days','CATALOGUED','European standardisation developments'),
('pbl','ENERGY_CLIMATE','research-authority','PBL','Planbureau voor de Leefomgeving','OFFICIAL','NL','official-web','https://www.pbl.nl/',interval '7 days','CATALOGUED','Climate, energy, environment and spatial planning'),
('rivm','HEALTH_DISRUPTION','health-authority','RIVM','RIVM','OFFICIAL','NL','official-web','https://www.rivm.nl/',interval '6 hours','CATALOGUED','Public health and societal disruption signals'),
('who','HEALTH_DISRUPTION','health-authority','WHO','World Health Organization','OFFICIAL','GLOBAL','official-web','https://www.who.int/',interval '6 hours','CATALOGUED','Global health and outbreak signals'),
('iea','ENERGY_CLIMATE','energy-authority','IEA','International Energy Agency','OFFICIAL','GLOBAL','official-web','https://www.iea.org/',interval '1 day','CATALOGUED','Energy markets, transition and security'),
('entsoe','ENERGY_CLIMATE','grid-data','ENTSO-E','ENTSO-E Transparency Platform','PRIMARY','EU','official-web','https://transparency.entsoe.eu/',interval '1 hour','CATALOGUED','European electricity-system and grid data'),
('world-bank','ECONOMY_FINANCE','multilateral-data','World Bank','World Bank','OFFICIAL','GLOBAL','official-web','https://www.worldbank.org/',interval '1 day','CATALOGUED','Global macroeconomic and country indicators'),
('oecd','ECONOMY_FINANCE','multilateral-data','OECD','OECD','OFFICIAL','GLOBAL','official-web','https://www.oecd.org/',interval '1 day','CATALOGUED','Economic, productivity, skills and policy indicators'),
('wto','GEOPOLITICS_TRADE','trade-authority','WTO','World Trade Organization','OFFICIAL','GLOBAL','official-web','https://www.wto.org/',interval '1 day','CATALOGUED','Trade measures, disputes and agreements'),
('un-comtrade','GEOPOLITICS_TRADE','trade-data','United Nations','UN Comtrade','OFFICIAL','GLOBAL','official-web','https://comtradeplus.un.org/',interval '1 day','CATALOGUED','International goods trade flows'),
('fiu-nl','TRUST_FINANCIAL_CRIME','financial-crime-authority','FIU-Nederland','FIU-Nederland','OFFICIAL','NL','official-web','https://www.fiu-nederland.nl/',interval '1 day','CATALOGUED','Money-laundering and suspicious-transaction guidance'),
('eu-sanctions-map','TRUST_FINANCIAL_CRIME','sanctions','European Union','EU Sanctions Map','OFFICIAL','EU','official-web','https://www.sanctionsmap.eu/',interval '6 hours','CATALOGUED','EU sanctions regimes and restrictions'),
('kadaster','LOCATION_MOBILITY','register','Kadaster','Kadaster','OFFICIAL','NL','official-web','https://www.kadaster.nl/',interval '7 days','CATALOGUED','Property and location information'),
('rdw','LOCATION_MOBILITY','mobility-register','RDW','RDW','OFFICIAL','NL','official-web','https://www.rdw.nl/',interval '7 days','CATALOGUED','Vehicle and mobility information'),
('rws','LOCATION_MOBILITY','infrastructure','Rijkswaterstaat','Rijkswaterstaat','OFFICIAL','NL','official-web','https://www.rijkswaterstaat.nl/',interval '1 hour','CATALOGUED','Road, water and infrastructure disruptions'),
('cbs-demography','DEMOGRAPHY_SOCIAL','statistics','CBS','CBS bevolking & demografie','OFFICIAL','NL','official-web','https://www.cbs.nl/nl-nl/maatschappij/bevolking',interval '1 day','CATALOGUED','Population, households, migration and regional trends'),
('scp','DEMOGRAPHY_SOCIAL','social-research','SCP','Sociaal en Cultureel Planbureau','OFFICIAL','NL','official-web','https://www.scp.nl/',interval '7 days','CATALOGUED','Social and cultural trends and public attitudes'),
('ser','LABOR_SKILLS','advisory','SER','Sociaal-Economische Raad','OFFICIAL','NL','official-web','https://www.ser.nl/',interval '7 days','CATALOGUED','Labour, skills, work and socioeconomic policy'),
('news-official-press','MEDIA_COMMUNITIES','official-press','Government + regulators','Official press releases','OFFICIAL','NL/EU','search',null,interval '1 hour','CATALOGUED','Government, regulator and public-authority press releases'),
('sector-media','MEDIA_COMMUNITIES','trade-media','Sector publishers','Vakmedia','SPECIALIST','NL/EU','search',null,interval '6 hours','CATALOGUED','Industry-specific news and professional commentary'),
('linkedin-public-signals','MEDIA_COMMUNITIES','professional-network','LinkedIn','LinkedIn public signals','COMMUNITY','GLOBAL','connector','https://www.linkedin.com/',interval '6 hours','CATALOGUED','Professional conversation, hiring and company signals'),
('youtube-public-signals','MEDIA_COMMUNITIES','video-community','YouTube','YouTube public signals','COMMUNITY','GLOBAL','search','https://www.youtube.com/',interval '6 hours','CATALOGUED','Public product, customer and industry discussion'),
('reddit-public-signals','MEDIA_COMMUNITIES','community','Reddit','Reddit public signals','COMMUNITY','GLOBAL','search','https://www.reddit.com/',interval '6 hours','CATALOGUED','Weak-signal community discussion; never treated as authority'),
('search-demand','SEARCH_DIGITAL_DEMAND','search-demand','Search providers','Search demand','SPECIALIST','GLOBAL','provider',null,interval '6 hours','CATALOGUED','Search-volume, intent and emerging-query signals'),
('serp-competition','SEARCH_DIGITAL_DEMAND','serp','Search providers','SERP & competitor visibility','SPECIALIST','GLOBAL','provider',null,interval '6 hours','CATALOGUED','Rankings, SERP composition, domains and competitor visibility'),
('price-monitoring','PRICING','price-monitoring','Public web + providers','Market & competitor pricing','SPECIALIST','GLOBAL','search',null,interval '6 hours','CATALOGUED','Competitor, supplier and market price movements'),
('insurance-market','INSURANCE','insurance-market','Insurers + regulators','Insurance market','SPECIALIST','NL/EU','search',null,interval '7 days','CATALOGUED','Premium, coverage, insurability and acceptance-condition changes'),
('ma-deals','BUSINESS_REGISTERS_MA','deal-intelligence','Public registers + press','M&A and investment activity','SPECIALIST','NL/EU','search',null,interval '1 day','CATALOGUED','Acquisitions, investments, consolidations and strategic buyers'),
('company-registers','BUSINESS_REGISTERS_MA','company-register','Official registers','Company registers','OFFICIAL','NL/EU','provider',null,interval '1 day','CATALOGUED','Company status, filings, director changes and insolvency context'),

('afas','INTERNAL_FINANCE','erp-hr-finance','AFAS','AFAS','INTERNAL','TENANT','connector','https://www.afas.nl/',interval '1 hour','CATALOGUED','Finance, HR, CRM and operational data when connected'),
('sap','INTERNAL_OPERATIONS','erp','SAP','SAP','INTERNAL','TENANT','connector','https://www.sap.com/',interval '1 hour','CATALOGUED','ERP, supply chain, finance and operational data when connected'),
('dynamics365','INTERNAL_CUSTOMERS_SALES','crm-erp','Microsoft','Dynamics 365','INTERNAL','TENANT','connector','https://www.microsoft.com/en-us/dynamics-365',interval '1 hour','CATALOGUED','CRM, sales, service and ERP context when connected'),
('exact','INTERNAL_FINANCE','accounting','Exact','Exact','INTERNAL','TENANT','connector','https://www.exact.com/',interval '1 hour','CATALOGUED','Accounting, finance and business administration when connected'),
('topdesk','INTERNAL_SERVICE','service-management','TOPdesk','TOPdesk','INTERNAL','TENANT','connector','https://www.topdesk.com/',interval '1 hour','CATALOGUED','Service, incidents, assets and customer/internal support context'),
('salesforce','INTERNAL_CUSTOMERS_SALES','crm','Salesforce','Salesforce','INTERNAL','TENANT','connector','https://www.salesforce.com/',interval '1 hour','CATALOGUED','CRM, pipeline, customer and service context'),
('hubspot','INTERNAL_CUSTOMERS_SALES','crm-marketing','HubSpot','HubSpot','INTERNAL','TENANT','connector','https://www.hubspot.com/',interval '1 hour','CATALOGUED','CRM, marketing, pipeline and customer engagement'),
('power-bi','INTERNAL_SYSTEMS_DATA','bi','Microsoft','Power BI','INTERNAL','TENANT','connector','https://www.microsoft.com/en-us/power-platform/products/power-bi',interval '1 hour','CATALOGUED','Metrics, semantic models and management information'),
('microsoft-fabric','INTERNAL_SYSTEMS_DATA','data-platform','Microsoft','Microsoft Fabric','INTERNAL','TENANT','connector','https://www.microsoft.com/en-us/microsoft-fabric',interval '1 hour','CATALOGUED','Lakehouse, warehouse, pipelines, notebooks and analytics'),
('snowflake','INTERNAL_SYSTEMS_DATA','data-platform','Snowflake','Snowflake','INTERNAL','TENANT','connector','https://www.snowflake.com/',interval '1 hour','CATALOGUED','Cloud data warehouse and analytics context'),
('databricks','INTERNAL_SYSTEMS_DATA','data-platform','Databricks','Databricks','INTERNAL','TENANT','connector','https://www.databricks.com/',interval '1 hour','CATALOGUED','Lakehouse, AI, data engineering and ML context'),
('bigquery','INTERNAL_SYSTEMS_DATA','data-platform','Google Cloud','BigQuery','INTERNAL','TENANT','connector','https://cloud.google.com/bigquery',interval '1 hour','CATALOGUED','Cloud warehouse and analytics context'),
('azure-data-factory','INTERNAL_SYSTEMS_DATA','integration','Microsoft Azure','Azure Data Factory','INTERNAL','TENANT','connector','https://azure.microsoft.com/en-us/products/data-factory',interval '1 hour','CATALOGUED','Data integration, pipelines and dependencies'),
('sharepoint-onedrive','INTERNAL_KNOWLEDGE','documents','Microsoft','SharePoint & OneDrive','INTERNAL','TENANT','connector','https://www.microsoft.com/en-us/microsoft-365/sharepoint/collaboration',interval '1 hour','CATALOGUED','Documents, policies, project files and institutional knowledge'),
('google-drive','INTERNAL_KNOWLEDGE','documents','Google','Google Drive','INTERNAL','TENANT','connector','https://drive.google.com/',interval '1 hour','CATALOGUED','Documents, spreadsheets, presentations and shared knowledge'),
('notion','INTERNAL_KNOWLEDGE','knowledge','Notion','Notion','INTERNAL','TENANT','connector','https://www.notion.so/',interval '1 hour','CATALOGUED','Knowledge, plans, docs, databases and working context'),
('gmail','INTERNAL_KNOWLEDGE','email','Google','Gmail','INTERNAL','TENANT','connector','https://mail.google.com/',interval '1 hour','CATALOGUED','Customer, supplier and internal communication context'),
('google-calendar','INTERNAL_PROJECTS','calendar','Google','Google Calendar','INTERNAL','TENANT','connector','https://calendar.google.com/',interval '1 hour','CATALOGUED','Meetings, commitments, deadlines and operating rhythm'),
('microsoft-teams','INTERNAL_KNOWLEDGE','collaboration','Microsoft','Microsoft Teams','INTERNAL','TENANT','connector','https://www.microsoft.com/en-us/microsoft-teams/group-chat-software',interval '1 hour','CATALOGUED','Collaboration, decisions and communication context'),
('slack','INTERNAL_KNOWLEDGE','collaboration','Slack','Slack','INTERNAL','TENANT','connector','https://slack.com/',interval '1 hour','CATALOGUED','Collaboration, decisions and communication context'),
('jira','INTERNAL_PROJECTS','work-management','Atlassian','Jira','INTERNAL','TENANT','connector','https://www.atlassian.com/software/jira',interval '1 hour','CATALOGUED','Projects, issues, dependencies and delivery risk'),
('asana','INTERNAL_PROJECTS','work-management','Asana','Asana','INTERNAL','TENANT','connector','https://asana.com/',interval '1 hour','CATALOGUED','Projects, tasks, owners and delivery'),
('monday','INTERNAL_PROJECTS','work-management','monday.com','monday.com','INTERNAL','TENANT','connector','https://monday.com/',interval '1 hour','CATALOGUED','Work management, tasks and project status'),
('stripe','INTERNAL_FINANCE','payments','Stripe','Stripe','INTERNAL','TENANT','connector','https://stripe.com/',interval '1 hour','CATALOGUED','Payments, subscriptions and revenue evidence'),
('banking-open-banking','INTERNAL_FINANCE','banking','Banks / PSD2 providers','Bank & open-banking feeds','INTERNAL','TENANT','connector',null,interval '1 hour','CATALOGUED','Cash, transactions, working capital and financing evidence'),
('shopify','INTERNAL_CUSTOMERS_SALES','commerce','Shopify','Shopify','INTERNAL','TENANT','connector','https://www.shopify.com/',interval '1 hour','CATALOGUED','Orders, products, customers and ecommerce demand'),
('google-ads','INTERNAL_MARKETING','advertising','Google','Google Ads','INTERNAL','TENANT','connector','https://ads.google.com/',interval '1 hour','CATALOGUED','Campaign spend, demand, conversion and acquisition economics'),
('meta-ads','INTERNAL_MARKETING','advertising','Meta','Meta Ads','INTERNAL','TENANT','connector','https://www.facebook.com/business/ads',interval '1 hour','CATALOGUED','Campaign spend, audiences and conversion context'),
('search-console','INTERNAL_MARKETING','owned-search','Google','Google Search Console','INTERNAL','TENANT','connector','https://search.google.com/search-console/',interval '1 hour','CATALOGUED','Queries, impressions, clicks and organic-demand context'),
('analytics','INTERNAL_MARKETING','owned-analytics','Google / Adobe / others','Web analytics','INTERNAL','TENANT','connector',null,interval '1 hour','CATALOGUED','Traffic, behavior, conversion and channel performance'),
('supplier-master-internal','INTERNAL_SUPPLIERS','supplier-master','Customer systems','Supplier master & contracts','INTERNAL','TENANT','connector',null,interval '1 hour','CATALOGUED','Supplier dependency, performance, terms and continuity'),
('inventory-internal','INTERNAL_OPERATIONS','inventory','Customer systems','Inventory & warehouse','INTERNAL','TENANT','connector',null,interval '1 hour','CATALOGUED','Stock, shortages, turns, service levels and working capital'),
('production-internal','INTERNAL_OPERATIONS','production','Customer systems','Production / MES / operations','INTERNAL','TENANT','connector',null,interval '1 hour','CATALOGUED','Throughput, quality, downtime, capacity and operational constraints'),
('customer-feedback-internal','INTERNAL_SERVICE','feedback','Customer systems','Customer feedback / NPS / complaints','INTERNAL','TENANT','connector',null,interval '1 hour','CATALOGUED','Customer satisfaction, complaints and service-quality signals')
on conflict (source_key) do update set
  domain_key=excluded.domain_key,
  source_type=excluded.source_type,
  provider=excluded.provider,
  label=excluded.label,
  authority_tier=excluded.authority_tier,
  geography=excluded.geography,
  acquisition_mode=excluded.acquisition_mode,
  official_url=excluded.official_url,
  refresh_cadence=excluded.refresh_cadence,
  description=excluded.description,
  updated_at=now();
