-- Canonical unified content publication operations ledger.
-- One fail-closed execution truth for planned content through live proof, measurement and learning.

create table if not exists public.content_publication_obligations (
  id bigint generated by default as identity primary key,
  tenant_id text not null default 'canonical',
  publication_date date not null,
  planning_date date,
  due_at timestamptz,
  scheduled_for timestamptz,
  channel text not null,
  operational_channel text,
  experiment_id text,
  content_kind text not null default 'social',
  status text not null default 'PLANNED',
  delivery_status text,
  approval_required boolean not null default false,
  approval_deadline timestamptz,
  source_collaboration jsonb not null default '{}'::jsonb,
  relationship_signal jsonb not null default '{}'::jsonb,
  competitive_signal jsonb not null default '{}'::jsonb,
  market_signal jsonb not null default '{}'::jsonb,
  economic_signal jsonb not null default '{}'::jsonb,
  delivery_provider text,
  provider_channel_id text,
  content_id text,
  slug text,
  external_id text,
  canonical_url text,
  content_url text,
  review_required boolean not null default false,
  review_reason text,
  verify_due_at timestamptz,
  recheck_due_at timestamptz,
  expected_revenue_eur numeric(14,2),
  actual_revenue_eur numeric(14,2),
  actual_margin_eur numeric(14,2),
  generated_at timestamptz,
  approved_at timestamptz,
  dispatched_at timestamptz,
  published_at timestamptz,
  live_proven_at timestamptz,
  measured_at timestamptz,
  learned_at timestamptz,
  last_error text,
  recovery_attempts integer not null default 0,
  evidence jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  next_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint content_publication_obligations_tenant_date_channel_key unique (tenant_id, publication_date, channel),
  constraint content_publication_obligations_channel_check check (channel in ('linkedin_personal','linkedin_company','instagram','blog')),
  constraint content_publication_obligations_status_check check (status in ('PLANNED','GENERATED','APPROVED','DISPATCHED','PUBLISHED','LIVE_PROVEN','MEASURED','LEARNED','BLOCKED','FAILED'))
);

create index if not exists content_publication_obligations_due_idx
  on public.content_publication_obligations (tenant_id, publication_date, channel, status);

create or replace function public.content_publication_state_rank(p_status text)
returns integer
language sql
immutable
as $$
  select case upper(coalesce(p_status,''))
    when 'PLANNED' then 0
    when 'GENERATED' then 10
    when 'APPROVED' then 20
    when 'DISPATCHED' then 30
    when 'PUBLISHED' then 40
    when 'LIVE_PROVEN' then 50
    when 'MEASURED' then 60
    when 'LEARNED' then 70
    when 'BLOCKED' then 900
    when 'FAILED' then 901
    else -1
  end;
$$;

create or replace function public.sync_content_publication_obligations(
  p_from date default (timezone('Europe/Amsterdam', now()))::date,
  p_to date default (timezone('Europe/Amsterdam', now()))::date
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer := 0;
begin
  if p_from is null or p_to is null or p_to < p_from then
    raise exception 'INVALID_PUBLICATION_RANGE';
  end if;

  insert into public.content_publication_obligations (
    tenant_id,
    publication_date,
    planning_date,
    due_at,
    scheduled_for,
    channel,
    operational_channel,
    experiment_id,
    content_kind,
    status,
    delivery_status,
    next_action,
    updated_at
  )
  select
    coalesce(nullif(e.tenant_id,''), 'canonical'),
    e.calendar_date,
    e.calendar_date,
    (e.calendar_date::timestamp + interval '23 hours 59 minutes') at time zone 'Europe/Amsterdam',
    null,
    ch.channel,
    ch.channel,
    e.experiment_id::text,
    case when ch.channel = 'blog' then 'blog' else 'social' end,
    'PLANNED',
    'PLANNED',
    case
      when ch.channel = 'blog' then 'Selecteer exact één goedgekeurde due slug en lever via candidate PR → BG169 → live proof.'
      else 'Genereer/publiceer via de bestaande kanaallane en koppel live bewijs plus metrics terug.'
    end,
    now()
  from public.social_experiments e
  cross join lateral (
    select distinct value as channel
    from jsonb_array_elements_text(coalesce(e.target_channels,'[]'::jsonb)) as c(value)
  ) ch
  where e.calendar_date between p_from and p_to
    and coalesce(nullif(e.tenant_id,''), 'canonical') in ('canonical','bedrijfsgeheugen')
    and ch.channel in ('linkedin_personal','linkedin_company','instagram','blog')
  on conflict (tenant_id, publication_date, channel) do update
    set experiment_id = excluded.experiment_id,
        planning_date = coalesce(content_publication_obligations.planning_date, excluded.planning_date),
        due_at = coalesce(content_publication_obligations.due_at, excluded.due_at),
        operational_channel = coalesce(content_publication_obligations.operational_channel, excluded.operational_channel),
        content_kind = excluded.content_kind,
        delivery_status = coalesce(content_publication_obligations.delivery_status, excluded.delivery_status),
        next_action = case
          when public.content_publication_state_rank(content_publication_obligations.status) <= 10 then excluded.next_action
          else content_publication_obligations.next_action
        end,
        updated_at = now();

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

revoke all on function public.sync_content_publication_obligations(date,date) from public;

create or replace function public.record_content_publication_state(
  p_tenant_id text,
  p_publication_date date,
  p_channel text,
  p_status text,
  p_content_id text default null,
  p_slug text default null,
  p_external_id text default null,
  p_canonical_url text default null,
  p_evidence jsonb default '{}'::jsonb,
  p_metrics jsonb default '{}'::jsonb,
  p_next_action text default null,
  p_error text default null
)
returns public.content_publication_obligations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.content_publication_obligations%rowtype;
  v_old_rank integer;
  v_new_rank integer;
begin
  select * into v_row
  from public.content_publication_obligations
  where tenant_id = p_tenant_id
    and publication_date = p_publication_date
    and channel = p_channel
  for update;

  if not found then
    raise exception 'PUBLICATION_OBLIGATION_NOT_FOUND';
  end if;

  v_old_rank := public.content_publication_state_rank(v_row.status);
  v_new_rank := public.content_publication_state_rank(p_status);
  if v_new_rank < 0 then
    raise exception 'INVALID_PUBLICATION_STATE';
  end if;

  if v_row.status not in ('BLOCKED','FAILED')
     and p_status not in ('BLOCKED','FAILED')
     and v_new_rank < v_old_rank then
    raise exception 'STATE_REGRESSION_NOT_ALLOWED';
  end if;

  if p_status in ('LIVE_PROVEN','MEASURED','LEARNED')
     and coalesce(nullif(p_canonical_url,''), nullif(p_external_id,''), nullif(v_row.canonical_url,''), nullif(v_row.external_id,'')) is null then
    raise exception 'LIVE_PROOF_REQUIRED';
  end if;

  if p_status in ('LIVE_PROVEN','MEASURED','LEARNED')
     and coalesce(p_evidence, '{}'::jsonb) = '{}'::jsonb
     and coalesce(v_row.evidence, '{}'::jsonb) = '{}'::jsonb then
    raise exception 'LIVE_PROOF_REQUIRED';
  end if;

  update public.content_publication_obligations
  set status = p_status,
      delivery_status = p_status,
      content_id = coalesce(nullif(p_content_id,''), content_id),
      slug = coalesce(nullif(p_slug,''), slug),
      external_id = coalesce(nullif(p_external_id,''), external_id),
      canonical_url = coalesce(nullif(p_canonical_url,''), canonical_url),
      content_url = coalesce(nullif(p_canonical_url,''), content_url),
      evidence = case when coalesce(p_evidence,'{}'::jsonb) = '{}'::jsonb then evidence else evidence || p_evidence end,
      metrics = case when coalesce(p_metrics,'{}'::jsonb) = '{}'::jsonb then metrics else metrics || p_metrics end,
      next_action = coalesce(p_next_action, next_action),
      last_error = case when p_status in ('BLOCKED','FAILED') then coalesce(p_error, last_error) else null end,
      recovery_attempts = recovery_attempts + case when p_status in ('BLOCKED','FAILED') then 1 else 0 end,
      generated_at = case when p_status in ('GENERATED','APPROVED','DISPATCHED','PUBLISHED','LIVE_PROVEN','MEASURED','LEARNED') then coalesce(generated_at,now()) else generated_at end,
      approved_at = case when p_status in ('APPROVED','DISPATCHED','PUBLISHED','LIVE_PROVEN','MEASURED','LEARNED') then coalesce(approved_at,now()) else approved_at end,
      dispatched_at = case when p_status in ('DISPATCHED','PUBLISHED','LIVE_PROVEN','MEASURED','LEARNED') then coalesce(dispatched_at,now()) else dispatched_at end,
      published_at = case when p_status in ('PUBLISHED','LIVE_PROVEN','MEASURED','LEARNED') then coalesce(published_at,now()) else published_at end,
      live_proven_at = case when p_status in ('LIVE_PROVEN','MEASURED','LEARNED') then coalesce(live_proven_at,now()) else live_proven_at end,
      measured_at = case when p_status in ('MEASURED','LEARNED') then coalesce(measured_at,now()) else measured_at end,
      learned_at = case when p_status = 'LEARNED' then coalesce(learned_at,now()) else learned_at end,
      updated_at = now()
  where tenant_id = p_tenant_id
    and publication_date = p_publication_date
    and channel = p_channel
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.record_content_publication_state(text,date,text,text,text,text,text,text,jsonb,jsonb,text,text) from public;

create or replace view public.content_operations_cockpit as
select
  o.*,
  (o.publication_date = (timezone('Europe/Amsterdam', now()))::date) as is_due_today,
  (o.publication_date < (timezone('Europe/Amsterdam', now()))::date
    and o.status not in ('LIVE_PROVEN','MEASURED','LEARNED')) as is_overdue,
  case
    when o.status in ('LIVE_PROVEN','MEASURED','LEARNED') then 'proven'
    when o.status in ('BLOCKED','FAILED') then 'attention'
    when o.publication_date < (timezone('Europe/Amsterdam', now()))::date then 'overdue'
    else 'open'
  end as operational_state
from public.content_publication_obligations o;

create or replace view public.v_content_publication_operations as
select * from public.content_operations_cockpit;

select public.sync_content_publication_obligations(date '2026-09-14', date '2026-12-31');

do $$
declare
  v_blog_count integer;
begin
  select count(*) into v_blog_count
  from public.content_publication_obligations
  where tenant_id in ('canonical','bedrijfsgeheugen')
    and channel = 'blog'
    and publication_date between date '2026-09-14' and date '2026-12-31';

  if v_blog_count <> 109 then
    raise exception 'BLOG_CALENDAR_INCOMPLETE expected=109 actual=%', v_blog_count;
  end if;
end;
$$;
