import { createClient } from 'npm:@supabase/supabase-js@2';

const TOKEN_HASH='0ca9abe4469bea5e83355a193662d5d9455b04f7b6f76a668755e87348eadb75';
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store'}});
async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('');}
const tenantOf=(b:any)=>String(b?.tenantId||b?.post?.tenantId||b?.snapshot?.tenantId||b?.evaluation?.tenantId||b?.experiment?.tenantId||b?.learning?.tenantId||b?.application?.tenantId||b?.decision?.tenantId||b?.projection?.tenantId||b?.obligation?.tenantId||b?.data?.tenantId||'canonical');
const camelPost=(p:any)=>({postId:p.post_id,tenantId:p.tenant_id,platform:p.platform,channelId:p.channel_id,channelName:p.channel_name,channelKind:p.channel_kind,publishedAt:p.published_at,format:p.format,funnelStage:p.funnel_stage,contentPillar:p.content_pillar,hookType:p.hook_type,narrativeType:p.narrative_type,emotion:p.emotion,ctaType:p.cta_type,learningStatus:p.learning_status,learningId:p.learning_id});

Deno.serve(async(req:Request)=>{
  if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);
  if(await sha256(req.headers.get('x-bg-service-token')||'')!==TOKEN_HASH)return json({error:'UNAUTHORIZED'},401);
  let body:any;try{body=await req.json()}catch{return json({error:'INVALID_JSON'},400)}
  const action=String(body?.action||''),tenantId=tenantOf(body),url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  if(!url||!key)return json({error:'SERVER_CONFIG'},500);
  const db=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});
  try{
    if(action==='put_post'){
      const p=body.post||{};if(!p.postId||!p.platform||!p.externalPostId)return json({error:'INVALID_POST'},400);
      const row={tenant_id:tenantId,post_id:p.postId,platform:p.platform,channel_id:p.channelId||null,channel_name:p.channelName||null,channel_kind:p.channelKind||null,external_post_id:p.externalPostId,published_at:p.publishedAt||null,content_hash:p.contentHash||null,topic:p.topic||null,content_pillar:p.contentPillar||null,audience:p.audience||null,funnel_stage:p.funnelStage||null,format:p.format||null,hook_type:p.hookType||null,narrative_type:p.narrativeType||null,emotion:p.emotion||null,cta_type:p.ctaType||null,source_campaign_id:p.sourceCampaignId||null,updated_at:new Date().toISOString()};
      const {error}=await db.from('social_posts').upsert(row,{onConflict:'tenant_id,post_id'});if(error)throw error;return json({stored:true});
    }
    if(action==='append_snapshot'){
      const s=body.snapshot||{};if(!s.snapshotId||!s.postId||!s.observedAt)return json({error:'INVALID_SNAPSHOT'},400);
      const {data:post,error:postError}=await db.from('social_posts').select('published_at').eq('tenant_id',tenantId).eq('post_id',s.postId).maybeSingle();if(postError)throw postError;
      const ageHours=post?.published_at?(new Date(s.observedAt).getTime()-new Date(post.published_at).getTime())/36e5:null;
      const row={tenant_id:tenantId,snapshot_id:s.snapshotId,post_id:s.postId,observed_at:s.observedAt,age_hours:Number.isFinite(ageHours)?ageHours:null,source:s.source||'unknown',source_event_id:s.sourceEventId||s.snapshotId,data_quality:s.dataQuality||'OBSERVED',metrics:s.metrics||{}};
      const {data:existing}=await db.from('social_metric_snapshots').select('snapshot_id,metrics,source_event_id').eq('tenant_id',tenantId).eq('snapshot_id',s.snapshotId).maybeSingle();
      if(existing){if(JSON.stringify(existing.metrics)!==JSON.stringify(row.metrics)||existing.source_event_id!==row.source_event_id)return json({error:'SNAPSHOT_CONFLICT'},409);return json({stored:false,duplicate:true});}
      const {error}=await db.from('social_metric_snapshots').insert(row);if(error){if(error.code==='23505')return json({error:'SNAPSHOT_CONFLICT'},409);throw error;}return json({stored:true});
    }
    if(action==='get_post'){const {data,error}=await db.from('social_posts').select('*').eq('tenant_id',tenantId).eq('post_id',body.postId).maybeSingle();if(error)throw error;return json({post:data?camelPost(data):null});}
    if(action==='get_snapshots'){const {data,error}=await db.from('social_metric_snapshots').select('*').eq('tenant_id',tenantId).eq('post_id',body.postId).order('observed_at',{ascending:true});if(error)throw error;return json({snapshots:(data||[]).map((r:any)=>({snapshotId:r.snapshot_id,postId:r.post_id,tenantId:r.tenant_id,observedAt:r.observed_at,ageHours:r.age_hours,source:r.source,sourceEventId:r.source_event_id,dataQuality:r.data_quality,metrics:r.metrics}))});}
    if(action==='list_due_posts'){
      const now=new Date(body.now||Date.now());const {data:posts,error}=await db.from('social_posts').select('*').eq('tenant_id',tenantId).not('published_at','is',null).lte('published_at',new Date(now.getTime()-24*36e5).toISOString());if(error)throw error;
      const {data:evals,error:e2}=await db.from('social_learning_evaluations').select('post_id,window_hours').eq('tenant_id',tenantId);if(e2)throw e2;const done=new Set((evals||[]).map((e:any)=>`${e.post_id}:${e.window_hours}`)),out:any[]=[];
      for(const p of posts||[])for(const w of [24,48,72])if(now.getTime()>=new Date(p.published_at).getTime()+w*36e5&&!done.has(`${p.post_id}:${w}`))out.push({...camelPost(p),dueWindow:w});
      return json({posts:out});
    }
    if(action==='get_cohort'){
      const input=body.query||{},target=input.post||{},windowHours=Number(input.windowHours||24),tolerance=Number(input.toleranceHours||6);
      let pq=db.from('social_posts').select('*').eq('tenant_id',tenantId).neq('post_id',target.postId).not('published_at','is',null);
      if(target.platform)pq=pq.eq('platform',target.platform);if(target.channelKind)pq=pq.eq('channel_kind',target.channelKind);if(target.format)pq=pq.eq('format',target.format);if(target.funnelStage)pq=pq.eq('funnel_stage',target.funnelStage);if(target.contentPillar)pq=pq.eq('content_pillar',target.contentPillar);
      const {data:posts,error}=await pq.order('published_at',{ascending:false}).limit(30);if(error)throw error;const ids=(posts||[]).map((p:any)=>p.post_id);if(!ids.length)return json({posts:[]});
      const {data:snaps,error:sErr}=await db.from('social_metric_snapshots').select('*').eq('tenant_id',tenantId).in('post_id',ids);if(sErr)throw sErr;const byPost=new Map<string,any[]>();for(const s of snaps||[]){const a=byPost.get(s.post_id)||[];a.push(s);byPost.set(s.post_id,a);}
      const out:any[]=[];for(const p of posts||[]){let best:any=null,delta=Infinity;for(const s of byPost.get(p.post_id)||[]){const age=Number.isFinite(s.age_hours)?Number(s.age_hours):(new Date(s.observed_at).getTime()-new Date(p.published_at).getTime())/36e5;const d=Math.abs(age-windowHours);if(d<=tolerance&&d<delta){best=s;delta=d;}}if(best)out.push({...camelPost(p),observedAt:best.observed_at,ageHours:best.age_hours,metrics:best.metrics});}
      return json({posts:out});
    }
    if(action==='put_evaluation'){const e=body.evaluation||{};const row={tenant_id:tenantId,evaluation_id:e.evaluationId,post_id:e.postId,window_hours:e.windowHours,observed_at:e.observedAt,metric_vector:e.metricVector||{},cohort_size:e.cohortSize||0,evidence:e.evidence||null};const {error}=await db.from('social_learning_evaluations').upsert(row,{onConflict:'tenant_id,evaluation_id'});if(error)throw error;return json({stored:true});}
    if(action==='upsert_experiment'){const e=body.experiment||{};if(!e.experimentId||!e.hypothesis||!e.primaryMetric||!e.startedAt)return json({error:'INVALID_EXPERIMENT'},400);const row={tenant_id:tenantId,experiment_id:e.experimentId,hypothesis:e.hypothesis,primary_metric:e.primaryMetric,comparison_scope:e.comparisonScope||{},started_at:e.startedAt,ended_at:e.endedAt||null,status:e.status||'ACTIVE',updated_at:new Date().toISOString()};const {error}=await db.from('social_experiments').upsert(row,{onConflict:'tenant_id,experiment_id'});if(error)throw error;return json({stored:true});}
    if(action==='upsert_learning'){const l=body.learning||{};const row={tenant_id:tenantId,learning_id:l.learningId,fingerprint:l.fingerprint,component_scope:l.componentScope||'social_components',claim:l.claim||'',baseline_definition:l.baselineDefinition||null,effect_metric:l.effectMetric||null,effect_size:l.effectSize??null,sample_size:l.sampleSize||0,confidence:l.confidence||0,evidence_window:l.evidenceWindow||null,status:l.status||'CANDIDATE',first_seen_at:l.firstSeenAt||null,last_validated_at:l.lastValidatedAt||null,expires_or_review_at:l.expiresOrReviewAt||null,evidence_refs:l.evidenceRefs||[],updated_at:new Date().toISOString()};const {error}=await db.from('social_learnings').upsert(row,{onConflict:'tenant_id,learning_id'});if(error)throw error;return json({stored:true});}
    if(action==='list_current_learnings'){const {data,error}=await db.from('social_learnings').select('*').eq('tenant_id',tenantId).in('status',['PROVEN','TESTING','WEAKENING']).order('confidence',{ascending:false}).limit(50);if(error)throw error;return json({learnings:(data||[]).map((r:any)=>({learningId:r.learning_id,fingerprint:r.fingerprint,componentScope:r.component_scope,claim:r.claim,baselineDefinition:r.baseline_definition,effectMetric:r.effect_metric,effectSize:r.effect_size,sampleSize:r.sample_size,confidence:r.confidence,evidenceWindow:r.evidence_window,status:r.status,firstSeenAt:r.first_seen_at,lastValidatedAt:r.last_validated_at,expiresOrReviewAt:r.expires_or_review_at,evidenceRefs:r.evidence_refs}))});}
    if(action==='record_application'){const a=body.application||{};const row={tenant_id:tenantId,application_id:a.applicationId,post_id:a.postId,learning_id:a.learningId,decision_id:a.decisionId||null,applied_at:a.appliedAt||new Date().toISOString(),application_role:a.applicationRole||'PRIMARY',expected_effect:a.expectedEffect??null,actual_effect:a.actualEffect??null,verification_status:a.verificationStatus||'PENDING',updated_at:new Date().toISOString()};const {error}=await db.from('social_learning_applications').upsert(row,{onConflict:'tenant_id,application_id'});if(error)throw error;return json({stored:true});}
    if(action==='record_decision'){const d=body.decision||{};const {error}=await db.from('social_learning_decisions').upsert({tenant_id:tenantId,decision_id:d.decisionId,post_id:d.postId,decision:d,recorded_at:d.recordedAt||new Date().toISOString()},{onConflict:'tenant_id,decision_id'});if(error)throw error;return json({tenantId,decisionId:d.decisionId,postId:d.postId});}
    if(action==='reconcile_application'){const a=body.application||{};const {error}=await db.from('social_learning_applications').update({actual_effect:a.actualEffect??null,verification_status:a.verificationStatus||'VERIFIED',updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('application_id',a.applicationId);if(error)throw error;return json({stored:true});}
    if(action==='reconcile_applications'){const d=body.data||{};const {error}=await db.from('social_learning_applications').update({actual_effect:d.effect??null,verification_status:d.verificationStatus||'VERIFIED',updated_at:new Date().toISOString()}).eq('tenant_id',tenantId).eq('post_id',d.postId);if(error)throw error;return json({stored:true});}
    if(action==='record_obligation'){const o=body.obligation||{};const {error}=await db.from('social_learning_obligations').upsert({tenant_id:tenantId,obligation_id:o.id,type:o.type||'MISSED_OBLIGATION',owner:o.owner||'POWERHOUSE_SOCIAL_LEARNING',post_id:o.postId||null,window_hours:o.windowHours||null,due_at:o.dueAt||null,status:o.status||'OPEN',payload:o,updated_at:new Date().toISOString()},{onConflict:'tenant_id,obligation_id'});if(error)throw error;return json({stored:true});}
    if(action==='get_projection'){const {data,error}=await db.from('social_learning_projections').select('projection').eq('tenant_id',tenantId).maybeSingle();if(error)throw error;return json({projection:data?.projection||null});}
    if(action==='put_projection'){const p=body.projection||{};const {error}=await db.from('social_learning_projections').upsert({tenant_id:tenantId,version:p.version,projection:p,updated_at:new Date().toISOString()},{onConflict:'tenant_id'});if(error)throw error;return json({stored:true});}
    return json({error:'INVALID_ACTION'},400);
  }catch(error:any){console.error(error);return json({error:'STORE_OPERATION_FAILED'},500);}
});
